### ISSUE TITLE
Changing the `src` folder

### ISSUE THREAD

**Issue by marreman** [mozilla-neutrino/neutrino-dev#100]
I can't seem to find a way to change the `src` folder via configuration. Changing [this line](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/src/index.js#L14) in the `neutrino-preset-web` preset solves it. Is there any way to do it properly?

**Comment by eliperelman** [comment]
So, the source directory drives a number of different pieces of configuration, and as you can see from the file, it's used in a few places. Using either [simple overrides or advanced ones](https://neutrino.js.org/customization/) will let you change how this operates. For advanced customization:

```js
module.exports = ({ config }) => {
  const oldSrc = path.join(__dirname, 'src');
  const newSrc = path.join(__dirname, 'lib');
  
  config
    .entry('index')
    .delete(oldSrc)
    .add(newSrc);

  config.module
    .rule('compile')._include
      .delete(oldSrc);

  config.module.rule('compile').add(newSrc)
  config.devServer.contentBase(newSrc);

  if (process.env.NODE_ENV !== 'development') {
    config
      .plugin('copy')
      .inject((Plugin, args) => {
        args[0].context = newSrc;
        return new Plugin(...args);
      });
  }
};
```

That should at least give you a push in the right direction, and this should be a little easier in v5.

**Comment by eliperelman** [comment]
That said, maybe it would be nice if Neutrino had options for some of these top-level configuration parts like source and destination. I'll see about adding that in for v5.

**Comment by marreman** [comment]
Thanks for the quick reply! Nice to know I didn't miss anything. Big ups to the Neutrino initiative!
