### ISSUE TITLE
Set Jest's testEnvironment to "node" when not targetting a browser

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#1020]
Currently the `@neutrinojs/jest` preset doesn't define `testEnvironment`, so Jest uses the default of `'jsdom'`:
https://jestjs.io/docs/en/configuration.html#testenvironment-string

This seems fine for projects that are targetting the browser (eg `@neutrinojs/web`, ...), however for `@neutrinojs/node` or `@neutrinojs/library` (with `target: 'node'`) a more suitable value for `testEnvironment` would be `'node'`.

I'm not sure of the best way of checking within `@neutrinojs/jest` when to override the environment - hardcoding presets is a non-starter, so perhaps by inspecting the babel preset-env compile targets?

**Comment by eliperelman** [comment]
What about getting the value of `neutrino.config.target()`?
