### ISSUE TITLE
Extract default presets from devDependencies

### ISSUE THREAD

**Issue by sheerun** [mozilla-neutrino/neutrino-dev#107]
I guess it would make more sense than using no presets at all by convention, wouldn't it?

Of course one could override just like now with `config.presets` configuration.

**Comment by eliperelman** [comment]
I'm not sure we can realistically tackle this because we don't have a mechanism for determining load order other than what is specified via the CLI.

**Comment by sheerun** [comment]
Maybe we could do topological sort and specify loader dependencies instead?

e.g. module.requireLoaders = ["babel"] for jest preset, and make neutino automatically order presets, so ones containing babel come before jest preset

**Comment by barraponto** [comment]
Since I spend most of my time teaching and mentoring, I have to ask: please don't.
Explicit is better than implicit. I think having the presets ordered in `package.json` is amazingly simple.

**Comment by eliperelman** [comment]
Yeah, I'm starting to think that this is also a documentation issue. For example, we should have a well-defined recommended load order:

&darr; Option-based overrides
&darr; Linting presets/middleware
&darr; Application presets
&darr; Testing presets/middleware
&darr; Project-based overrides

**Comment by jefffriesen** [comment]
I also think explicitly setting the presets is clearer.

**Comment by eliperelman** [comment]
Leaving this open until we can better document the recommended middleware loading order.

**Comment by eliperelman** [comment]
I don't think there can be a recommended default loading order, as things can be woven together as the user see fit the priority. Closing, and will triage issues as they arise from load order.
