### ISSUE TITLE
DeprecationWarning during neutrino start

### ISSUE THREAD

**Issue by sheerun** [mozilla-neutrino/neutrino-dev#108]
Excuse me if you already know about this issue. I get following when using neutrino with react preset:

Waiting for initial build to finish(node:65014) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by eliperelman** [comment]
This is a known issue, and in v5 we are hiding the deprecation notice until it is resolved. 

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/bin/neutrino#L3
