### ISSUE TITLE
Allow for async resolution of presets

### ISSUE THREAD

**Issue by jaridmargolin** [mozilla-neutrino/neutrino-dev#112]
I have some async work that needs to be done prior to configuration. Specifically I need to hit an endpoint and utilize the returned data in my `DefinePlugin` config. It would be great if I could do this async work within my preset:

```
module.exports = async ({ config }) => {
  const result = await doSomeAsyncStuff()
  ...
})
```

Architecturally would there be any reason this could not be done?

**Comment by eliperelman** [comment]
I don't see any problem with it. It will probably mean needing to make a change to Neutrino's `use` to support Promised middleware, which should be pretty simple.

**Comment by eliperelman** [comment]
Hmm, while this is easy enough to handle through the CLI, any API use of `.use` really gets a wrench thrown in it:

```js
neutrino.use(alpha);
neutrino.use(beta);
neutrino.use(gamma);

if (x) {
  neutrino.use(delta);
}
```

Each of these would need to wait for the previous use to finish, since we could not know which are async and which are not. If you have async work that needs to be done, you should probably consider doing that prior to starting Neutrino, maybe write it to a file, then have your preset import it.

**Comment by jaridmargolin** [comment]
I was able to hack around and get this working locally by modifying the Neutrino constructor where the presets are required. I'll open up a PR with my approach so we can discuss details of implementation.

Thanks.

**Comment by jaridmargolin** [comment]
Ahh.. Looks like I made my changes on an out of date distribution.

**Comment by jaridmargolin** [comment]
Looking at your comment regarding `use`... Internally, can this method just push tasks onto a queue?

**Comment by jaridmargolin** [comment]
- or even if use doesn't push onto a queue, why not just always have `use` return a promise:

```
Promise.resolve(preset(this, options));
```

And then you could change usage:

```
neutrino.use(alpha)
  .then(() => neutrino.use(beta));
  .then(() => neutrino.use(gamma));
  .then(() => x ? neutrino.use(delta) : undefined);
```

---

I think this is a more sound solution... `selenium-webdriver` at one point tried to implement an internal queue for its promises and was a mess to work with (they are currently in the promise of removing).

**Comment by eliperelman** [comment]
A Queue is one possible solution, but it makes using `use` from middleware tricky. Essentially a call to `use` would then do nothing but put middleware on the stack for unwinding later. This means that everything within middleware must also be pushed onto the queue so it is done in the correct order:

```js
use(middleware, options) {
  this.queue.enqueue(() => Promise.resolve(middleware(options)));
}
```

```js
// alpha middleware
module.exports = neutrino => neutrino.config.devtool('eval');
```

```js
const alpha = require('alpha');

module.exports = neutrino => {
  neutrino.use(alpha);
  neutrino.use(() => {
    if (neutrino.config.get('devtool') === 'eval') {
      // ...
    }
  });
};
```

**Comment by eliperelman** [comment]
Note that I'm not against the Promisified queue, it's just an extra level of complexity that we have not yet added.

**Comment by eliperelman** [comment]
Using a Promise chain on the other hand can get unwieldy. Since the CLI would have to use this technique, it ends up emulating its own queue:

```js
const api = new Neutrino();
const promises = [];

presets.forEach(preset => {
  promises.push(neutrino.use(preset));
});

// unwind the Promise stack
```

I think you're probably on the right track by putting the queue itself into the Neutrino API, and then exposing a method for unwinding the queue.

**Comment by jaridmargolin** [comment]
I use bluebirds `Promise.each()` to walk through the presets. Barely changes the implementation but adds an additional dependency.

**Comment by eliperelman** [comment]
As discussed in the PR, we will revisit async presets in the future but at the moment we aren't ready to go down that route.
