### ISSUE TITLE
Modifying a previous preset

### ISSUE THREAD

**Issue by barraponto** [mozilla-neutrino/neutrino-dev#114]
In my [PostCSS preset][neutrino-preset-postcss], I am assuming the user has installed `neutrino-preset-web` since I'm modifying the `css` rules. I mention this in the documentation and also in my `package.json` as a `peerDependency`.

Should I do something in my code? Is this the right approach?
https://github.com/barraponto/neutrino-preset-postcss/blob/master/src/index.js

[neutrino-preset-postcss]: https://github.com/barraponto/neutrino-preset-postcss/blob/master/src/index.js

**Comment by eliperelman** [comment]
I think you're doing the right thing by documenting the load order, and it's something we should probably document a little better as well. I guess if you wanted a little more enforcement, you could make your preset throw if it doesn't find the other loader:

```js
if (!neutrino.config.module.rules.has('css')) {
  throw new Error('Ensure postcss middleware is loaded after Web middleware');
}
```

Something similar.
