### ISSUE TITLE
Remove process.exit(0) on run.

### ISSUE THREAD

**Issue by jaridmargolin** [mozilla-neutrino/neutrino-dev#118]
```
  api[command](args)
    .then(() => process.exit(0))
    .catch(err => {
      if (err) {
        console.error(err);
      }

      process.exit(1);
    });
```

I am curious as to why `.then(() => process.exit(0))` needs to be chained off of the api command. As long as the catch does not hit, the process will already exit with a 0, correct?

This also has consequences of stopping execution of various plugins. For example [BundleAnalyzer](https://github.com/th0r/webpack-bundle-analyzer/blob/master/src/BundleAnalyzerPlugin.js#L33) executes after webpack has compiled.

**Comment by eliperelman** [comment]
Resolved in #119.
