### ISSUE TITLE
Modify the same plugin from multiple presets

### ISSUE THREAD

**Issue by barraponto** [mozilla-neutrino/neutrino-dev#124]
In neutrino v4 (webpack-chain v1), `config.plugin('example').inject((Plugin, options) => new Plugin(options))` is used to modify the plugin options. How can I modify the same plugin again from another profile?

**Comment by barraponto** [comment]
For a use-case, consider a project using both https://github.com/barraponto/neutrino-preset-vue/tree/3b757133de7f9285f71a0154c5c8ee744879efbe and https://github.com/barraponto/neutrino-preset-stylelint-standard (released on npm as `neutrino-preset-stylelint-standard`)

**Comment by eliperelman** [comment]
Unfortunately webpack-chain v1 does have a good answer to this. It would involve merging the `.args` from the low-level access of the plugin, and then you could take your pick of array-merging strategy. In Neutrino v5 and hence webpack-chain v3 this will be better.

**Comment by eliperelman** [comment]
Closing in anticipation of v5. Please re-open if something isn't working as expected.
