### ISSUE TITLE
Extend neutrino-preset-web with source maps 

### ISSUE THREAD

**Issue by BrunoFenzl** [mozilla-neutrino/neutrino-dev#126]
Hi!

First time using Neutrino. I'm customising my presets for my current project and besides some custom eslint rules I desperately need sourcemaps. Eslint rules are working perfectly and extending neutrino is a joy! Now, the sourcemaps…
I searched everywhere but could not find any information about extending the web preset to output them. Is there any resource around? I'm probably missing somewhere obvious…

This is what I got working so far:
```

const lint = require('neutrino-preset-airbnb-base');
const merge = require('deepmerge');
const webpack = require('webpack');

// const CWD = process.cwd();
// const pkgStr = path.join(CWD, 'package.json');
// const PKG = require(pkgStr);


module.exports = (neutrino) => {
	// const hasSourceMap = (PKG.dependencies && 'source-map-support' in PKG.dependencies) ||
	// 	(PKG.devDependencies && 'source-map-support' in PKG.devDependencies);
	// Implement custom linting
	lint(neutrino);

	neutrino.config.module
		.rule('lint')
		.loader('eslint', props => merge(props, {
			options: {
				globals: [
					'describe',
					'expect',
					'jest',
					'test',
					'document',
					'window',
					'fetch',
					'XMLHttpRequest',
					'HTMLElement',
					'HTMLImageElement',
					'Blob',
					'srcid',
				],
				rules: {
					'no-console': 0,
					'no-tabs': 0,
					indent: ['error', 'tab'],
					'no-param-reassign': 0,
					'no-underscore-dangle': 0,
					'max-len': 0,
					'no-unused-expressions': 0,
					'no-mixed-operators': 0,
					'func-names': 0,
					'no-restricted-properties': 0,
					'no-continue': 0,
					'prefer-rest-params': 0,
					'no-restricted-syntax': 0,
					'no-use-before-define': 0,
				},
				baseConfig: {
					extends: ['airbnb-base'],
				},
			},
		}));

	// copied from neutrino-preset-node. Not working…
	neutrino.config.plugin('banner')
		.use(webpack.BannerPlugin, {
			banner: `require('source-map-support').install();`,
			raw: true,
			entryOnly: true,
		});
};

```
Any help is more than appreciated!

**Comment by jaridmargolin** [comment]
Hey @BrunoFenzl - You could try `config.devtool('source-map')`. Does this generate what you are looking for?

**Comment by eliperelman** [comment]
Jarid is correct, and in v5 `source-map` will be the default during development. Related notes:

https://github.com/mozilla-neutrino/neutrino-dev/pull/105

**Comment by eliperelman** [comment]
Closing as resolved. Please re-open if these suggestions do not work properly. Thanks!

**Comment by jefffriesen** [comment]
I just tested this and it worked (using v4)
https://github.com/jefffriesen/neutrino-react-reference/blob/master/neutrino-custom-tcomb.js#L5

**Comment by BrunoFenzl** [comment]
Thank you @jaridmargolin and all others. `config.devtool('source-map')` worked perfectly, all clear now.
