### ISSUE TITLE
Check location of failed require in requireMiddleware

### ISSUE THREAD

**Issue by jaridmargolin** [mozilla-neutrino/neutrino-dev#130]
The following line should additionally check the module lookup that failed:

```
if (!/Cannot find module/.test(exception.message))
```

It ends up being a false negative on nested require fails.

**Comment by eliperelman** [comment]
I have removed this test in my functional PR, and hopefully any errors should bubble up when there are problems requiring.

**Comment by eliperelman** [comment]
Should be unnecessary now via #137.
