### ISSUE TITLE
default publicPath of './' causes 404 with deep paths

### ISSUE THREAD

**Issue by nlf** [mozilla-neutrino/neutrino-dev#133]
Currently the `publicPath` defaults to `./`, so the generated `index.html` file has paths like `./index.bundle.js` referenced in it.

This works fine when loading the base page in the dev server at `http://localhost:5000`, but if you happen to start browsing in your dev server at a deep link like `http://localhost:5000/some/deep/link` the bundled js files return a 404 because of the leading `.`.

A (possibly naive) fix is changing the `publicPath` to `/` instead, which changes the bundle js references to `/index.bundle.js` which work from any url depth in the dev server. I haven't looked very deeply to see if there are any negative consequences to this change, but from working with this change on a project myself it seems to not cause any problems in either the dev server or built output.

Maybe I'm just doing something wrong, but I thought I'd at least bring it up. Thoughts?

**Comment by eliperelman** [comment]
@nlf I've encountered this same issue, and it stems from the different ways you could build an application. Unfortunately some projects need the `./` and others need `/`, just depending on factors like single-page vs. multipage, client-side routing, history mechanisms, etc.

We opted to use the relative path, and hopefully being able to use customization to switch to `/` is sufficient. Unfortunately switching everyone to use `/` would cause similar problems for others, especially regarding sub-paths within a host.

Hope that makes sense. :smile:

**Comment by nlf** [comment]
I kind of suspected that might be the case, my gut feeling was that it seemed like the majority of use cases would benefit from an absolute path but it sounds like that's not so?

In any case it took me a while to find the setting and how to fix it for my needs, so maybe it's at least worth mentioning in the docs somewhere :)

**Comment by eliperelman** [comment]
Yeah, I think relative is a good default for many use cases, and this could definitely be added to the docs. If you wanted to create a PR for it it would be very welcome. Otherwise I'll leave this open until it's documented.
