### ISSUE TITLE
neutrino-preset-airbnb-base 5.0.0 incorrect configuration

### ISSUE THREAD

**Issue by Dbuggerx** [mozilla-neutrino/neutrino-dev#143]
After upgrading to 5.0.0, in order **to get eslint to work properly with rule customizations**, I've had to tweak the suggested configurations from the documentation:

## When customizing the rules in my _package.json_:

**documentation**:
```javascript
// .eslintrc.js
const Neutrino = require('neutrino');
const pkg = require('./package.json');
const api = new Neutrino();

// If the Airbnb preset is not included in pkg.neutrino.presets,
// use it manually:
api.use(require('neutrino-preset-airbnb-base'));

// Add the rest of the presets:
pkg.neutrino.presets.map(preset => api.use(preset));

module.exports = api.eslintrc();
```

**mine** (note the "Add configuration overrides" block):
```javascript
// .eslintrc.js
const Neutrino = require('neutrino');
const pkg = require('./package.json');
const api = new Neutrino();

// If the Airbnb preset is not included in pkg.neutrino.presets,
// use it manually:
api.use(require('neutrino-preset-airbnb-base'));

// Add the rest of the presets:
pkg.neutrino.presets.map(preset => api.use(preset));

// Add configuration overrides
const merge = require('deepmerge');
api.config.module
  .rule('lint')
  .use('eslint')
  .tap(options => merge(options, pkg.neutrino.config.module.rule.lint.use.eslint.options));

module.exports = api.eslintrc();
```

## Using as middleware:

**documentation**:
```javascript
// If using as middleware, remove from presets and .use it from your override:
const airbnb = require('neutrino-preset-airbnb-base');

module.exports = neutrino => {
  neutrino.use(airbnb, {
    rules: {
      semi: 'off'
    }
  });
};
```

**mine** (had to add "rules" to "eslint"): 

```javascript
const airbnb = require('neutrino-preset-airbnb-base');

module.exports = (neutrino) => {
  neutrino.use(airbnb, {
    eslint: {
      rules: {
        semi: 'off'
      }
    }
  });
};
```

So, I'd like to know if I'm doing anything wrong, or maybe the documentation is incorrect?

**Comment by eliperelman** [comment]
There was an error in the documentation, but has now been fixed. Could you please try it again to see if what you have correlates with what's now in the docs?

**Comment by eliperelman** [comment]
I believe this is now resolved with our docs fixes and re-syncing the package READMEs to what we have in docs. Please re-open if the changes are still not clear or incorrect. Thanks!

**Comment by Dbuggerx** [comment]
@eliperelman I still have the reported issues, and my proposed solutions still apply.
I'm even more confused now.
**Without my proposed changes, my rules customizations do not work.**
Can you please reopen this issue and help me clarify this?
Thanks

**Comment by eliperelman** [comment]
@Dbuggerx can you share your changes so we can figure out what is wrong?

**Comment by Dbuggerx** [comment]
@eliperelman I've already done that in my first message (the **mine** blocks). Please let me know if you have any questions.

**Comment by eliperelman** [comment]
@Dbuggerx right, and as noted, the documentation has been updated. Could you show me where the documentation and your proposed solutions do not align?

**Comment by Dbuggerx** [comment]
@eliperelman , for example: [in this page](https://neutrino.js.org/presets/neutrino-preset-airbnb-base/#advanced-configuration), "// If using as middleware...", and "// .eslintrc.js"

**Comment by eliperelman** [comment]
Ahhh, now I see. I'll update.
