### ISSUE TITLE
add typescript preset

### ISSUE THREAD

**Issue by phra** [mozilla-neutrino/neutrino-dev#158]
hi,

as i see, there is no typescript preset that can be used in frontend or backend development. it would be nice to have that one in order to speed up kickstarting typescript projects.

**Comment by eliperelman** [comment]
I found this one on npm, is this sufficient?

https://www.npmjs.com/package/neutrino-preset-typescript

**Comment by phra** [comment]
@eliperelman i've tried it, it thows a validation error on the webpack config.

**Comment by eliperelman** [comment]
Are you using any custom configuration?

**Comment by phra** [comment]
nope.

**Comment by eliperelman** [comment]
Ah ok, that sounds like a bug in that preset. Would you mind filing a bug with it to get that resolved?

**Comment by eliperelman** [comment]
Closing, as there already exists a Typescript preset, and we won't be creating a new one in the core.

**Comment by FDiskas** [comment]
"neutrino-preset-typescript" Impossible to run that on neutrino v6
