### ISSUE TITLE
Expose eslint bin from eslint middleware

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#162]
It seems reasonable that someone wanting to use the eslint middleware should also be able to run eslint against an eslintrc file. Right now yarn doesn't re-expose the eslint bin, so we can probably manually expose it.

Another option would be to find a way for the lint middleware to augment the CLI with its own command that proxies to the eslint bin. This is probably not a reasonable option, though.

**Comment by barraponto** [comment]
When that is the case, I just `yarn add eslint` or `yarn add stylelint` in my projects.
Neutrino does its thing, eslint/stylelint do theirs.

**Comment by edmorley** [comment]
The problem with that is then you can have different versions of eslint used by each, which in our case resulted in an `eslint` reporting no errors, but the Neutrino build failing due to lint errors.

**Comment by barraponto** [comment]
I guess we could make `eslint` a peer dependency of `neutrino-eslint-middleware`.

**Comment by eliperelman** [comment]
No longer a serious issue with #236.
