### ISSUE TITLE
Emit run events

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#166]
If you want to execute some generic code prior to a build, you would need to listen for `pretest`, `prestart`, and `prebuild`. If we can create emit `prerun` and `run` events, there wouldn't need to be multiple bindings for generic tasks.

**Comment by helfi92** [comment]
@eliperelman If you want to execute code prior to a build, can you please elaborate why `prebuild` wouldn't be a good prospect. Also, where in the codebase are the list of listeners created. Thanks!

**Comment by eliperelman** [comment]
`prebuild` would **only** run when executing `neutrino build` or the build API. If you want to execute something no matter what command is run, we need a generic event.

Here's where the specific events are currently run:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/src/index.js#L17
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/src/index.js#L22

**Comment by helfi92** [comment]
Tackled in #222.
