### ISSUE TITLE
Alternative output without deleting other files

### ISSUE THREAD

**Issue by kuehn-sba** [mozilla-neutrino/neutrino-dev#1695]
### Bug or issue?
issue

Please try to answer the following questions:

- What version of Neutrino are you using?
9.5.0

- Are you trying to use any presets? If so, which ones, and what versions?
no

- Are you using the Yarn client or the npm client? What version?
npm 6.14.12

- What version of Node.js are you using?
v14.16.1

- What operating system are you using?
MacOS BigSur

- What did you do?
I would like to specify an alternative folder for the build and tried the options.output option with a path to public www folder

- What did you expect to happen?
the files are build, but the files should be created without deleting all other files in this path before!

- What actually happened, contrary to your expectations?
the files are build there, but all other necessary files are deleted there. 

### Feature request or enhancement?
It's more a (bug)fix!

Please describe your request in detail. Use the following questions as guidance:

- What is the goal of the change?
usability, flexiblity...

- What are the pros and cons of the change?
usability, flexiblity...

- Could this dramatically improve the experience of our users?
of course.

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
