### ISSUE TITLE
fullScreen make the app crash on armhf

### ISSUE THREAD

**Issue by rdcdt1** [mozilla-neutrino/neutrino-dev#1705]
hi,
firstly thx for the great work with neutrino.

i got an issue that appear only armhf not on windows ( i didn't try the other os :{ ).
the issue is when i put "fullScreen": true it make the app crash.
i try to different projet and template it's always crashing.
the error display in terminal is : 
"Gdk-Message: 14:40:42.309: Error 71 (Protocol error) dispatching to Wayland display."
i m on linux poky made by yocto with the desktop wayland and node v12.22.2

**Comment by edmorley** [comment]
Closing since unfortunately this project is no longer maintained. See:
https://github.com/neutrinojs/neutrino/issues/1707
https://github.com/neutrinojs/webpack-chain/issues/358
