### ISSUE TITLE
FR: Support multiple entry points through neutrino.options.entry

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#174]
Would be great if you could specify an obj here for multiple named entry points:

```
entry: {
  head: ['./js/head.js'],
  tail: ['./js/tail.js'],
}
```

**Comment by constgen** [comment]
Is it really necessary? In this situation the strong convention is more important than the absolute flexibility. Your case can be resolved by one of two variants:
*index.js*
```
import './js/head.js'
import './js/tail.js'
```
*index.js*
```
import('./js/head.js')
import('./js/tail.js')
```

**Comment by timkelty** [comment]
But your examples would just result in 1 bundle, right?...the point is I want 2 separate bundles `head` and `tail`.

The specific use-case is having a separate bundle for things you might want loaded in the `<head>` of you doc, (e.g. modernizr).

**Comment by constgen** [comment]
Ok. Lets try any way this one.
```
import('./js/head.js')
import('./js/tail.js')
```
Dynamic imports are always build separately. But honestly I have never tied to load them directly with `<script>` tag. And yes, they will have number counters instead of names.

**Comment by eliperelman** [comment]
Optimizing for the multi-page scenario is tougher, as it involves a number of moving pieces, like tim mentioned. Maybe this is something we can address for v6 and flesh out. Unfortunately right now I don't have a better solution than manually configuring that.

**Comment by timkelty** [comment]
@constgen Ah - I honestly didn't know about code splitting w/ dynamic `import()` in webpack! Will give that a try.

@eliperelman what does this subsequent reference to `.entry('index')` do here? Is it only enabling `source-map` for that entry point specifically?

**Comment by eliperelman** [comment]
You're referring to this line?

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L154

The `devtool()` above it has nothing to do with the subsequent `entry` definition. We just set `devtool` to `source-map` during development, and also add webpack-dev-server stuff during development.

Technically those other entries would also need to be added to other entry points if doing multi-page.

**Comment by timkelty** [comment]
@eliperelman yeah sorry, forgot to link.

Oh I see, you're adding the dev server stuff to the index entry, duh.
Does this make sense then? https://github.com/mozilla-neutrino/neutrino-dev/pull/191

**Comment by timkelty** [comment]
So to sum up: I say close if you like, or consider it a low-priority.

**Comment by eliperelman** [comment]
Closing for now as this falls under the realm of multiple entries which nothing is well-suited towards handling. I think it's OK from an advanced usage scenario, and would be happy to review a PR which makes this easier.

Will gladly re-open if someone would like to attempt this.

**Comment by trusktr** [comment]
Isn't the the entry option reachable from webpack-chainable API? Then it is possible to make some new preset using it.

**Comment by timkelty** [comment]
@trusktr that's correct.

When this issue was created, the problem was that other neutrino presets/middlewares sometime _expected_ only one webpack entry, `index`. Example: https://github.com/mozilla-neutrino/neutrino-dev/blob/d7688dc674af187011c114f42f5837f0ce2b880b/packages/neutrino-preset-web/index.js#L152-L156

However, it looks like maybe that was the only example, and the reference to `index` doesn't exist in the current version: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L150-L153, so maybe it isn't an issue any more.
