### ISSUE TITLE
[Issue] Pushstate webpack dev server public path

### ISSUE THREAD

**Issue by rj254** [mozilla-neutrino/neutrino-dev#175]
https://github.com/ReactTraining/react-router/issues/676#issuecomment-73963306

There should probably be an option to set publicPath on the devServer so that `react-router` and other libraries that rely on it can work out of the box.

**Comment by eliperelman** [comment]
@rj254 it seems like the solution is to just set the `devServer.publicPath` to `config.output.publicPath`. Does that sound right?

**Comment by rj254** [comment]
I believe so, locally I had to set both the output path to '/' and the devServer.publicPath to '/' in order to get this to work. 

More (relevant) information can be found here: https://github.com/react-boilerplate/react-boilerplate/issues/113

**Comment by eliperelman** [comment]
Cool, I'll upgrade webpack-chain, then the web middleware accordingly.

**Comment by eliperelman** [comment]
Setting the devServer.publicPath to the same value ends up with the public path being `./`, which broke things. Any idea why that is?

**Comment by eliperelman** [comment]
>  Make sure publicPath always starts and ends with a forward slash.

**Comment by rj254** [comment]
I believe devServer.publicPath has a set of rules including that the path should start and end with / . It turns out the default is also just "/". What really should happen is that the output public path should be specified as "/" not "./" when using the HTML webpack plugin.

**Comment by eliperelman** [comment]
@rj254 would you mind testing out https://github.com/mozilla-neutrino/neutrino-dev/pull/179 to see if it fulfills all the use cases you describe?

**Comment by rj254** [comment]
Sure

**Comment by rj254** [comment]
Unfortunately, the changes in #179 did not fix the issue. There is no need to set publicPath to '/' as it is [defaulted](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-) to '/'. The webpack docs additionally recommend the following:
` It is recommended that devServer.publicPath is the same as output.publicPath.`
output.publicPath should not be configured to `./` and should instead be configured to `/`

**Comment by constgen** [comment]
I think in dev run `publicPath` should always be overridden to "/" and in prod run to stay the same as consumer defined.

**Comment by eliperelman** [comment]
So, we can't set `devServer.publicPath` to `./`, which is what `output.publicPath` is set to. Is there anything that should be done here, or are these changes that should be made in userland if necessary?

**Comment by constgen** [comment]
Please don't set `output.publicPath` to `/` during the build. It breaks possibility to doubleclick the **index.html** to run the application from the local file system. Keep it `./` (or what consumer set) when `neutrino build` and `/` when `neutrino start` and probably `neutrino test`

**Comment by eliperelman** [comment]
@constgen yep, this is about what the best value to set `devServer.publicPath` is.

**Comment by constgen** [comment]
I believe this is done and can be closed. We explicitly set `publicPath: '/'` when start a Dev Server and keep untouched `publicPapth` when build. So the consumer can configure it by itself.
