### ISSUE TITLE
v5.5 webpack dev server is broken

### ISSUE THREAD

**Issue by aborsu** [mozilla-neutrino/neutrino-dev#178]
Fresh install using neutrino-preset-react v5.5.0

When running neutrino start, compilation succeeds but the server displays the following error. `Cannot GET /`

Rolling back to 5.4.0 fixes the issue.

**Comment by aborsu** [comment]
I have the issue both using `neutrino-preset-react` and `neutrino-preset-web`.
To reproduce create a brand new project following the neutrino doc and launch `yarn start`
The dev server starts but responds to all connections with 
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /</pre>
</body>
</html>
```
Running neutrino build works fine.
Switching back to 5.4.0 solves the issue.

I'm running macOS Sierra 10.12.4 and node v7.8.0

**Comment by eliperelman** [comment]
@aborsu I just pushed a patch of 5.5.1, can you test if that fixes it?

**Comment by eliperelman** [comment]
So sorry you had to experience this.
