### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by jaridmargolin** [mozilla-neutrino/neutrino-dev#182]
Keeping dependencies up to date and operating as expected can be extremely time consuming if done manually. It would be great to get something like Greenkeeper wired up. Unfortunately it does not appear to support the "monorepo" style repositories that contain nested package.json files.

Progress could be tracked here: https://github.com/greenkeeperio/greenkeeper/issues/139

**Comment by edmorley** [comment]
In addition to monorepo support, they'd also need to support updating yarn.lock (greenkeeperio/greenkeeper#314).

**Comment by destroyerofbuilds** [comment]
Temporarily, while Greenkeeper is still adding enhancements, you may want to consider using [renovate](https://keylocation.sg/our-tech/renovate).

`renovate` has [support for monorepos], and [yarn](https://github.com/singapore/renovate/#why).

**Comment by eliperelman** [comment]
Renovate has since switched to an integrated github app model, which works pretty well. I've added it to neutrino-dev, so I think we can consider this done now.
