### ISSUE TITLE
Ignore CSS during copying

### ISSUE THREAD

**Issue by rodmoreno** [mozilla-neutrino/neutrino-dev#183]
What version of Neutrino are you using?
**Neutrino v5.5.1**

Are you trying to use any presets? If so, which ones, and what versions?
**neutrino-preset-react v5.5.1**
**neutrino-middleware-postcss v2.0.2**

Are you using the Yarn client or the npm client? What version?
**Yarn 0.23.2**

What version of Node.js are you using?
**Node v7.9.0**

What operating system are you using?
**macOS sierra 10.12.4**

What did you do?
I use the follow neutrino's configuration from package.json
```json
  "neutrino": {
    "options": {
      "copy": {
        "ignore": ["*.css"]
      }
    }
  }
```

What did you expect to happen?
**No CSS files at build process**

What actually happened, contrary to your expectations?
**CSS files copied at build process**

**Comment by constgen** [comment]
As for me "copy" plugin should be disabled at all for the `neutrino-preset-react`

**Comment by eliperelman** [comment]
There aren't any Neutrino-defined options specific to overriding the Copy plugin, and doing this from package.json gets a little unwieldy:

```json
"neutrino": {
  "config": {
    "plugin": {
      "copy": {
        "args": [{}, { "ignore": ["*.css"] }]
      }
    }
  }
}
```

It would would be easier to use an [override middleware file](https://neutrino.js.org/customization/advanced.html) and do it from there:

```js
module.exports = neutrino => neutrino.config
  .plugin('copy')
  .tap(args => {
    args[1].ignore = ['*.css'];
    return args;
  });
```

**Comment by rodmoreno** [comment]
@eliperelman This makes sense to me. However it only worked when I compile the project through the command: `yarn build` if I just want to start the application in development mode through the command: `yarn start` fails.

Is there a way to condition such behavior when it is a build to when you just want to start?

**Comment by eliperelman** [comment]
You're totally right; the copy plugin only exists during building, which is the `production` environment:

```js
module.exports = neutrino => neutrino.config
  .when(process.env.NODE_ENV === 'production', config => config
    .plugin('copy')
    .tap(args => {
      args[1].ignore = ['*.css'];
      return args;
    }));
```

**Comment by kirikintha** [comment]
I am trying to do the same, with .scss files. This was a very timely post! Interesting thing about the code above, I was getting some unexpected output :

With the above code I was not expecting to see app/*.js being emitted:

```
                   app/app.component.js  352 bytes          [emitted]
  vendor.b78bc260f5e0cb61deff.bundle.js     174 kB       0  [emitted]  vendor
polyfill.34b6bccbb3f3f02fe0b8.bundle.js     107 kB       2  [emitted]  polyfill
                              index.css     147 kB       1  [emitted]  index
                            favicon.ico    15.1 kB          [emitted]
                             index.html  997 bytes          [emitted]
   index.713ba1b82c9374daf884.bundle.js    3.86 kB       1  [emitted]  index
                 app/app.component.scss  189 bytes          [emitted]
                               index.js  443 bytes          [emitted]

```
I changed the code to:

```
module.exports = neutrino => neutrino.config
  .when(process.env.NODE_ENV === 'production', config => config
    .plugin('copy')
    .tap(args => {
      args[1].ignore = ['*.css', '*.scss', '*.js'];
      return args;
    }));
```

And now my bundle is outputting as expected:

```
  vendor.b78bc260f5e0cb61deff.bundle.js     174 kB       0  [emitted]  vendor
   index.713ba1b82c9374daf884.bundle.js    3.86 kB       1  [emitted]  index
polyfill.34b6bccbb3f3f02fe0b8.bundle.js     107 kB       2  [emitted]  polyfill
                              index.css     147 kB       1  [emitted]  index
                             index.html  997 bytes          [emitted]
```

**Comment by eliperelman** [comment]
Ah good catch. The reason is that the web preset currently has the ignore option set to:

```js
ignore: ['*.js*']
```

In my previous comment, I changed it to `*.css` which overwrote the value, when I should have merged them:

```js
module.exports = neutrino => neutrino.config
  .when(process.env.NODE_ENV === 'production', config => config
    .plugin('copy')
    .tap(args => {
      args[1].ignore.push('*.css');
      return args;
    }));
```

Anyway, sounds like we have a solution. Please re-open if this doesn't work as expected. Thanks!
