### ISSUE TITLE
Allow environment-specific configuration overrides

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#185]
Using the package.json overrides, all configuration is added to every environment. If you want to override something that only exists in a certain environment, this will blow up. We should support making overrides on an environment or command-specific basis.

Environment-specific:

```js
{
  "neutrino": {
    "env": {
      "production": {
        "config": {
          // e.g. edit minify plugin options
        }
      }
    }
  }
}
```

Command-specific:

```js
{
  "neutrino": {
    "command": {
      "build": {
        "config": {
          // e.g. edit minify plugin options
        }
      }
    }
  }
}
```

**Comment by helfi92** [comment]
Resolved in #230
