### ISSUE TITLE
Change the default entry file from 'index.js' to 'index'

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/neutrino-dev#188]
The default file in the `index` entry is `index.js`. We should rename the file just to `index`. So Webpack will aromatically resolve the extension. This is useful for different types of projects. For example TypeScript projects (with necessary middlewares) will start from `index.ts`. Other project types are also possible. 
In general this should simplify creation of middlewares and presets for developers.

**Comment by eliperelman** [comment]
I think this makes sense, good catch.
