### ISSUE TITLE
Avoid needing to use NODE_ENV=development when running standalone eslint

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#192]
As part of mozilla/treeherder#2309, the package.json script entry `lint` was modified to prefix the eslint command with `NODE_ENV=development`, so that `isNotDev` works properly in `neutrino-middleware-eslint`:
https://github.com/mozilla-neutrino/neutrino-dev/blob/d009882e6d2dbbefe5c450472e689817dbc753af/packages/neutrino-middleware-eslint/index.js#L8

In comparison, the neutrino commands don't need such a prefix, since the Neutrino CLI wrapper sets an appropriate value using `getNodeEnv()` - defaulting to `development` if the command is not known:
https://github.com/mozilla-neutrino/neutrino-dev/blob/ebf7879ca67c1deca22e85991adf52da5db25a32/packages/neutrino/src/index.js#L10
https://github.com/mozilla-neutrino/neutrino-dev/blob/ebf7879ca67c1deca22e85991adf52da5db25a32/packages/neutrino/src/utils.js#L17-L22

However `getNodeEnv()` doesn't help the standalone eslint case, since that uses `.eslintrc.js` which accesses the Neutrino API directly, if created following the example in the docs:
https://neutrino.js.org/middleware/neutrino-middleware-eslint/#eslintrc-config

It would be great to avoid having to set `NODE_ENV=development` since cross-platform environment variables are annoying, and it's more boilerplate to type if calling eslint outside of yarn run.

I think this could be solved by either:
1) Updating the `.eslintrc.js` example in the docs to add a fallback if `process.env.NODE_ENV` is not defined.
2) Update `isNotDev` such that it treats `process.env.NODE_ENV` the same as if it were set to `development`.

@eliperelman, which do you feel is the best approach?

**Comment by eliperelman** [comment]
I think approach 2 would be OK. I'd also be inclined to drive these settings from an option rather than from the environment, since this **is** middleware. Then the consumer (e.g. Web preset, etc.) can pass an option based on the environment.

**Comment by edmorley** [comment]
Fixed by #225. Many thanks!
