### ISSUE TITLE
doc improvements

### ISSUE THREAD

**Issue by SeeThruHead** [mozilla-neutrino/neutrino-dev#193]
I cannot for the life of me figure out how to extend the configuration for the 'env' middleware

> Customization
> 
> neutrino-middleware-env creates some conventions to make overriding the configuration easier once you are ready to make changes.
> 
> Plugins
> 
> The following is a list of plugins and their identifiers which can be overridden:
> 
> env: Inject environment variables into source code at process.env.

is this `neutrino.plugins.env` or `neutrino.options.plugins.env` or ....
there's no indication of under which key extending middleware goes under in package.json

I believe there should be at least one example of how to extend via package.json as well as a preset for every middleware, preset, and plugin.

I could help flush these out if I were able to figure it out myself

thanks.

**Comment by eliperelman** [comment]
Plugins are kinda difficult to configure from package.json, but there is a structure you can follow from webpack-chain:

https://github.com/mozilla-neutrino/webpack-chain#merging-config

So to merge args for plugins, like env:

```json
{
  "neutrino": {
    "config": {
      "plugin": {
        "env": {
          "args": ['whatever env args']
        }
      }
    }
  }
}
```

Does that help?

**Comment by SeeThruHead** [comment]
I'm using the advanced config inside  custom preset. I've tried multiple tactics to remove copy load after applying the react preset
`neutrino.config.plugin('copy', args => []);`
`neutrino.config.plugin('copy').use(() => {}, []);`
`neutrino.config.plugin('copy').use(null)`
`neutrino.config.plugin.copy = null;`
`neutrino.config.plugin.delete('copy');`

none seem to manage to remove the copy plugin.

**Comment by eliperelman** [comment]
You can delete plugins by deleting from their backing store, at `.plugins`:

```js
neutrino.config.plugins.delete('copy');
```
