### ISSUE TITLE
Consider dropping babel-polyfill from being included by default

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#198]
Removing babel-polyfill is harder than adding it, and having to manage application-specific dependencies is something we really need to avoid because of the issues it causes with maintaining versions, etc. I think we should consider removing the polyfill chunk and entry point, and revert back to having applications include it if they need it.

**Comment by jaridmargolin** [comment]
Hmmmm. I like the idea that it simplifies getting up and running with the web preset in an intelligent manor. At a minimum, it could be pulled out into middleware, and possibly configured via an option in the web preset?

**Comment by constgen** [comment]
Are we talking about the web preset only?

**Comment by eliperelman** [comment]
I think the Web preset is the only one that defines it, so yes.

**Comment by barraponto** [comment]
I think we should document it then, specially how to add it back in a custom preset (advanced configuration).

**Comment by constgen** [comment]
I am going to extract it to a separate middleware. This will resolve a lot of questions how to bring it back. 

The question is: should this middleware be in the core packages?

**Comment by eliperelman** [comment]
Coming back full circle here, let's either thumbs up or thumbs down this issue:

👍 **if you want to remove the polyfill from being included by default**
👎 **if you want to keep the polyfill included by default, and document how to remove**

@mozilla-neutrino/core-contributors if I could get a vote, that would really help.

**Comment by barraponto** [comment]
and that's how I became aware of _being part_ of the core-contributors team...

**Comment by constgen** [comment]
But we can redesign it to be a separate middleware any way, right?

**Comment by constgen** [comment]
My vote depends on wether it will stay in the core package or not

**Comment by eliperelman** [comment]
In adding options to configure middleware, I just added an option for:

```js
neutrino.use(web, {
  polyfills: { babel: false }
});
```

So this would easily shut off everything that uses babel-polyfill. I also added a flag for fast-async. So I think that makes this issue pointless.

**Comment by eliperelman** [comment]
Closing as wontfix. Easily disabled if need be now. :)
