### ISSUE TITLE
How hard to modify presets to use a different project layout

### ISSUE THREAD

**Issue by curioussavage** [mozilla-neutrino/neutrino-dev#203]
Can someone tell me roughly how hard it would be to modify the presets so I can store unit tests in the same directory as their JS files.

**Comment by eliperelman** [comment]
Neutrino uses the `tests` option to select the directory where test files are stored:

https://neutrino.js.org/api/#optionstests

If you want this to be the same as the source directory, you can override in package.json:

```json
{
  "neutrino": {
    "options": {
      "tests": "src"
    }
  }
}
```

Or in more dynamically in an override file:

```js
module.exports = neutrino => {
  neutrino.options.tests = neutrino.options.source;
};
```

Each of the test presets that Neutrino provides looks for test files with a special extension to differentiate them from source files. For example, the Jest preset looks for `.js` or `.jsx` files ending in: `_test`, `_spec`, `.test`, or `.spec`. The Karma preset looks for `*_test.js` files. The Mocha probably isn't as friendly out of the gate as it will burn though a directory recursively, which may mean source files getting included.

Does that answer your question?

**Comment by eliperelman** [comment]
Addressed in previous comment, if this was insufficient, please feel free to re-open. Thanks!
