### ISSUE TITLE
neutrino-middleware-html-loader should use html-loader instead of file-loader

### ISSUE THREAD

**Issue by akkie** [mozilla-neutrino/neutrino-dev#206]
The [neutrino-middleware-html-loader](https://github.com/mozilla-neutrino/neutrino-dev/blob/957645f820c5262373096c65ba1cd530b26101eb/packages/neutrino-middleware-html-loader/index.js) uses the [file-loader](https://github.com/webpack-contrib/file-loader) instead of the [html-loader](https://github.com/webpack-contrib/html-loader).

This has the disadvantage that HTML files will not be imported. Instead the import returns only the filename to the import. So no error will be shown that HTML files cannot be imported. Instead the code fails somewhere where an HTML string is expected.

This is related to: https://mozilla-neutrino.slack.com/archives/C21E72PSN/p1495015489979725

**Comment by eliperelman** [comment]
Agreed, I no longer see any purpose of using file-loader instead of html-loader for `.html` files.

**Comment by eliperelman** [comment]
Unless we determine this to be a bug, this would probably be a breaking change.

**Comment by eliperelman** [comment]
Resolved in #219.
