### ISSUE TITLE
New modules are not picked up, requiring server restart

### ISSUE THREAD

**Issue by tj** [mozilla-neutrino/neutrino-dev#207]
Been a while since I've used webpack and friends, but is it normal to require a restart after adding a module in ./src ? I don't remember that being an issue in the past but my memory is foggy there.

It seems like files are fine (`./src/lib/*.js` for example), however new dirs are not.

Thanks again for the great project!

**Comment by eliperelman** [comment]
@tj are you using hot module replacement within your entry/main index.js file? e.g.

```js
// index.js
if (module.hot) {
  module.hot.accept();
}
```

**Comment by tj** [comment]
hmm strange I tried again and it's fine, sorry for the noise! Not sure what I did

**Comment by eliperelman** [comment]
No worries, thanks for the report!
