### ISSUE TITLE
Feature request: Better debugging capabilities for node presets

### ISSUE THREAD

**Issue by kriswep** [mozilla-neutrino/neutrino-dev#208]
I was wondering how would you go about debugging `neutrino-node` apps? 

What I'm hoping for is a possibility to be able to start the node server with the fairly new `--inspect` flag. That would allow for a great debugging experiences, as outlined by [Paul Irish](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27). 
However I was not able to set that up using your node preset.

It should be possible to implement that in a fairly straightforward way, since the [start-server-webpack-plugin](https://github.com/ericclemmons/start-server-webpack-plugin), which you use in `start-server` middleware, allows you to do that with an additional property `nodeArgs: ['--inspect']`.

I'm not sure about the best way to toggle debugging behaviour, since you use the `-- inspect` flag to print the webpack conf.

If there is another way to start the underlying node server in debugging mode, that could be an opportunity to improve the docs.

**Comment by eliperelman** [comment]
This seems to be pretty easy to implement, with the issue being where exactly to expose this functionality since it's only useful to the Node preset.

**Comment by eliperelman** [comment]
Maybe we could add a `--debug` flag which maps to `neutrino.options.debug = true`, then any middleware can choose to take any action they wish based on the presence of the flag.

**Comment by kriswep** [comment]
Sounds great, will send a PR the next days then.
