### ISSUE TITLE
Consider adding improvements to speedup build times

### ISSUE THREAD

**Issue by akkie** [mozilla-neutrino/neutrino-dev#210]
There exists some tweaks to improve the build time and also the testing time with babel and webpack. Maybe this issue can serve as a documentation for others searching for improvements regarding slow build times. Maybe some of the improvements find a way into neutrino or the neutrino documentation.

**1. Enable `cacheDirectory` for `babel-loader`:**

Please see: https://github.com/babel/babel-loader#options

Enabling the `cacheDirectory` option can increase the babel build time up to 2x.

**2. Use HappyPack**

> HappyPack makes webpack builds faster by allowing you to transform multiple files in parallel.
https://github.com/amireh/happypack

**3. Use Webpack DLL Plugin**

> Webpack's Dll and DllReference plugins are a way to split a large JavaScript project into multiple bundles which can be compiled independently. They can be used to optimize build times (both full and incremental) and improve caching for users by putting code which changes infrequently into separate "library" bundles. The term 'Dll' is short for Dynamically Linked Library which is a feature for native Windows applications that solves the same problem.

https://robertknight.github.io/posts/webpack-dll-plugins/
https://webpack.js.org/plugins/dll-plugin/

Maybe there are other tweaks. So it would be cool if they could be added here.

**Comment by eliperelman** [comment]
I think option 1 is a relatively simple change, and we should go for it.

While HappyPack is nice, it would probably mean a fundamental shift in the way Neutrino works. I'm happy to review a PR that makes this change, but I personally can't put any effort towards that.

For option 3, I'm not sure how we could utilize DllPlugin in a manner that would be application-agnostic. I'd be happy to look over a PR for option 3 if it's possible.

---

For now, I'm going to see about the `cacheDirectory`.

**Comment by eliperelman** [comment]
Resolved with `cacheDirectory: true` in #221.

**Comment by constgen** [comment]
The task is closed. But should we extract next points to separate issues for investigation?
2. Use HappyPack
3. Use Webpack DLL Plugin
