### ISSUE TITLE
[neutrino-preset-web]: Allow to configure contentBase

### ISSUE THREAD

**Issue by leesiongchan** [mozilla-neutrino/neutrino-dev#214]
Are there any reasons why use `source` in `contentBase` and not being configurable instead? In my case I want it to serve my static files.

[neutrino-preset-web#L149](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L149)

**Comment by eliperelman** [comment]
This value is configurable. You can either change the `source` value:

```js
// package.json
{
  "neutrino": {
    "options": {
      "source": "static"
    }
  }
}

// advanced override file
module.exports = neutrino => {
  neutrino.options.source = 'static';
};
```

Or you can override the `contentBase`:

```js
module.exports = neutrino => {
  neutrino.config.devServer.contentBase(path.join(__dirname, 'static'));
};
```

**Comment by leesiongchan** [comment]
I believe `source` value is meant to be pointed to `src` (source codes) but not `static` (static files)?

**Comment by eliperelman** [comment]
You can override any of these values to serve your particular use case, so while Neutrino has pre-configured values for the middleware, feel free to change them how you need.

**Comment by constgen** [comment]
I am interested with this problem. @leesiongchan can you describe in more details what is your project file structure and what kind of application you run?

**Comment by leesiongchan** [comment]
- src (sources codes)
- public (static files)
  - images
  - ...other static files

So in my project I suppose I should configure my configuration like this
```json
{
  "neutrino": {
    "config": {
      "devServer": {
        "contentBase": "public"
      },
    },
    "options": {
      "source": "src"
    }
  }
}
```

Of course I could override `contentBase` but just wondering why is [contentBase](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L149) uses `source` directly instead of allowing us to configure from `package.json`.

**Comment by constgen** [comment]
Is `public` not part of source code? In my projects I usually use`src/data` or `src/static` and correctly setup copying to build

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/neutrino-dev/issues/4

**Comment by eliperelman** [comment]
> just wondering why is contentBase uses source directly instead of allowing us to configure from package.json.

Like I said in my [previous comment](https://github.com/mozilla-neutrino/neutrino-dev/issues/214#issuecomment-303375250) these are configurable from package.json and an override file. In fact, you can also use package.json config:

```json
{
  "neutrino": {
    "config": {
      "devServer": {
        "contentBase": "public"
      }
    }
  }
}
```

If any of these options do not work, please feel free to re-open. Thanks!
