### ISSUE TITLE
Update 'eslint-plugin-react' to v7

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/neutrino-dev#216]
Need to investigate what braking changes and new features the latest version of `eslint-plugin-react` provides and use them in the React preset.

**Comment by eliperelman** [comment]
Agreed, we need to walk through all packages and upgrade any breaking changes we can.

**Comment by eliperelman** [comment]
I'll be removing this from the React preset as it shouldn't be enforcing a style on anyone. If they want to use the React settings, they can merge it with some other ESLint middleware.
