### ISSUE TITLE
Rely on browserslist instead of passing neutrino.options.compile.targets directly

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#229]
**The goal:**

Be able to have a [Browserslist](https://github.com/ai/browserslist) config (e.g. `.browserslistrc`) and have it be used by anything relevant (e.g. [compile-loader/babel-preset-env](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-web/index.js#L78), eslint-plugin-compat, postcss/autoprefixer)

Seems like we could drop the `neutrino.options.compile.targets` option entirely.

**Comment by eliperelman** [comment]
My goal is to have `.neutrinorc.js` **include** the compile targets, like how we have now with `neutrino.options.compile.targets`. While a `.browserlistrc` may have wider support among tools, it forces additional boilerplate on projects and is specific to browser definitions, so it wouldn't be useful for defining Node.js targets.

We should be trying to invoke these other tools programmatically such that we can have a single configuration source of truth: `.neutrinorc.js`.

**Comment by timkelty** [comment]
Related - if we go the route we've been discssuing in https://github.com/mozilla-neutrino/neutrino-dev/issues/199, `neutrino.options.compile` would become part of options passed to `neutrino-preset-web` instead of an api level level option (`neutrino.options`)

**Comment by eliperelman** [comment]
With v6, we have been consolidating our sources of configuration down to 2 possibilities: middleware and command-line. The only middleware Neutrino will automatically try and require for you is `.neutrinorc.js`. All other middleware either comes from that file, or the command line. Each of those places can specify additional middleware.

To pull in configuration from somewhere else would complicate this further, and introduce a potentially slippery slope. For that reason, I think we should leave pulling in this data as an exercise for the user if they still want to keep this data in a separate file, e.g. require package.json and pass the values into the middleware options, or `readFileSync` on .browserlistrc, split the lines, clean out comments, and pass this into middleware.
