### ISSUE TITLE
`neutrino build` does nothing, with no output or errors

### ISSUE THREAD

**Issue by metamas** [mozilla-neutrino/neutrino-dev#241]
I'm running `node 6.11.0` and `npm 5.0.3`.

I've followed the docs to result in the following `package.json`:
```json
{
  "name": "neutrino-is-dope",
  "main": "index.js",
  "neutrino": {
    "use": [
      "neutrino-preset-airbnb-base",
      "neutrino-preset-react"
    ]
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build"
  },
  "dependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  },
  "devDependencies": {
    "neutrino": "^5.9.0",
    "neutrino-preset-airbnb-base": "^5.9.0",
    "neutrino-preset-react": "^5.9.0"
  }
}
```
With all packages installed, when I run the `npm build` command nothing appears to happen. There is no output, no apparent errors, and no built files in the `build/` directory. This behavior is not the same for `npm start` which builds the project and starts the dev server as expected.

However, I can run `node_modules/.bin/neutrino build` from my project root, and everything builds with output as expected. 

Am I missing something or is this a bug? If the latter, I'm happy to fix and do a PR — given some direction.

**Comment by eliperelman** [comment]
npm scripts work a little differently than yarn scripts, in that unless the npm script is well defined by the npm cli, it won't actually do anything. Said another way, the `build` script is not well defined by the npm CLI, so you have to use the `run` argument, unlike yarn. So while `yarn start` and `npm start` both work, with build it would be `yarn build` and `npm run build`.

Try `npm run build` and you should be good!

**Comment by metamas** [comment]
Oh no! Lol. I had known that `build` wasn't a defined script name in npm... at some point in the past. I guess this new yarn and/or npm world has crossed some wires. Thank you, and sorry about the oversight on my part.
