### ISSUE TITLE
Improve the speed of the Travis run

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#248]
Each sub-job within the Travis run takes 5-6 minutes:
https://travis-ci.org/mozilla-neutrino/neutrino-dev/builds/242170076

Of this, about:
* 6-12 seconds spent downloading the Travis cache archive from S3
* 60-70 seconds is spent extracting the travis cache ("Setting up build cache" section)
* 50 seconds spent calculating that the cache didn't need updating at the end of the run
* 10-15 seconds spent doing the root yarn install, even though node_modules was supposedly cached
* 60-80 seconds spent running yarn bootstrap, even though the sub-package's node_modules were supposedly cached
* 5 seconds running `yarn lint`
* 20 seconds running `yarn test`
* 3 seconds running code coverage

The Travis caching feature really doesn't seem to handle the tens (hundreds?) of thousands of files from the 20+ node_modules that well, so I've filed:
https://github.com/travis-ci/travis-ci/issues/7898

Until that is fixed, I wonder if the caching is adding more time than it is saving, particularly given that yarn is still doing work?

Caching just the yarn cache (`~/.cache/yarn`, which is already done via the `yarn: true` line) might be the best value-for-cache-extract-time of all?

**Comment by edmorley** [comment]
I've tested oao locally and with a clean checkout, the first bootstrap takes 125 seconds, and the second still takes 63 seconds, even though it had nothing to do. This explains why we're not seeing much advantage from caching the sub-package node_modules. I've filed: guigrpa/oao#42.

**Comment by eliperelman** [comment]
Yeah, I'm totally fine with removing the cache if we aren't seeing any speedup from it, which I guess is supposed to be the whole point of having the cache.

**Comment by edmorley** [comment]
It seems like oao is just quite slow at the moment - I've found some issues in a profile in guigrpa/oao#42.

I wonder if [lerna](https://github.com/lerna/lerna) might be better - it has 20 times as many stars on GitHub, much more activity/contributors and is used by the babel project.

Also, one generic suggestion I've seen for speeding up monorepo development/testing is to move as many of the `devDependencies` (not the `dependencies`) to the root `package.json` to avoid duplication?

**Comment by edmorley** [comment]
Oh and yarn may add support for something similiar to lerna/oao in the future too: yarnpkg/rfcs#60

**Comment by eliperelman** [comment]
I had evaluated and tried lerna and yerna prior to choosing oao. Lerna (at least when I evaluated it) did not support yarn, and yerna was just buggy.

I agree on the devDependencies, that makes total sense, although I don't think it will avoid peerDependency warnings, which isn't a big deal.

I've been waiting for the yarn workspaces for a while, I really hope it becomes reality soon.

**Comment by edmorley** [comment]
Lerna now supports yarn:
https://github.com/lerna/lerna#--npm-client-client

It also supports optional hoisting (which would require neutrino to do the right thing wrt dependency resolution, the tests fail locally currently):
https://github.com/lerna/lerna/blob/master/doc/hoist.md

Once the first bootstrap is run, `lerna bootstrap --npm-client=yarn --hoist` takes 0.6 seconds locally for me (compared to oao's 40+ seconds).

**Comment by eliperelman** [comment]
If you can, it would be great to have a PR to try this on (based off the v6-dev branch). How difficult do you think it would be to switch and try it?

One thing that concerns me is publishing, since right now I control building a dependency graph and doing the publishing in order:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/.scripts/publish

I see that lerna can do (at least in the RC releases) topological publishing, which hopefully would negate the need for the custom publish script.

**Comment by guigrpa** [comment]
There is an imminent release of oao that [improves build times](https://github.com/guigrpa/oao/issues/42) and adds flags to `oao bootstrap` as requested by @eliperelman [here](https://github.com/guigrpa/oao/issues/43). I hope to get it out tonight.

**Comment by edmorley** [comment]
Looking at the Travis timings on recent runs, the notable durations are now:
* 5-7 seconds spent downloading the Travis cache archive from S3
* 6-8 seconds is spent extracting the travis cache ("Setting up build cache" section)
* 5-9 seconds spent calculating that the cache didn't need updating at the end of the run
* 19-34 seconds spent doing the root `yarn install`
* 92-186 seconds spent running `yarn bootstrap`
* 4-8 seconds running `yarn lint`
* 34-69 seconds running `yarn test`

The reduced cache handling times compared to the OP are due to #253. There was also some overall end-to-end speedup due to switching to Trusty (#249).

The biggest remaining win would be to switch to yerna/yarn workspaces, since judging from the speedup seen locally, it would drastically reduce the 13-34 + 92-186 second package installation times.

Since the remaining work is covered by #251, I'll close this out for now.
