### ISSUE TITLE
Experiment with switching from oao to lerna

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#251]
oao is pretty slow (particularly in what should be no-op situations, see #248), so we may be able to speed up the CI end to end time (and improve local development UX) by switching to lerna.

For example, a no-op bootstrap takes 40 seconds with oao but only 0.6 seconds with lerna.

I have a WIP here:
https://github.com/mozilla-neutrino/neutrino-dev/compare/master...edmorley:lerna

...however `yarn test` currently fails with:
```
devbox ~/neutrino-dev $ yarn test
yarn test v0.24.6
$ nyc --reporter lcov ava packages/*/test
(node:6372) Warning: process.on(SIGPROF) is reserved while debugging
module.js:487
    throw err;
    ^

Error: Cannot find module 'neutrino'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/neutrino-dev/packages/neutrino-preset-node/test/node_test.js:1:5301)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/home/vagrant/neutrino-dev/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at extensions.(anonymous function) (/home/vagrant/neutrino-dev/node_modules/require-precompiled/index.js:13:11)
    at /home/vagrant/neutrino-dev/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.(anonymous function) (/home/vagrant/neutrino-dev/node_modules/ava/lib/process-adapter.js:105:4)
    at Object.<anonymous> (/home/vagrant/neutrino-dev/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/neutrino-dev/node_modules/ava/lib/test-worker.js:33:1)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/home/vagrant/neutrino-dev/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/vagrant/neutrino-dev/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/vagrant/neutrino-dev/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Function.runMain (/home/vagrant/.node-spawn-wrap-6372-6ccbe2e3007b/nodejs:40:10)
    at Object.<anonymous> (/home/vagrant/neutrino-dev/node_modules/nyc/bin/wrap.js:22:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/home/vagrant/.node-spawn-wrap-6372-6ccbe2e3007b/nodejs:140:8)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
module.js:487
    throw err;
    ^

...
```

(full log: https://emorley.pastebin.mozilla.org/9024478)

**Comment by eliperelman** [comment]
Looking at the error log, the problem seems to be that the presets tried requiring `neutrino` and couldn't find it. This tells me that lerna probably didn't symlink the peerDependency.

**Comment by edmorley** [comment]
Yarn 0.28 now has support for workspaces, which means part of the lerna functionality is now in yarn and it can perform even more hoisting optimisations. It also means there is only the need for a single root yarn.lock rather than one in each package. Lerna would still be used for assisting with publishing etc.

See:
https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by eliperelman** [comment]
I tried using workspaces in Neutrino, both standalone, with lerna, and with oao. They seemed to be completely broken with Neutrino, and I just think yarn's workspaces are still buggy.

**Comment by edmorley** [comment]
I've just tried {native yarn workspaces, traditional lerna, traditional lerna but with hoisting enabled, lerna using yarn workspaces} using nodejs 8.5.0, yarn 1.1.0 and lerna 2.2.0.

Out of those, everything apart from the hoisting one worked pretty well (apparently using lerna hoisting mode + yarn falls back to npm for certain things so is buggy: lerna/lerna#852).

The one thing I did have to change to get them to work, was adding the neutrino `peerDependency` as additionally as a `devDependency`, since apparently that's the recommended way to ensure it's installed. OAO's behaviour of automatically installing peer dependencies does not occur in {npm, yarn, lerna} by design (see lerna/lerna#691, npm/npm#11213 and https://docs.npmjs.com/files/package.json#peerdependencies).

What things were broken for you, so I can check I have definitely got it working properly? Also what version of yarn were you using? :-)

**Comment by edmorley** [comment]
It's worth noting as well that eslint checks for missing dependencies (I didn't realise it did this - pretty handy!) - eg:

```
× Running lint failed

.../neutrino-dev/packages/neutrino-preset-jest/src/index.js
  5:15  error  'deepmerge' should be listed in the project's dependencies. Run 'npm i -S deepmerge' to add it  import/no-extraneous-dependencies
```

...which mitigates my concern that any hoisting type solution (either traditional lerna with hoisting enabled, or yarn workspaces) could result in publishing a package that is missing dependencies from it's `package.json` if another package specified them.

As such, we can take full advantage of hoisting and avoiding the massive duplication in each package's node_modules.

**Comment by edmorley** [comment]
It looks like yarkpkg/yarn#4583 will fix a number of yarn workspaces issues, after which we can revisit.

**Comment by eliperelman** [comment]
Yeah, most of my problems may have just been with a bunch of Yarn bugs. Hopefully that releases soon.

**Comment by eliperelman** [comment]
Regarding Yarn version, I had tried 0.28 as well as 1.0.0 when it released.

**Comment by edmorley** [comment]
Yarn 1.2.0 is out which includes a couple of significant workspaces improvements. However I just went through the yarn issue tracker and there are still half a dozen other workspaces bugs that I could repro using 1.2.0, so perhaps worth waiting a little longer.

In the meantime we could always still update to newer yarn, once we update to the new oao update and see whether the error messages went away for you? (The errors I saw are now resolved)

**Comment by edmorley** [comment]
@eliperelman, I don't suppose you could outline some of the workflows you use oao for? Knowing what steps you take and the expected outcome (eg things like "when I do a release I want every package version number to be bumped, not just the changed packages") would help me test yarn workspaces/lerna for compatibility with them.

(Context: The latest neutrino release didn't update all the versions properly again - there must be a bug in oao or the `.scripts/publish` script - the sooner we can just move away the better IMO)

**Comment by eliperelman** [comment]
@edmorley here is what I use oao for:

### Linking packages together

This is normally done with `yarn bootstrap` or `yarn oao bootstrap`. This would be solvable by yarn workspaces.

### Checking outdated packages

I usually run in the root:

```bash
yarn oao outdated
```

Which walks through all sub-packages and tells me what packages are out of date. Analogous to just running `yarn outdated` inside a package that would use yarn workspaces.

### Dependency commands in packages

Things like upgrading the version of a package inside of a sub-package, e.g. `yarn deps:upgrade neutrino webpack`. Solvable by yarn workspaces, except I think their commands are still buggy. Last I checked, lerna didn't expose commands for these operations, but again, not necessary if yarn workspaces work properly.

### Resetting all versions when publishing

When I publish, my workflow is usually:

```bash
yarn changelog

# This next command is run via npm for some weird credential issue between yarn and npm
npm run release 7.1.4

git add .
git commit -m "..."
git tag -a v7.1.4 ... -m "v7.1.4"
git push upstream master
git push upstream master --tags
```

Inside the publish script is a call to exec the command `oao reset-all-versions`, which sets it to be whatever I pass for the version arg on the command line.

**Comment by eliperelman** [comment]
Was still having trouble publishing after being completely unable to move forward. I switched to using workspaces and lerna, and even though it still needs some configuration, I was at least able to push out v7.2.1.

I didn't mean to have it committed to master, but I was working in that branch and lerna had committed it, so unless we want to cherry pick the right changes, we can roll with it since it's just in development.

**Comment by eliperelman** [comment]
Going to close this since we accidentally already moved to lerna. 😆 

We can improve the dev experience by adding more yarn scripts if needed.

**Comment by edmorley** [comment]
Is the publish script still being used? If not we can remove that too. I wonder whether we should also switch to opening a PR for bumping a new version, so it can be reviewed/double-checked until we're confident in the new system?

**Comment by eliperelman** [comment]
Oops, forgot to delete that. Yeah, it can be removed.

Regarding reviewing, we will have to see if lerna can stage a publish without actually doing it. My concern is the dependency upgrades, like presets depending on middleware.
