### ISSUE TITLE
Use yarn install --frozen-lockfile

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#255]
In CI it's advantageous to use `yarn install --frozen-lockfile` rather than `yarn install`, since otherwise yarn will silently update `yarn.lock` when installing, hiding the fact that the PR may have caused it to drift out of sync with `package.json`.

I'd link to the yarn docs for this flag, except they don't exist (yarnpkg/website#378), thanks to yarnpkg/yarn#2891.

Instead, from `yarn install --help`:
```
--no-lockfile         don't read or generate a lockfile
--pure-lockfile       don't generate a lockfile
--frozen-lockfile     don't generate a lockfile and fail if an update is needed
```

**Comment by eliperelman** [comment]
Partially fixed in #256 but until oao supports bootstrapping with `--frozen-lockfile`, I'm afraid the packages are still at risk.

I've filed https://github.com/guigrpa/oao/issues/43 and hopefully it can be resolved there.

**Comment by eliperelman** [comment]
I tried updating our yarn.lock files and then putting `oao bootstrap --frozen-lockfile` in the repo, but for some reason travis was still picking up updates and failing. Will dig in more soonish.

**Comment by edmorley** [comment]
I say we wontfix this, since with yarn workspaces, yarn only gets invoked once so the leaf invocations no longer exist.

**Comment by edmorley** [comment]
Actually it looks like this already works using oao 0.10.3 and yarn 0.28.4:
https://travis-ci.org/edmorley/neutrino-dev/jobs/286084290

Example demonstrating the job turning red when it should do:
https://travis-ci.org/edmorley/neutrino-dev/jobs/286085987
