### ISSUE TITLE
add neutrino-preset-react-require to react preset

### ISSUE THREAD

**Issue by tj** [mozilla-neutrino/neutrino-dev#260]
Any interest in adding https://github.com/tj/neutrino-preset-react-require out of the box? Shouldn't do any harm having it there even if people ignore it, but then they can get rid of the "code smell" of importing React each time which is nice!

**Comment by barraponto** [comment]
Does it throw errors if the user actually adds `import React from 'react'`?
If it doesn't, it means it is optional -- and we could turn it on by default.
Right?

**Comment by eliperelman** [comment]
I'm also curious as to what happens when you need an export from it:

```js
import { PureComponent } from 'react';
```

Any ideas @tj?

**Comment by tj** [comment]
I believe it detects those cases, I haven't had issues yet requiring Component in some etc

**Comment by eliperelman** [comment]
OK, I think that's pretty cool! Would probably just need to also add some docs for it as well.

👍

**Comment by eliperelman** [comment]
@tj would you be willing to PR this? If not, I can pick it up in the next week or so.
