### ISSUE TITLE
Extract compile-loader merge functionality into separate package

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#262]
Maybe something like babel-merge, it's generic enough.

**Comment by gigafied** [comment]
Think I was just bit by this?

Trying to use preset-react, this is in my `.neutrinorc.js` file:

```  neutrino.use('neutrino-middleware-compile-loader', {
    babel: {
      plugins: [
        'babel-plugin-transform-decorators-legacy'
      ]
    }
  })
```

Anyway to workaround this for now?

**Comment by eliperelman** [comment]
What version of neutrino are you using? Can you share your package.json and .neutrinorc.js file?

**Comment by eliperelman** [comment]
If you are using the React preset already, there is no need to bring in the compile loader, just pass a babel object to the React preset:

```js
// .neutrinorc.js
module.exports = {
  use: [
    ['neutrino-preset-react', {
      babel: {
        plugins: ['babel-plugin-transform-decorators-legacy']
      }
    }]
  ]
};
```

Documented here: https://neutrino.js.org/presets/neutrino-preset-react/#preset-options

**Comment by eliperelman** [comment]
If that doesn't work, please feel free to re-open. Thank you for the issue!

**Comment by gigafied** [comment]
Thanks @eliperelman for the response.

That didn't actually work as the order of the plugins is important in this case. I ended up just creating my own preset to work around the issue
