### ISSUE TITLE
Upgrade to Webpack 3

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#267]
It's not out yet but when it is we need to jump on the train. This will be a breaking change most likely to v7.

**Comment by nikolay** [comment]
@eliperelman It is out now. People say it's mostly backward-compatible. Any chances to have v7 out soon?

**Comment by RomanovRoman** [comment]
It's not look as big deal... Have we enough tests?
> Migrating from webpack 2 to 3, should involve no effort beyond running the upgrade commands in your terminal.
[this proof is quoted from webpack blog](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b#17f8)

**Comment by eliperelman** [comment]
Shipped in Neutrino v7! 🎉
