### ISSUE TITLE
neutrino-preset-karma returning zero even when tests are failing

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#268]
Treeherder is using the neutrino-preset-karma preset to run tests, however neutrino test is returning zero even though some of the Karma tests failed. Example "green" Travis run on master:
https://travis-ci.org/mozilla/treeherder/jobs/243425766#L477

We have the package.json `test` script set to:
`neutrino test --presets ./neutrino-custom/test.js`

The custom test.js preset is here:
https://github.com/mozilla/treeherder/blob/d9045d01b1dd14a61e5f003649b3cb51fac40ba7/neutrino-custom/test.js

It makes use of neutrino-preset-karma v4.2.0, which going back through the git log (that tag is missing), was this:
https://github.com/mozilla-neutrino/neutrino-dev/blob/85ed67f035de81a861d49a74f97f6dbede61c004/packages/neutrino-preset-karma/src/index.js#L49-L51

Whilst we're running the old v4 Neutrino series, the Karma preset doesn't look to have changed much between then and master, so I'm wondering if it's broken on master too?

**Comment by eliperelman** [comment]
I think it's broken on master. Looking at the signature of the Karma Server:

http://karma-runner.github.io/1.0/dev/public-api.html

It returns a function with a status code. I believe we used to sniff that status code, but now we are resolving regardless. Should be easy enough to fix.

**Comment by eliperelman** [comment]
@edmorley I pushed out a hotfix for the Karma preset in the 4.x line. Can you try neutrino-preset-karma 4.2.1?

**Comment by edmorley** [comment]
Confirmed that works a treat :-)
https://travis-ci.org/mozilla/treeherder/jobs/244706840#L484

Thank you for pushing the hotfix!

**Comment by eliperelman** [comment]
🎉
