### ISSUE TITLE
Offline/PWA support

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#27]
Using https://github.com/NekR/offline-plugin this could be pretty straightforward, and a win for everyone.

**Comment by sotayamashita** [comment]
It also useful stuff. https://github.com/webpack/webpack-pwa

**Comment by eliperelman** [comment]
It would be *really nice* to have out-of-the-box offline and PWA build support, maybe a combination of sane defaults with some conventions. Let's plan this for v6, but we can push it back more if it's just too much right now.

cc: @addyosmani in case he has any nice links for some generic webpack configuration we can borrow for PWA stuffs.

**Comment by eliperelman** [comment]
Some good resources here as well: https://github.com/vuejs/pwa/tree/prototype/template

**Comment by barraponto** [comment]
I'd like this to be a preset, so web-preset users don't see any change until they opt-in to this.

**Comment by eliperelman** [comment]
Have a first draft landed in the v6-dev branch. We can iterate on it more in the future.

**Comment by constgen** [comment]
Currently we use Hot Module Replacement only in development mode. This is useful for development purposes. But I see some profit for enabling it in production in case we build a PWA. HMR is designed to work in production also to help with seamless deploy when changes are pushed to the client side without a page refresh
