### ISSUE TITLE
Live reload is triggered only every second time.

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/neutrino-dev#277]
When start project in a development mode with `neutrino start` not every file change triggers browser resources reload. CLI reports about changes and recompilation every time but reload happens only every second time. Expected that a browser will react to every file change and recompilation.
The issue can be reproduced on `neutrino-preset-web` and any on top of it.

**Comment by constgen** [comment]
Didn't find a solution, but have some investigation results. I tried to localize the problem and seems that it is somewhere in the Neutrino core, not middlewares, not `webpack-chain`. I have created a [test suite](https://www.dropbox.com/s/0iqjcrrc8xeqiod/web-test-hot-reload.zip?dl=0).
There are two ways to start:
#### Using Neutrino
```
npm start
```
#### Using a regular Webpack config
```
npm run start-webpack
```
They both use the same configuration chain.

You can observe these results:
- starting from Webpack works as expected. Every change in `index.js` reloads the browser window. 
- starting from Neutrino doesn't reload at all. 

The next thing is the most interesting. Open `webpack-middleware.js` and switch from `only-dev-server` to `dev-server`. Now the config is like in `neutrino-middlware-dev-server`. The results are
- starting from Webpack throws an error. It fails even with simple configuration without `webpack-chain`. I could reproduce this error even in clean Webpack setup, so this is not our fault. 
- starting from Neutrino is successful and window is reloaded only every second time the file is changed. These is how all presets work now.

Now I am asking for support. We need somebody who is an expert in Webpack or Neutrino core.

**Comment by constgen** [comment]
The issue is fixed. Need somebody to patch the version and publish a new release.

**Comment by eliperelman** [comment]
Released in 6.1.5 by #304.
