### ISSUE TITLE
Help with babel config

### ISSUE THREAD

**Issue by lielran** [mozilla-neutrino/neutrino-dev#286]
I would like to setup a custom config for mobx (https://mobx.js.org/best/decorators.html). 

I try this one: 
``` 
module.exports = {
  use: ['neutrino-preset-react',
    "neutrino-preset-jest",
    "neutrino-preset-airbnb-base",
    (neutrino) => neutrino.config.module
      .rule('compile')
      .use('standard')
      .loader(require('babel'), ({ options }) => {
        options.presets = [
          "es2015",
          "stage-1"
        ],
        options.plugins =  ["transform-decorators-legacy"]
      })

  ]
};
```
 but it didn't work(```Error: Cannot find module 'babel'```)

anyone can help with that?

**Comment by eliperelman** [comment]
@lielran your loader should probably be either `babel-loader` or `require.resolve('babel-loader')`.

**Comment by eliperelman** [comment]
Closing, please reopen if my recommendation is not working for you.

**Comment by lielran** [comment]
@eliperelman  - ``` require.resolve('babel-loader') ``` did help but now I'm facing other error that comes from the present-web.
Thanks for the help but I'm decided to drop the decorators of Mobx for now. too much complexity and not sure if it worth it in my case. 

but a geneal note on neutrino documentation that is that I coudn't find any docs about this simple babel config.
