### ISSUE TITLE
Add `findRelatedTests` CLI option to jest preset

### ISSUE THREAD

**Issue by okonet** [mozilla-neutrino/neutrino-dev#287]
It looks like Jest preset CLI options are missing `findRelatedTests` options that is useful with tools like [lint-staged](https://github.com/okonet/lint-staged)

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-preset-jest/src/index.js#L97

**Comment by eliperelman** [comment]
@okonet Thanks for the issue! I couldn't find much in the way of documentation of this, but it appears to want string paths. How do you suppose this option should work? If specified, should we set it to `neutrino.options.entry`?

```diff
  const cliOptions = {
    config: configFile,
    coverage: args.coverage,
    watch: args.watch,
+   findRelatedTests: neutrino.options.source
  };
```

**Comment by okonet** [comment]
It's suppose to get arguments from CLI. So in case with lint-staged, it will call `neutrino test --findRelatedTests ./path/to/file1.js ./path/to/file2.js ...`. Can this be accomplished?

**Comment by okonet** [comment]
Here is the related documentation: http://facebook.github.io/jest/docs/cli.html#findrelatedtests-spaceseparatedlistofsourcefiles

**Comment by eliperelman** [comment]
Yeah, that should be doable. I'll see if I can figure out a nice generic way to grab any extra CLI arguments from the Neutrino `args` and pass them on.

**Comment by okonet** [comment]
Any updates on this one? Do you need any help?

**Comment by okonet** [comment]
@eliperelman I think this issue can be expanded to any command. I tried to run `npm run lint -- --fix` but it won't get passed to `eslint` which is vey unfortunate IMO. Do you think we could expand the architecture to allow this?

**Comment by okonet** [comment]
@eliperelman should I open a separate issue in relation to lint and other tasks? https://github.com/mozilla-neutrino/neutrino-dev/issues/287#issuecomment-328820679

**Comment by eliperelman** [comment]
@okonet yes, go ahead! Right now flags aren't passed to eslint because we use ESLint CLIEngine, not the CLI itself.

**Comment by eliperelman** [comment]
@okonet although not sure why `--fix` isn't working:

https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino-middleware-eslint/index.js#L79
