### ISSUE TITLE
neutrino-middleware-env doesn't work when defined before neutrino-middleware-rpweb

### ISSUE THREAD

**Issue by wlach** [mozilla-neutrino/neutrino-dev#296]
Given this .neutrinorc.js:

```js
'use strict';

const envs = {
  SERVICE_DOMAIN: 'https://data-missioncontrol.dev.mozaws.net'
};
// Set environment variables to their default values if not defined
Object
  .keys(envs)
  .forEach(env => !(env in process.env) && (process.env[env] = envs[env]));

module.exports = {
  options: {
    output: 'dist',
    source: 'frontend'
  },
  use: [
    ['neutrino-middleware-env', Object.keys(envs)],
    'neutrino-preset-mozilla-rpweb'
  ]
};
```

`process.env.SERVICE_DOMAIN` does not seem to be defined.

However, if I move the `neutrino-middleware-env` option to the *end* of the `use` list, it is. I had a quick look at https://github.com/mozilla-rpweb/neutrino-preset-mozilla-rpweb and didn't see anything that would obviously cause this, so thinking this might be a bug somewhere in neutrino itself.

**Comment by eliperelman** [comment]
This is expected. The rpweb preset uses the env middleware, so using it again will override the original. Last one wins.

**Comment by wlach** [comment]
Hmm, I don't see any references to env here: https://github.com/mozilla-rpweb/neutrino-preset-mozilla-rpweb

Am I missing something? Also, if this preset (or something it depends on) must modify the environment, could we not just merge it with any modifications made previously? At the very least shouldn't we add some documentation? This seems like a pretty big footgun.
