### ISSUE TITLE
How to pack two entry js file at the same time?

### ISSUE THREAD

**Issue by heibor** [mozilla-neutrino/neutrino-dev#301]
The default entry js file is src/index.js, if I have two js file in the src directory: src/index.js an src/another.js, I want neutrino to build them at the same time? It seems that only src/index.js can be handled by webpack, how to let webpack to build src/another.js at the same time?

**Comment by constgen** [comment]
You can try an advanced technic in the neutronrc:

```js
module.exports = {
  use: [
    'neutrino-preset-any...',
    function customConfig (neutrino){
      neutrino.config
        .entry('secondary')
          .add(require.resolve(`./${neutrino.options.source}/secondary-index.js`))
          .end()
        // the next entry is defined by default so you can skip it at all. 
        // But you can override it if you wish
        .entry('index') 
          .add(neutrino.options.entry)
          .end()
    }
  ]
}
```

**Comment by heibor** [comment]
Thank you, it's very good. Is it possible to provide an option to let the compiled entry file to be standalone? I want to load the js file dynamically, but it has been put into the script tag in the page by default.

**Comment by eliperelman** [comment]
If you want to load a route dynamic, you just need to use dynamic imports. A second JS file will be automatically generated for you, no build changes needed. You can watch the file being dynamically loaded in your devtools as well:

```js
// index.js

setTimeout(() => {
  import('./another');
}, 5000);
```

**Comment by eliperelman** [comment]
Closing as question answered. Please reopen if that doesn't solve your issue. Thanks!
