### ISSUE TITLE
Running production build locally

### ISSUE THREAD

**Issue by yantakus** [mozilla-neutrino/neutrino-dev#302]
Is there a way to run the builded project locally with neutrino? It is very helpful for testing the production version of the app before deploying.

**Comment by constgen** [comment]
It depends on your project. If you don't use History API it should fully work from the file system. Just doubleclick `build/index.html` and open it in the browser. You will be able to verify if it works correctly

**Comment by yantakus** [comment]
I use history API (and 99% of other developers) so it won't work without a server. Most react boilerplates has it on board. It could be express.js with a few lines of configuration to run the app at localhost:[port] and rewrite all URLs to index.html. I know this is easy to add yourself, but it would be really cool to have it in neutrino-dev as almost every project needs this functionality. So having something like: `scripts.start:prod` would be really great.

**Comment by constgen** [comment]
I know. I have a similar idea in my personal roadmap. But can't say that it will be ready even in the next 2 weeks. I would like to copy a static server to `build` folder for production serving purposes. It could also be used locally to run the application in the localhost. The command will look like `cd build && node server.js`

**Comment by barraponto** [comment]
@yantakus is there really a way to have create-react-app build the files for production and then serve them? All I saw in their documentation is the development script `npm start` which does the same as `neutrino start`: compile for development and serve (with HMR).

**Comment by yantakus** [comment]
@barraponto, no. There is such functionality in react-boilerplate for example: https://github.com/react-boilerplate/react-boilerplate/blob/master/server/index.js

**Comment by eliperelman** [comment]
You can run the production by serving the output of `neutrino build`. I use a CLI tool called [serve](https://www.npmjs.com/package/serve) which works great. It should be as simple as:

```bash
neutrino build
serve --single build
```

That will allow you to test your production bundle locally. Please reopen if that doesn't work. Thanks!
