### ISSUE TITLE
Provide documentation for the API

### ISSUE THREAD

**Issue by markelog** [mozilla-neutrino/neutrino-dev#303]
I'm trying to write a preset (or middleware? Don't get the difference).

Checked other presets and it seems they use some cascading API, but I don't get what all of those `when`, `use`, `rule`, `loader`, etc means. As far as I can see there is no docs for it. I guess this should be close to webpack entities... or not?

So it would be cool if you would add a docs for those methods

**Comment by jaridmargolin** [comment]
Behind the scenes neutrino is using [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain).

It may take a little bit of time to get up to speed, but the result is configuration that can be modified in a sane manner. Rather than searching for a plugin `config.plugins[0]` you can access the plugin via `config.plugin('hot')`.

This allows plugins to be composed and shared across various projects.

Anyways, hope that helps :)

**Comment by barraponto** [comment]
@markelog you can ask for support in our slack channel too!
https://neutrino-slack.herokuapp.com/

**Comment by eliperelman** [comment]
On the docs there is an API section:

https://neutrino.js.org/api/

which lists config:

https://neutrino.js.org/api/#config

which links to the webpack-chain docs:

https://github.com/mozilla-neutrino/webpack-chain

I have been contemplating moving the webpack-chain docs into the Neutrino docs so they will be easier for Neutrino users to digest.

**Comment by markelog** [comment]
@jaridmargolin

> Anyways, hope that helps :)

It did, thank you! Created couple ones – https://github.com/markelog/neutrino-preset-component, https://github.com/markelog/neutrino-middleware-sass (since `neutrino-preset-sass` doesn't really work and it should be called `middleware` I think?).

Need dig in the chain docs to improve it, probably both of them has redundancies

@barraponto thanks for the link

@eliperelman

> I have been contemplating moving the webpack-chain docs into the Neutrino docs so they will be easier for Neutrino users to digest.

That would be appreciated

**Comment by eliperelman** [comment]
Resolved in Neutrino v7's docs:

https://neutrino.js.org/webpack-chain
