### ISSUE TITLE
Add -o option to `serve` to open dev server in browser

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#307]
I'll PR this when I have time.

**Comment by eliperelman** [comment]
What about making the really generic for config? I can't remember what we talked about in the past on this but it seems like it wouldn't be that hard to do:

```sh
neutrino start --options.config.devServer.open
```

We could probably sniff it in the API with something like:

```js
if (options.config) {
  neutrino.config.merge(options.config);
}
```

**Comment by eliperelman** [comment]
This is now possible in Neutrino v7 with `--options.config.devServer.open`.
