### ISSUE TITLE
Support multiple Webpack configurations

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#308]
In order to support multiple Webpack configurations, I think we need to re-think how we are allowing configurations to be composed. I still think the right approach is to let middleware modify configuration that is passed to it as an argument, but I think that this should not be a single config object directly accessed on the Neutrino object.

We can allow the user to name configuration objects using the API or `.neutrinorc.js`, and then Neutrino would be able to pass an array of configs to Webpack. The caveat here is that this is a breaking change, as we would probably need to change the signature of the middleware function to take a particular configuration object as a parameter as the user composes them.

Let me try and break down what I mean via some reduced examples:

`simple-middleware`

```js
module.exports = (config, options) => {
  config.devtool('source-map');
};
```

`.neutrinorc.js`

```js
module.exports = {
  react: {
    use: [
      // all the middleware to use for a react config
    ]
  },

  express: {
    use: [
      // all the middleware to use for an express config
    ]
  }
};
```

We could store these named configs on the Neutrino object, and remove `neutrino.config`. It could look something like:

```js
api.configs = {
  react: new Config(),
  express: new Config()
};
```

Then it would still be possible to target them by name, but we would definitely prefer users to compose their middleware via `.neutrinorc.js`. Maybe we even create a `default` middleware when a named one isn't specified.

Thoughts?

**Comment by barraponto** [comment]
how do we do global stuff then, like `neutrino.register('lint')`?

**Comment by constgen** [comment]
Why not array? We will not use these names anyway

**Comment by eliperelman** [comment]
> how do we do global stuff then, like neutrino.register('lint')?

We could still pass the Neutrino object into the middleware, but maybe as the third argument:

```js
module.exports = (config, options, neutrino) => {
  neutrino.register('lint', () => /* ... */);
};
```

> Why not array?

We may be able to get by using array, but right now Neutrino's array format is already defined to accept arrays as a `<middleware, options>` pair. Maybe we could figure out how to do that if it's an array of objects instead.

```js
module.exports = [
  {
    use: [
      // all the middleware to use for a react config
    ]
  },

  {
    use: [
      // all the middleware to use for an express config
    ]
  }
];
```

> We will not use these names anyway

I'm inclined to think this is correct, but didn't want to assume just in case there was a use case I had forgotten about. Using arrays would be easier, but let's make sure we can go down this route.

**Comment by barraponto** [comment]
But what happens if the command-setting middleware is used twice (and is configured from those two middlewares)? I'm foreseeing conflicts.

**Comment by eliperelman** [comment]
Currently, the same thing would happen as when you use 2 middleware; the second declaration would overwrite the first.

You make me think of something else though. What if the CLI could create a separate Neutrino API instance for every separate configuration? This would solve that problem, and would also let us keep the existing middleware function format. In order to make that happen though, I think that `.neutrinorc.js` would need special treatment with the CLI and API. I haven't thought it through, but it sounds like an idea worth exploring, even though it may prove to be difficult.

**Comment by eliperelman** [comment]
In order to have API-per-configuration, we need to break a couple things:

**Only auto-load `.neutrinorc.js` when no CLI `--use` middleware exists**

This means that `neutrino build --use alpha beta gamma` implies a single configuration with the composition of `alpha`, `beta`, and `gamma` and no `.neutrinorc.js`. `neutrino build` should *only* load `.neutrinorc.js`, which should define one or more configurations.

**Change the array format for `.neutrinorc.js`**

We can keep all the other formats the same, but exporting an array directly from `.neutrinorc.js` should be the indicator of multiple configurations. We should only support this format from the RC file.

**Consider removing support from the API for automatically loading the RC file**

This one is painful, but I don't think we can reasonably allow the Neutrino API to create more instances of itself as it needs to load more configurations if it loads the `.neutrinorc.js` itself.

**Comment by constgen** [comment]
Can we just create multiple `Neutrino` instances and run them with different presets in `.neutrinorc.js`? The question is related to the current version. Something simillar to what we do in `.eslintrc.js`

**Comment by eliperelman** [comment]
Addressed in #425.

**Comment by trusktr** [comment]
Where's the docs for this?

**Comment by edmorley** [comment]
Hi! For Neutrino 8 you can use the fork preset, so the docs are here:
https://neutrinojs.org/packages/fork/

For Neutrino 9 (not yet released) things will change slightly - the docs will be updated soon in #896 and #944.
