### ISSUE TITLE
It takes a long time to build with `neutrino--preset-react`

### ISSUE THREAD

**Issue by chenxsan** [mozilla-neutrino/neutrino-dev#309]
1. neutrino 6.1.5
2. neutrino-preset-react 6.1.5
3. npm 5.3.0
4. node 8.1.2
5. macOS Sierra 10.12.6

I'm building my project with these configurations in `.neutrinorc.js`:

```js
module.exports = {
  use: [
    'neutrino-preset-react',
    (neutrino) => neutrino.config.output.filename('[name].js')
  ]
}
```
And here's the output:

<img width="572" alt="screen shot 2017-08-19 at 9 50 59 am" src="https://user-images.githubusercontent.com/1091472/29482451-ef0e4ee6-84c3-11e7-9108-12841eaaf95e.png">

It took 30395ms to finish the build.

Then I tried the build with `webpack.config.js` under the project:

```js
const path = require('path')
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, 'wp'),
    filename: '[name].js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['env', 'react'],
            plugins: [require('babel-plugin-transform-class-properties'), require('babel-plugin-transform-es2015-classes'), require('babel-plugin-transform-object-rest-spread')]
          }
        }
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {}
          }
        ]
      },
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' }
        ]
      }
    ]
  }
}
```

And build with command `npx webpack -p`:

```sh
$ npx webpack -p
Hash: f2314041c61430feead4
Version: webpack 2.7.0
Time: 10585ms
```

I have less than 30 files under `src` folder. I know it might not be sane comparing webpack with neutrino like this, but neutrino just took too long to build.

**Comment by constgen** [comment]
I noticed that CommonChunks plugin optimization takes a significant amount of time at the end of build process. Could you include it also in your "handmade" config to compare results?

**Comment by eliperelman** [comment]
When you get a chance, could you test this with Neutrino v7? Webpack 3, which Neutrino v7 includes, now builds almost 2X faster for me.

**Comment by eliperelman** [comment]
Closing. Please re-open if you get a chance to test this and it doesn't improve.
