### ISSUE TITLE
How do we simply compile an entry point, but not run it?

### ISSUE THREAD

**Issue by trusktr** [mozilla-neutrino/neutrino-dev#318]
The closest thing to what I need is `neutrino-preset-node`, but that automatically runs the output file.

How would I do the same thing, but not run the file, only build it (but stay in watch mode (start mode))?

In this case, I also don't need hot module reload, I just need to build the file exactly like the `node` preset does, and rebuild on changes, and that's all.

I have a feeling it's easy, but I'm not getting it from the docs...

Maybe I need to use only the middlewares that I want, and create my own preset? Or is it easy starting with the node preset then disabling some things?

EDIT: it's not easy disabling things: https://github.com/mozilla-neutrino/neutrino-dev/issues/320

**Comment by eliperelman** [comment]
It's currently not documented very well, but when using the `start` command with no server options, it will trigger the webpack watcher:

https://neutrino.js.org/cli/#neutrino-start
https://neutrino.js.org/api/#startwebpackconfig-neutrinoapi

This means that for presets based on the Web presets, you need to remove the `devServer` config, and presets based on the Node one need to remove the `start-server` plugin:

```js
// Web-based presets
neutrino.config.devServer.clear();
```

```js
// Node-based presets
neutrino.config.plugins.delete('start-server');
```

Give that a shot and let me know how it goes.

**Comment by eliperelman** [comment]
Closing with posted solution. If that doesn't seem to be correct, please feel free to reopen. Thanks!
