### ISSUE TITLE
Setting Environment Variables for preset-node

### ISSUE THREAD

**Issue by trusktr** [mozilla-neutrino/neutrino-dev#319]
I'd like for an app that I run with neutrino-preset-node to use _real_ environment variables (not transpiled in).

How can we do this?

**Comment by eliperelman** [comment]
Node.js still has access to `process.env` and environment variables won't be transpiled in unless you use a Webpack plugin or the env middleware to force it to. For example, if you had the following code:

```js
console.log(process.env.TEST);
```

and ran the build with:

```bash
TEST="hello world" neutrino build
```

Your built file won't contain the string "hello world". It will still contain the call to `process.env.TEST` and it will be pulled at runtime (e.g. when the Node.js process starts).

Hope that answers your question. 👍

**Comment by trusktr** [comment]
It makes sense, but as mentioned in the other issue, the env vars are
undefined when neutrino runs the script.

**Comment by trusktr** [comment]
I ended up making a webpack plugin to start/restart the server using `child_process.exec` on `compiler` `after-emit` event.

**Comment by timkelty** [comment]
@trusktr @eliperelman I believe the confusion here may be related this bug: https://github.com/mozilla-neutrino/neutrino-dev/issues/839

**Comment by edmorley** [comment]
@trusktr does the issue you were seeing sound like #839?
