### ISSUE TITLE
Remove or disable a middleware from a preset.

### ISSUE THREAD

**Issue by trusktr** [mozilla-neutrino/neutrino-dev#320]
I'm trying something similar to https://github.com/mozilla-neutrino/neutrino-dev/issues/168.

This doesn't seem to always work. For example, disabling the `hot` plugin from the `node` preset causes an error.

I have this `.neutrinorc.js` file:

```js
module.exports = {
  use: [
    'neutrino-preset-node',

    // disable Hot Module Reloading for now, it's buggy.
    n => {
      return n
        .config
        .plugins
        .delete('hot')
    },

  ],
  options: {
    entry: 'server/index',
  },
}
```

and running `neutrino start` causes this error:

```
✔ Build completed
/path/to/project/build/index.js:739
        throw new Error("[HMR] Hot Module Replacement is disabled.");
        ^

Error: [HMR] Hot Module Replacement is disabled.
    at Object.<anonymous> (/path/to/project/build/index.js:739:8)
    at __webpack_require__ (/path/to/project/build/index.js:21:30)
    at Object.<anonymous> (/path/to/project/build/index.js:1068:18)
    at __webpack_require__ (/path/to/project/build/index.js:21:30)
    at /path/to/project/build/index.js:67:18
    at Object.<anonymous> (/path/to/project/build/index.js:70:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by trusktr** [comment]
Ah, well, turns out we can just do

```js

// running the server.
module.exports = {
  use: [
    ['neutrino-preset-node', {
      // disable Hot Module Reloading for now, it's buggy.
      hot: false,
    }]
  ],
  options: {
    entry: 'server/index',
  },
}
```

Knowing how to do it the other way might be good for learning though.

**Comment by trusktr** [comment]
Ah, but now, with `hot` set to false, the server doesn't seem to restart on changes... Hmmm.....

**Comment by eliperelman** [comment]
You are correct, there are some features that take disabling multiple things in order for them to be truly shut off. In those instances, we try to provide a middleware option for it, like you have discovered with HMR. While you can remove the hot plugin, you still have to remove the hot entrypoint from the bundle, and it's easier to use a setting to control this whole feature than to have to remember which items to remove.

Another thing to remember is some plugins or rules are only available in certain environments, as documented on the presets docs.

Also, start-server should restart the server when it's used along with HMR, but without HMR it doesn't get the signals it needs to restart the server.

**Comment by trusktr** [comment]
Maybe it's easy enough to get HMR working? What are the steps to enable HMR in my server code?
