### ISSUE TITLE
Is there an option to detect start vs build mode in .neutrinorc.js?

### ISSUE THREAD

**Issue by trusktr** [mozilla-neutrino/neutrino-dev#324]
Right now I'm doing

```
IS_BUILD=true neutrino build
```

then reading that ENV var in the `.neutrinorc.js` file. Is there a better way? Does neutrino set some property I can check?

**Comment by eliperelman** [comment]
In v6 the easiest way right now is to read the `NODE_ENV` environment variable. By default Neutrino sets this to `development` when using `start`, and `production` when using `build`. In v7 we plan to also have a dedicated property you can read for this.

Another way would be to read the args directly:

```js
neutrino.options.args._[0] // build, start, etc.
```

**Comment by eliperelman** [comment]
This is now available in v7 by reading `neutrino.options.command`.
