### ISSUE TITLE
Plugin class names missing from --inspect output

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#328]
Currently the output when using `--inspect` includes a `plugins` property, which contains an array of plugin options but not the actual name of the plugin to which the options belong.

For example:
```js
  plugins: [
    {
      keys: [
        'NODE_ENV'
      ],
      defaultValues: {}
    },
    {
      options: {
        template: 'ui/index.html',
        filename: 'index.html',
        hash: false,
        inject: false,
        compile: true,
        favicon: false,
        minify: {
          useShortDoctype: true,
          keepClosingSlash: true,
          collapseWhitespace: true,
          preserveLineBreaks: true
        },
        cache: true,
        showErrors: true,
        chunks: 'all',
        excludeChunks: [],
        title: 'Webpack App',
        xhtml: true,
        appMountId: 'root',
        mobile: true
      }
    },
```

To work out the mapping of plugins to options, I have to cross-reference against the output from `neutrino.config.toConfig()`:
```js
  plugins: 
   [ EnvironmentPlugin { keys: [Array], defaultValues: {} },
     HtmlWebpackPlugin { options: [Object] },
```

This is using neutrino 6.2.0 and webpack-chain 3.3.0 with node 8.5.0.

**Comment by eliperelman** [comment]
The output of --inspect is essentially the config that will be passed to webpack, but sorted and formatted. Webpack doesn't accept this config with named output, it doesn't match its schema.

Maybe we can change `--inspect` to also allow viewing an object form of the webpack-chain config, e.g. `--inspect named`? Or `--inspect-named`?

**Comment by edmorley** [comment]
Yeah I understand it's not meant to be passed to webpack, that's not what I want to use it for.

The bug here is that the current serialised representation is incomplete -- it omits key information (the plugin names) to be able to understand the current configuration.

**Comment by eliperelman** [comment]
From `--help` for `--inspect`:

> Output a string representation of the configuration used by Neutrino and exit

You're right; this statement makes it sound like we are giving the Neutrino configuration and not the Webpack configuration. Switching it to the Neutrino config would be a breaking change. We can either fix the wording of the help to reference webpack, or change the output. Both outputs are useful, so we need a way to see both.

**Comment by edmorley** [comment]
I think we might still be miss-understanding each other?

I don't really mind whether the output is technically neutrino config or webpack config, all I would like is for the output to include as much of the configuration as possible. However at the moment names of the plugins aren't specified anywhere.

From the OP above:
```
  plugins: [
    {
      keys: [
        'NODE_ENV'
      ],
      defaultValues: {}
    },
```

Now whilst I can guess that these plugin options are for the `EnvironmentPlugin`, that's not stated explicitly, and instead could be for a hypothetical `DeleteEnvironmentPlugin`. Without knowing the plugin name, displaying the options is much less useful.

**Comment by edmorley** [comment]
Though as a separate issue/feature request, having a way to view both the Neutrino config and webpack configs would be useful :-)

**Comment by eliperelman** [comment]
I think I understand: right now you are seeing the webpack config, and you want the Neutrino config so you can see the names of entities.

**Comment by edmorley** [comment]
I think I see where the confusion is coming from - surely the webpack config has to include the plugin names at some point? (Yes passed as objects, but that could still be serialised?)

**Comment by edmorley** [comment]
And just in case, another clarification: By plugin names, I'm not meaning the identifier (eg `style`) given to plugins in Neutrino, I'm meaning the actual module/class name of the webpack plugin.

**Comment by eliperelman** [comment]
Note that this would be a breaking change, since switching the format of the inspection would break uses of diff: `git diff --no-index a.inspection b.inspection`.

**Comment by edmorley** [comment]
I guess what I'm really after is an equivalent to create-react-app's "eject" feature.

**Comment by edmorley** [comment]
v8.3.0 has just been released, which includes the new `--inspect-new`.
