### ISSUE TITLE
Remove node polyfill options from neutrino-preset-web that match the defaults

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#329]
Split out of:
https://github.com/mozilla-neutrino/neutrino-dev/issues/196#issuecomment-300018977

neutrino-preset-web includes the following:
```js
    .node
      .set('console', false)
      .set('global', true)
      .set('process', true)
      .set('Buffer', false)
      .set('__filename', 'mock')
      .set('__dirname', 'mock')
      .set('setImmediate', true)
      .set('fs', 'empty')
      .set('tls', 'empty')
```

However many of these match the defaults ([here](https://webpack.js.org/configuration/node/)) so could be removed.

**Comment by constgen** [comment]
Is it really a bad practice?

**Comment by edmorley** [comment]
I didn't say it was a bad practice; just seems unnecessary to duplicate the defaults.

I think it's actually clearer for someone reading the preset if only the deviations from webpack's defaults are listed, so they know what behaviour changes are being caused by Neutrino rather than webpack.

**Comment by eliperelman** [comment]
Fixing in https://github.com/mozilla-neutrino/neutrino-dev/pull/315/commits/d0087adca2e8b7ddab0af2027ec1f0b184fc154c.
