### ISSUE TITLE
Use babel-minify-webpack-plugin instead of babili-webpack-plugin

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#330]
The [babili-webpack-plugin](https://www.npmjs.com/package/babili-webpack-plugin) npm package has been renamed to [babel-minify-webpack-plugin](https://www.npmjs.com/package/babel-minify-webpack-plugin).

It looks likes new versions will only be released under the new npm package name, so Neutrino will need to switch over to it at some point.

See: webpack-contrib/babel-minify-webpack-plugin#55

**Comment by eliperelman** [comment]
Fixing in https://github.com/mozilla-neutrino/neutrino-dev/pull/315/commits/b6958133605f6c3e3bff0d395aee2a5da2d5118c.
