### ISSUE TITLE
Tag for 5.9.1 is missing

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#341]
It's not exactly urgent, but I noticed the other day that the tag for 5.9.1 is missing.

It looks like it was released from the `hotfix-5.9.1` branch:
https://github.com/mozilla-neutrino/neutrino-dev/compare/hotfix-5.9.1

I'm presuming if that commit were tagged we could also clean up that now unneeded branch?

**Comment by eliperelman** [comment]
Tagged!

**Comment by edmorley** [comment]
Many thanks :-)

I've now deleted the hotfix-5.9.1 branch.
