### ISSUE TITLE
compile-loader is unable to extend once its created

### ISSUE THREAD

**Issue by leesiongchan** [mozilla-neutrino/neutrino-dev#348]
```
neutrino.use(compileLoader, {
  babel: compileLoader.merge(babelOpts, {
    plugins: [
      'AAA',
    ],
  }),
});

neutrino.use(loaderMerge('compile', 'babel'), {
  plugins: [
    'BBB',
  ],
});
```

This cannot work as the plugin `BBB` will simply be ignored.

**Comment by eliperelman** [comment]
Could you provide a reproducible repo where this occurs? I know many repos that do this and it works there, so I'm curious what is happening with yours.

**Comment by eliperelman** [comment]
Ah, I think I see what is going on. In your original usage of the compile loader you are using the babel merge, but in the second, it's just using a deep merge, not the babel-merge.

**Comment by eliperelman** [comment]
Closing as noted in my previous comment. If that doesn't work for you, please re-open. Thanks!
