### ISSUE TITLE
Create neutrino-preset-vue

### ISSUE THREAD

**Issue by suhaotian** [mozilla-neutrino/neutrino-dev#35]
This project is awesome 👍 . But I didn't see preset about vue ~

**Comment by eliperelman** [comment]
@suhaotian Thank you! Unfortunately, I myself am not qualified to create a Vue preset, but would gladly promote it if someone created one.

**Comment by eliperelman** [comment]
Looks like there might be some resources here to at least get a first draft of a Vue preset going:

https://vuejs.org/v2/guide/single-file-components.html

**Comment by suhaotian** [comment]
```js
'use strict';

const web = require('neutrino-preset-web');
const webpack = require('webpack');


module.exports = neutrino => {
  web(neutrino);

  const { config } = neutrino;

  config.module
    .rule('compile')
    .test(/\.vue?$/)
    .loader('vue-loader', ({ options }) => {
      return {
        options: merge(options, {})
      };
    });
};
```

I try this, but didn't work...

**Comment by eliperelman** [comment]
By adding a **new** loader, there are no options passed to the function. You should only use the function when you need to override something already in place. Also, I don't see `merge` defined in this scope. Also, switching the `.test` to `/\.vue?$/` in the `compile` rule means Babel will only compile files with that extension, is that desired?

If the `vue-loader` doesn't need any options, consider writing it like this:

```js
config.module
  .rule('compile')
  .test(/\.vue?$/)
  .loader('vue-loader');
```

**Comment by barraponto** [comment]
Got a package published today for vue support: https://www.npmjs.com/package/neutrino-preset-vue

**Comment by eliperelman** [comment]
That's awesome! I'm going to go ahead and close this, and recommend that Vue users check out your preset. Thanks!
