### ISSUE TITLE
For React projects use eslint-config-airbnb rather than eslint-config-airbnb-base

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#352]
In `eslint-config-airbnb` 8.0.0 (2016-04-21), the package was split into two parts:
* [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) for the generic (non-react) rules
* [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) which includes some react rules and inherits from `eslint-config-airbnb-base`

Currently Neutrino uses `eslint-config-airbnb-base` for both React and non-React projects, however I think React projects should be switched to use `eslint-config-airbnb`, which would enable the additional rules here:
https://github.com/airbnb/javascript/blob/dfbeaaea4bf09be28463eea15979dd8c862fc10a/packages/eslint-config-airbnb/rules/react.js
https://github.com/airbnb/javascript/blob/dfbeaaea4bf09be28463eea15979dd8c862fc10a/packages/eslint-config-airbnb/rules/react-a11y.js

...and presumably save [neutrino-preset-mozilla-rpweb](https://github.com/mozilla-rpweb/neutrino-preset-mozilla-rpweb) and others from having to manually turn on rules themselves.

The only problem is that I can't work out what should have the dependency on `eslint-config-airbnb`?

`neutrino-preset-airbnb-base` is not React specific, and `neutrino-preset-react` doesn't assume a linter is being used. Either way, it seems like wherever we add it we're going to end up with missing peer dependency warnings for users who don't use linting or don't use react. (Albeit similar to the missing `eslint` peer dependency warning we already get from `neutrino-preset-react`'s dependency on `eslint-plugin-react`, so perhaps this isn't a problem?)

Thoughts?

**Comment by edmorley** [comment]
I guess the options boil down to:
a) Accept that we're going to have more missing peer dependency warnings for some cases
b) Prevent the missing peer dependency warnings by adding some of them as `dependencies` that will sometimes be unused
c) Create a `neutrino-preset-airbnb` to go alongside `neutrino-preset-airbnb-base` (perhaps putting react in the name to make things clearer)
d) Decide it's hard to separate the linting and building presets, and turn `neutrino-preset-airbnb-base` into middleware that's a `dependency` of `neutrino-preset-react` and `neutrino-preset-web`, which has the react customisations moved into `neutrino-preset-react`. We'd also add an option for people who didn't want linting to turn it off (they'd just have some unused dependencies, which wouldn't be the end of the world). People wanting only the linting feature (eg like what Neutrino does for its CI run) could use switch to the newly renamed `neutrino-middleware-airbnb-base`.

**Comment by eliperelman** [comment]
> a) Accept that we're going to have more missing peer dependency warnings for some cases

The status quo and path to least resistance. This represents a slightly degraded developer experience though since users may think they've either installed incorrectly or missed something.

> b) Prevent the missing peer dependency warnings by adding some of them as dependencies that will sometimes be unused

I think this is a legitimate solution, especially since these dependencies are build-related and not application-related.

> c) Create a neutrino-preset-airbnb to go alongside neutrino-preset-airbnb-base (perhaps putting react in the name to make things clearer)

This technically already exists in a community preset with https://www.npmjs.com/package/neutrino-preset-airbnb

> Decide it's hard to separate the linting and building presets, and turn neutrino-preset-airbnb-base into middleware that's a dependency of neutrino-preset-react and neutrino-preset-web, which has the react customisations moved into neutrino-preset-react.

This only works if we assume that anyone who uses linting wants Airbnb settings. There is also "standard", Google, eslint recommended, and a couple other major presets, not to mention completely custom.

**Comment by eliperelman** [comment]
I added a note to the Airbnb-base preset in #396 that React users should probably use the airbnb preset instead. Is that resolution good enough?

**Comment by edmorley** [comment]
I would really prefer to have this functionality handled by a stock Neutrino preset (whether that be a separate preset like (c) above, or else rolled into an existing one like the other options) rather than a community preset.
