### ISSUE TITLE
Inline html-webpack-template

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#371]
For the sake of expediency, I'm thinking we should inline the template from html-webpack-template directly into the html-template middleware. Basically, copy the file from https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs and place it in the html-template middleware.

Their project is MIT licensed, so we should probably reference that in the file.

**Comment by edmorley** [comment]
I think my preference would be to open a PR for jaketrent/html-webpack-template#61, and only after inline that cleaned up template into this repo (which may not even be necessary, given that PR has had a response).

**Comment by eliperelman** [comment]
That sounds awesome, and I'm glad to see movement in this direction! As long as the template can stay configurable from "configuration", I'm all for it. I'm going to close this for now, and we can address in the future if the need arises.
