### ISSUE TITLE
ESLint middleware can't consider .eslintrc

### ISSUE THREAD

**Issue by constgen** [mozilla-neutrino/neutrino-dev#377]
Test suite: https://mega.nz/#!HdMnVbRI!3s6VchrK3EFxzsUTF-DUVb5G5PvW4SGNYzepzI7gLCs

Here is a simple preset. It uses `neutrino-middleware-eslint`. The middleware is configured with 

```js
use: [
  ['neutrino-middleware-eslint', { useEslintrc: true }],
  ...
]
```
I expect it to take `.eslintrc` file from the root of the project and report errors. But running lint task can't find any errors in code

```
> neutrino lint

✔ Running lint completed
```

But in the code editor I see multiple mistakes in the `index.js` because this file doesn't match ESLint rules.

Am I doing this right? Hot to use `.eslintrc` as an ESLint config to be considered in `eslint-loader`?

**Comment by constgen** [comment]
You can see also other issues related to the same preset:
- https://github.com/mozilla-neutrino/neutrino-dev/issues/374
- https://github.com/mozilla-neutrino/neutrino-dev/issues/375

**Comment by eliperelman** [comment]
The eslint middleware options object accepts top-level middleware options, with eslint options being provided at the `eslint` property, i.e. you should change your configuration to this:

```js
['neutrino-middleware-eslint', { eslint: { useEslintrc: true } }]
```

Give that a shot!

**Comment by constgen** [comment]
That worked. Thanks.

**Comment by edmorley** [comment]
Great! Is there a docs tweak that you can think of, that might have made this clearer? :-)

**Comment by constgen** [comment]
As a Neutrino contributor I usually read not documents but sources. And this was my mistake. Looking at https://www.npmjs.com/package/neutrino-middleware-eslint I could figure out how it should work.
