### ISSUE TITLE
See if any of the @neutrinojs/eslint defaults are unnecessary

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#383]
neutrino-middleware-eslint sets a number of ESLint defaults:
https://github.com/mozilla-neutrino/neutrino-dev/blob/6ea0728c95ac1a7c061428a8dd7a33db7dfd6192/packages/neutrino-middleware-eslint/index.js#L59-L84

As seen in #380 and then discussed in #382, the more defaults there are, the more things people have to override/keep in sync, particularly for confusing rules like [strict](https://eslint.org/docs/rules/strict#rule-details), whose behaviour is affected by several other settings.

Some settings we clearly do need (eg `sourceType: 'module'`), however I wonder if setting that makes eg `impliedStrict: true` redundant?

I've had a look at the ESLint docs, but it still wasn't that clear - so I suspect we'll need to do some digging in the ESLint source (followed by some tickets asking for clarification in their docs).

**Comment by eirikurn** [comment]
IMO emitWarning and emitError should have default values. Both force all eslint issues as warnings and errors respectively. When both are set, emitError takes precedence, causing eslint warnings to be reported as errors and breaking the build.

The default logic is better (emitError: false, emitWarning: false). Then eslint issues are reported as warnings unless one of them is an error.

**Comment by eliperelman** [comment]
Fixed emitting, evaluated settings in #493.

**Comment by edmorley** [comment]
Reopening, since I think at least `impliedStrict` is unnecessary.

**Comment by eliperelman** [comment]
> `impliedStrict` - enable global strict mode (if `ecmaVersion` is 5 or greater)
