### ISSUE TITLE
exclude js and eslint processing in `src/static` folder

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#4]
_From @gasolin on December 27, 2016 9:37_

It's always happen when dev need to put some vendor libraries in code base.

_Copied from original issue: mozilla-neutrino/neutrino-preset-web#7_

**Comment by eliperelman** [comment]
In order to do this, we would need to standardize what the default static directory is, e.g. `src/static`. Contenders could be `static`, `public`, or `assets`. I believe there would also need to be other config changes needed to support this.

**Comment by eliperelman** [comment]
_From @gasolin on January 6, 2017 2:3_

I saw some configuration use `static` as non processed folder, and `assets` as recommend processable folder.. (Though I forget the source)

**Comment by eliperelman** [comment]
A good directory name could also be "vendor".

**Comment by eliperelman** [comment]
Putting these directories outside `src` would also work, without any Neutrino changes.

**Comment by eliperelman** [comment]
@mozilla-neutrino/core-contributors I'd like to settle on an agreed-upon directory name as the default directory for static/non-compiled assets. Most likely this would still live within the `source` directory so relative path roots would work correctly.

**Comment by jaridmargolin** [comment]
As you described it as "static/non-compiled assets", I would move forward with static. Semantically it makes sense. It was also the name I gravitated towards.

Specifically, I'm not a huge fan of vendor. I believe it is unnecessarily specific. There could be multiple reasons a file is needed to be static.

---

I also like the idea of keeping of it in the source directory but don't have a concrete argument... just intuition.

**Comment by constgen** [comment]
It is also important to work like `http.get('/static/data.json').then()`. So I think the name and place is correct. If nobody has no additional ideas I am ready to start work on a middleware.

**Comment by eliperelman** [comment]
Resolved in #235.
