### ISSUE TITLE
Multiple bundles support

### ISSUE THREAD

**Issue by onigoetz** [mozilla-neutrino/neutrino-dev#40]
Hello,

first congratulations for the awesome work on Neutrino, I had very similar needs in the company I work for and the solution I came to is far less elegant than yours.

The applications I work on have a strong legacy and I don't have the possibility to change everything on their interface, so I need to generate JS/CSS bundles manually, currently my solution is a mix of webpack + gulp.

Is there maybe a way to support mutliple instances of webpack inside Neutrino ?

I know my requirements are quite particular but if this is possible for you, then I would probably switch our build stack to Neutrino and contribute a few features as well.

**Comment by eliperelman** [comment]
If you need to generate different bundles, without knowing your exact needs, I would probably recommend running different commands mapped to different configuration combinations. For example:

```bash
neutrino build --presets neutrino-preset-react bundle-a
neutrino build --presets neutrino-preset-react bundle-b
neutrino build --presets neutrino-preset-react bundle-c
```

This would generate 3 bundles, each with configuration overrides in their `bundle-*` files. You can also make this easier in your package.json:

```json
{
  "presets": [
    "neutrino-preset-react:
  ],
  "scripts": {
    "build:a": "neutrino build --presets bundle-a",
    "build:b": "neutrino build --presets bundle-b",
    "build:c": "neutrino build --presets bundle-c",
    "build": "yarn build:a && yarn build:b && yarn build:c"
  }
}
```

Another option would be to add multiple entry points above just the `index` entry. This would create a bundle for every entry. It would most likely share other common configuration between the entries.

Does that answer your use case?

**Comment by onigoetz** [comment]
Very interesting, yes it seems to answer my need.

I'll come back to you if I have more questions or to share my final implementation :D

Thanks

**Comment by eliperelman** [comment]
Great! Closing for now. Please file an issue if there is a problem with those approaches.
