### ISSUE TITLE
How to reload .neutrinorc.js without a restart

### ISSUE THREAD

**Issue by Cheonsoon** [mozilla-neutrino/neutrino-dev#417]
Hi, it works well for webpack-dev-server reload modified scripts in 'src' directory. But how can I made it possible to reload scripts (like '.neutrinorc.js') outside the 'src' directory?

**Comment by constgen** [comment]
I don't know any ways without black magic. It is a Node module. So it is cached in Node process registry and not required more than ones. Even if you will change it in the File System and require it in a runtime the original version will be executed - the version of a moment when `neutrino start` was called

**Comment by eliperelman** [comment]
Just wanted to follow up here; @constgen is correct. Right now Neutrino doesn't have a way to re-start the compilation process when the `.neutrinorc.js` file changes. The best course of action would be to kill and re-run when that happens. Would happily accept a PR to implement this if anyone is interested. Best of luck.
