### ISSUE TITLE
style-loader: support style extraction via extract-text-webpack-plugin

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#439]
This is currently possible via https://github.com/jaridmargolin/neutrino-contrib/tree/master/packages/neutrino-middleware-extractstyles or https://github.com/barraponto/neutrino-preset-extractstyles, however, it requires being pretty tightly coupled to the existing `style` rule from `@neutrinojs/style-loader`.

I think it might be better to support it in neutrino core.

I'm thinking incorporating it into `@neutrinojs/style-loader` via `options.extract`.

/cc @jaridmargolin @barraponto 

If this sounds reasonable, I can work on PR.

**Comment by eliperelman** [comment]
YES YES YES!

**Comment by eliperelman** [comment]
I'd like extraction to become the default usage of style-loader.

**Comment by timkelty** [comment]
Great (I agree). I'll whip up a PR

**Comment by barraponto** [comment]
Maybe we could wait for Webpack's big plan? https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7

**Comment by eliperelman** [comment]
The problem with waiting is we don't know how long it will be until this plan goes into effect. Most likely it will mean a breaking change anyway, so that would mean another Neutrino rev.

**Comment by timkelty** [comment]
Here's a working implementation: https://github.com/mozilla-neutrino/neutrino-dev/pull/443

**Comment by timkelty** [comment]
Closed via #443
