### ISSUE TITLE
Use preact and vue in create-neutrino-project

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#442]
The preact preset seems pretty good as-is to add to the list, just need the scaffold bits.

I'd like the vue addition to be a single addition to neutrinorc instead of 2 with web+vue.

@fa7ad @barraponto I'm going to extend an offer if you so choose: you can add your presets to core if you like, under `@neutrinojs/preact` and `@neutrinojs/vue`. If that interests you, or you want to discuss more about it, let's do it!

**Comment by helfi92** [comment]
Today I'll work on the scaffolding bit. I agree it's a good idea to make the vue preset a single addition to be consistent with the other presets neutrino offers.

**Comment by fa7ad** [comment]
@eliperelman I'd be happy with the arrangement, just tell me what to do.

**Comment by eliperelman** [comment]
@fa7ad nice! just create a directory in packages named `preact` with the contents of your current package, and we can go from there!

**Comment by fa7ad** [comment]
@eliperelman check #454

**Comment by eliperelman** [comment]
Completed with #484.
