### ISSUE TITLE
Condition adding api options in lieu of repeated conditions

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#451]
Discussion started here: https://github.com/mozilla-neutrino/neutrino-dev/pull/446#issuecomment-345268552

There are lots of places where we repeat the same conditions for the same purpose. It might be nice to add some API options instead, to have a single source of truth for these repeated actions:

Examples:
- Use `neutrino.options.optimize` instead of `neutrino.options.env.NODE_ENV === 'production'`
- Use `neutrino.options.rev` instead of `neutrino.options.command === 'build'`

Thoughts? @mozilla-neutrino/core-contributors

**Comment by timkelty** [comment]
Pretty sure I like the idea of `neutrino.options.optimize`.

Less sure about `neutrino.options.revOutput`, but:
The idea for that came when adding conditions for revving assets across a few presets…
Some were `neutrino.options.command === 'build'`, some were `neutrino.options.command !== 'start'`, etc. - and I thought it would be nice if there were a consistent option to reference instead.

**Comment by eliperelman** [comment]
I like the idea, as long as the options are synonymous across middleware for their default values. For example, if there is `neutrino.options.optimize`, and its default value is `process.env.NODE_ENV === 'production'`, then that declaration should hold true across middleware, e.g. it makes sense for any middleware to be in optimize mode when the NODE_ENV is production.

I think optimize is a good place to start.

**Comment by timkelty** [comment]
Ok, I've added `neutrino.options.optimize` to https://github.com/mozilla-neutrino/neutrino-dev/pull/446
