### ISSUE TITLE
Update upgrading Neutrino guide for v7->v8

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#466]
As always, a new major release will bring breaking changes. We will need to update the upgrading Neutrino guide for v8, outlining the breaking changes, but also listing features.

**Comment by edmorley** [comment]
I'm still catching up on all the older recent review requests and PRs, but thought I'd comment on this new one first. I was thinking that perhaps we should turn the migration guide into a page that covers all versions? When updating several versions at once it's currently a bit of a pain to have to trawl through the old docs to find the necessary interim migration docs.

**Comment by eliperelman** [comment]
I agree, let's do it!

**Comment by helfi92** [comment]
I don't mind doing this :)

**Comment by eliperelman** [comment]
I'd have a look through the landed PRs, and specifically the ones tagged breaking changes.

**Comment by eliperelman** [comment]
@helfi92 I think we are close to shipping, so we can move forward with this now.

**Comment by helfi92** [comment]
I'm on it 💪
