### ISSUE TITLE
Problems with the use of script-ext-html-webpack-plugin

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#470]
The Neutrino web preset uses [script-ext-html-webpack-plugin](https://github.com/numical/script-ext-html-webpack-plugin) however at first glance I think it doesn't work with `html-webpack-template` (since that requires disabling injection mode, see jaketrent/html-webpack-template#61).

In addition, the docs for `script-ext-html-webpack-plugin` say:

> The order is important - the plugin must come after HtmlWebpackPlugin.

However the web preset doesn't use `.before()`, which is important if people end up customising the `html` plugin.

Also, do we really need to use `script-ext-html-webpack-plugin` at all?

**Comment by eliperelman** [comment]
Honestly, I can't even remember that that plugin does, maybe we don't need it.

**Comment by okonet** [comment]
This plugin allowed adding `defer` or `async` attributes to `script` tags that, in turn, allowed controlling the loading of scripts. After the removal it's not possible to do anymore. I don't think it was necessary to remove it after all since it's working as expected when added back.
