### ISSUE TITLE
Cannot find a way to disable output hash as part of generated file names

### ISSUE THREAD

**Issue by iongion** [mozilla-neutrino/neutrino-dev#475]
I am using my own `index.html` and I did not find a way to get the name of the output file to be able to properly embed it, therefore I had to do this:
```
  neutrino.config.output
    .filename('[name].js')
    .chunkFilename('[name][id].chunk.js');
```

But, because of this, I am now unable to build due to the fact that there are identical names when using code splitting. Any idea on how I can do one of these two optons:
- be able to intercept the output name
- be able to take control of the file names without name collision

**Comment by eliperelman** [comment]
My best guess to be able to embed these into the html file is to have a look at the source template from html-webpack-template to see how they do it:

https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs

**Comment by edmorley** [comment]
We use our own index.html by passing the filename via the `template` property (make sure to also enable `inject` mode). This doesn't require changing anything else :-)

**Comment by iongion** [comment]
@edmorley I specifically want to assume control over inject
@eliperelman Yup, this looks to be a good starting point!

This section is responsible:
```
    <% if (options.inlineManifestWebpackName) { %>
        <%= htmlWebpackPlugin.files[options.inlineManifestWebpackName] %>
    <% } %>

    <% for (item of options.scripts) { %>
    <% if (typeof item === 'string' || item instanceof String) { item = { src: item, type: 'text/javascript' } } %>
  	<script<% for (key in item) { %> <%= key %>="<%= item[key] %>"<% } %>></script>
    <% } %>

    <% for (key in htmlWebpackPlugin.files.chunks) { %>
    <% if (htmlWebpackPlugin.files.jsIntegrity) { %>
    <script
      src="<%= htmlWebpackPlugin.files.chunks[key].entry %>"
      type="text/javascript"
      integrity="<%= htmlWebpackPlugin.files.jsIntegrity[htmlWebpackPlugin.files.js.indexOf(htmlWebpackPlugin.files.chunks[key].entry)] %>"
      crossorigin="<%= webpackConfig.output.crossOriginLoading %>"></script>
    <% } else { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[key].entry %>" type="text/javascript"></script>
    <% } %>
    <% } %>
```

Thank you so much!
