### ISSUE TITLE
Web with Node development

### ISSUE THREAD

**Issue by lubo08** [mozilla-neutrino/neutrino-dev#482]
It is possible setup parallel node preset with web preset for parallel development both node and static web? If yes and you advice or provide some example I will appreciate it. :)

**Comment by eliperelman** [comment]
@lubo08 this is upcoming in Neutrino v8! With the fork middleware, you'll be able to launch different middleware in a single repo. If you want to learn more about it, here is the current README for the fork middleware:

https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/fork

**Comment by lubo08** [comment]
Thanks, perfect.  v8 :+1:
