### ISSUE TITLE
Add description and website to github homepage

### ISSUE THREAD

**Issue by jnachtigall** [mozilla-neutrino/neutrino-dev#49]
On https://github.com/mozilla-neutrino/neutrino-dev/ there's "No description or website provided." which makes this project look, well, immature ;)

**Comment by helfi92** [comment]
@jnachtigall The documentation link at the end of the README takes you to the website but you're right, we probably need to add the website as well in the description. Thanks for the feedback!

**Comment by tj** [comment]
A link to the repo on https://neutrino.js.org/ would probably be good too, I didn't see one

**Comment by helfi92** [comment]
@tj I added a link to https://neutrino.js.org right beside the repo description

**Comment by tj** [comment]
Just my 0.02 but I'd put it on the Introduction page for anyone who lands there, and doesn't dig into https://neutrino.js.org/contributing/development.html
