### ISSUE TITLE
style-loader: allChunks: true for ExtractTextPlugin?

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#503]
I'm wondering if we should be setting `allChunks: true` for `ExtractTextPlugin` in `style-loader`: https://github.com/webpack-contrib/extract-text-webpack-plugin#options

Does anybody have experience with this option? Reading the description, I'm still not 💯  I grasp if and when to use it, but it does mention combined use with `CommonsChunkPlugin`:

> Extract from all additional chunks too (by default it extracts only from the initial chunk(s))
> When using CommonsChunkPlugin and there are extracted chunks (from ExtractTextPlugin.extract) in the commons chunk, allChunks must be set to true

Any ideas @mozilla-neutrino/core-contributors?

**Comment by eliperelman** [comment]
From reading the description it *seems* like we should be setting it to `true` when using with extract.

**Comment by timkelty** [comment]
@eliperelman that was my impression as well.
