### ISSUE TITLE
Optimize css in production

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#507]
Probably using https://github.com/NMFR/optimize-css-assets-webpack-plugin, or https://github.com/sandark7/csso-loader

**Comment by timkelty** [comment]
Like we've done with minify and imagemin middlewares, I'm assuming this would best be served as its own preset, that would get applied in production from parent presets (web, etc)

It will also need to be easily disabled, as users may likely already be minifying through an existing css pipeline (postcss + cssnano, e.g.)

**Comment by eliperelman** [comment]
Maybe we should change the minify middleware to do all this, but have options to control what to minify:

```js
neutrino.use(minify, {
  babel: {},
  styles: {},
  images: {}
});
```

Thoughts?

**Comment by timkelty** [comment]
Yeah, I considered that as well…it seems tempting, but ultimately I'm not sure if there is much benefit? (one more thing to manage and pass options through)

At the very least - the current state it is a bit confusing to a newcomer in the naming. `minify` at this point really just mean minifying js. `imagemin` is specific, but also references the particular package doing the optimization.

**Comment by timkelty** [comment]
Or combine the ideas, and have `@neutrino/minify` be an aggregate of
`@neutrino/minify-js`
`@neutrino/minify-img`
`@neutrino/minify-styles`

But again - that makes me think there isn't much benefit.

**Comment by eliperelman** [comment]
> Or combine the ideas

I like that idea. What I also want to avoid is naming things according to file extension. Using `minify-js` isn't completely logical when using Vue, or may be confusing when you are using JSX. You want to minify those still.

So this seems logical to me:

`@neutrinojs/babel-minify`
`@neutrinojs/image-minify`
`@neutrinojs/style-minify`

And then `@neutrinojs/minify` could be the composition of said packages.

**Comment by eliperelman** [comment]
I plan on shipping v8 next week, so let me know if you think we can get this in time or told add it as a feature afterwards.

**Comment by timkelty** [comment]
@eliperelman I'll see if I can get to it this weekend.

**Comment by timkelty** [comment]
I might focus on splitting them up: https://github.com/mozilla-neutrino/neutrino-dev/issues/525 and hold off on the css bit, as that could be added later.
