### ISSUE TITLE
Scaffolding doesn't find the create-project package

### ISSUE THREAD

**Issue by gerherz** [mozilla-neutrino/neutrino-dev#512]
When running ```yarn create @neutrinojs/project <directory-name>```, I get the following output:

> yarn create v1.3.2
> [1/4] Resolving packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/@neutrinojs%2fcreate-project: Not found".

**Comment by eliperelman** [comment]
The create-project stuff in master is a part of v8. You'll find the current release in the `release/v7` branch. Don't worry though, this will be released in the next few days!
