### ISSUE TITLE
Multi compiler setup.

### ISSUE THREAD

**Issue by DylanPiercey** [mozilla-neutrino/neutrino-dev#513]
Is it possible to use webpacks [multi compiler](https://webpack.js.org/api/compiler/#multicompiler) configuration using neutrino?

Specifically I want to setup neutrino to build an isomorphic project where it is bundling both a server side and a browser side. Much of the config is the same but with some differences. This feature is also handy for stuff like bundling tests with webpack at the same time as your main bundle.

I'd love to be able to create the following or something similar.
```console
neutrino --use isomorphic --use web --use react
```

**Comment by eliperelman** [comment]
Hey @DylanPiercey! This will be possible with our v8 release coming up in the next few days. This will utilize the upcoming `fork` middleware:

https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/fork

This will let you drop a `.neutrinorc.js` file in your project similar to the following and build node (isomorphic) at the same time as the react code in a single project:

```js
module.exports = {
  use: [
    ['@neutrinojs/fork', {
      configs: {
        react: '@neutrinojs/react',
        node: {
          options: { source: 'server' },
          use: ['@neutrinojs/node']
        }
      }
    }]
  ]
};
```

Should have this released in the next few days! I'm going to close this as answered, but feel free to ask any other questions you may still have about this. Thanks!

**Comment by DylanPiercey** [comment]
Thats awesome! Looking forward to the release.
