### ISSUE TITLE
package.json is getting messy

### ISSUE THREAD

**Issue by helfi92** [mozilla-neutrino/neutrino-dev#517]
The `package.json` is starting to have a lot of scripts. It presently has the following scripts:

```json
  "scripts": {
    "build": "lerna run build",
    "changelog": "auto-changelog --remote upstream --commit-limit false",
    "cnp": "NODE_ENV=test packages/create-project/bin/create-neutrino-project.js $(yarn random)",
    "docs:build": "gitbook build && cp CNAME _book",
    "docs:deploy": "yarn docs:build && gh-pages --dist _book --remote upstream",
    "docs:serve": "gitbook serve",
    "link:all": "lerna exec yarn link",
    "lint": "node packages/neutrino/bin/neutrino lint",
    "precommit": "lint-staged",
    "random": "node -e \"process.stdout.write(require('crypto').randomBytes(8).toString('hex'))\"",
    "release": "yarn build && lerna publish --force-publish=*",
    "release:preview": "yarn build && lerna publish --force-publish=* --skip-git --skip-npm",
    "test": "yarn test:all --no-verbose --match '!*@neutrinojs*'",
    "test:all": "nyc --reporter lcov ava --verbose --fail-fast packages/*/test",
    "validate:eslintrc:root": "eslint --no-eslintrc --print-config . -c ./.eslintrc.js > /dev/null",
    "validate:eslintrc:eslint": "eslint --no-eslintrc --print-config . -c ./packages/eslint/eslintrc.js > /dev/null",
    "validate:eslintrc:airbnb": "eslint --no-eslintrc --print-config . -c ./packages/airbnb/eslintrc.js > /dev/null",
    "validate:eslintrc:airbnb-base": "eslint --no-eslintrc --print-config . -c ./packages/airbnb-base/eslintrc.js > /dev/null",
    "validate:eslintrc:standardjs": "eslint --no-eslintrc --print-config . -c ./packages/standardjs/eslintrc.js > /dev/null",
    "validate:eslintrc": "yarn validate:eslintrc:eslint && yarn validate:eslintrc:airbnb-base && yarn validate:eslintrc:airbnb && yarn validate:eslintrc:standardjs && yarn validate:eslintrc:root",
    "version": "yarn changelog --package && git add CHANGELOG.md"
  }
```

We can remove this mess by using something like [nps](https://github.com/kentcdodds/nps) where it would allow us to move our scripts to a `package-scripts.js` file. Also, because it is a javascript file, you can start doing a lot more with your project scripts.

**Comment by helfi92** [comment]
If we have an agreement on this, I can open a PR soon :)

**Comment by eliperelman** [comment]
I like the idea  but I have contention with:

> To use nps, it's recommended that you either install it globally (`npm i -g nps`) or add `./node_modules/bin` to your `$PATH`

Neither of these are good ideas. If we can find a way to either keep the bins in scope, or use relative paths within this file, I'd consider it.

**Comment by edmorley** [comment]
There definitely are quite a lot of script entries, however I'm not really sure that's a problem? What I'm less keen on however, is the duplication between the various eslint entries. If there was a way to reduce that (perhaps by using an eslint test runner script), then that would seem to be a win.

**Comment by edmorley** [comment]
I think there are a few aspects to this:
1. If there are more than N number of script entries, should we move them to another file?
2. Are there any commands we can remove?
3. Can we reduce duplication of the same command/options between script entries? (eg the eslint ones)

Given we don't ship the monorepo root `package.json` to end users I don't think (1) is an issue (and I don't think it's worth installing an additional package to be able to do this).

For (2) I've had a quick glance and can't see anything that is definitely unused.

For (3), we could possible come up with a wrapper script or similar, but it's likely to increase overall line count more than it reduces it, so not sure it's worth it, especially given the scarce time we have to work on this project.

As such I'm going to close this out for now (if this were Bugzilla I'd used "resolved incomplete", ie reopen if something else comes up).
