### ISSUE TITLE
Allow users to specify a custom template or middleware during create-project

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#521]
When asked questions like type of project or type of linting middleware, it would be neat if we allowed users to input their own value if they didn't like the choices, for example, if during adding a test runner they had their own AVA preset, or if their team used their own linting rules. Granted, there are some edge cases to work out.

- [ ] If a user specifies their own middleware, how should create-project be informed of how to do the scaffolding?

Maybe this is as simple as exporting well-known named function from the middleware. Or looking for a certain directory within the middleware that we template with.

**Comment by edmorley** [comment]
I think this would drastically increase the complexity of create-project, which is already quite hard to get right (ref #895), and as such maybe something we shouldn't support?

**Comment by eliperelman** [comment]
Yeah, probably not. It would be easy enough for people to automate their own setups that bake Neutrino stuff in via yeoman.
