### ISSUE TITLE
Split/Refactor minify (minify,*-minify)

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#525]
From here: https://github.com/mozilla-neutrino/neutrino-dev/issues/507

Packages will be:

`@neutrinojs/babel-minify`
`@neutrinojs/image-minify`
`@neutrinojs/style-minify`

and @neutrinojs/minify could be the composition of said packages.

**Comment by timkelty** [comment]
@eliperelman do you prefer `*-minify` or `minify-*` for the package names?

**Comment by eliperelman** [comment]
`*-minify`, since `babel-minify` has already set a precedent.

**Comment by eliperelman** [comment]
Fixed in #545.
