### ISSUE TITLE
Can't merge plain values in Neutrino options

### ISSUE THREAD

**Issue by eirikurn** [mozilla-neutrino/neutrino-dev#568]
- What version of Neutrino are you using? ^6.1.5
- Are you trying to use any presets? If so, which ones, and what versions? neutrino-preset-react@^6.1.5
- Are you using the Yarn client or the npm client? What version? yarn@1.3.2
- What version of Node.js are you using? 8.7.0
- What operating system are you using? MacOS 10.13.1
- What did you do?

Created a custom neutrino option (passed in through cli and node api) with a plain value (string). Then tried to override said value, eg like this `.neutrinorc.js`:

```
module.exports = {
  options: {
    customOption: 'new value',
  },
}
```

- What did you expect to happen?

I expect the merged options to contain `{ customOption: 'new value' }`.

- What actually happened, contrary to your expectations?

The end result was a deep merged value like this:

```
customOption: { '0': 'n', '1': 'e', '2': 'w', '3': ' ', '4': 'v', '5': 'a', '6': 'l', '7': 'u', '8': 'e'}`
```

Since deepmerge only supports merging object or array like values. Not sure if this issue belongs here or there.

**Comment by eliperelman** [comment]
@eirikurn could it be that you are trying to merge properties where the original value was an object, but you are passing a string?

**Comment by eliperelman** [comment]
Hmm, actually I don't replicate with these cases:

```js
const merge = require('deepmerge')

merge({ custom: '123' }, { custom: '456' })
// { custom: '456' }

merge({ custom: { hey: '123' } }, { custom: '456' })
// { custom: '456' }

merge({ custom: [123] }, { custom: '456' })
// { custom: '456' }
```

Could you show a particular case where this happens so I can see if it's a Neutrino thing?

**Comment by eirikurn** [comment]
Right. The proper case is this:

```
> merge('old value', 'new value')
{ '0': 'n',
  '1': 'e',
  '2': 'w',
  '3': ' ',
  '4': 'v',
  '5': 'a',
  '6': 'l',
  '7': 'u',
  '8': 'e' }
```

This is the affected line: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/src/api.js#L97

So, it's an issue when merging options with string, number and boolean values. A workaround is to nest custom options in a namespace:

```
{
  thisDoesNotWork: 'new value',
  ns: {
    thisWorks: 'new value',
  },
}
```

**Comment by eliperelman** [comment]
Oooooooo good catch! I'll get a patch going.

**Comment by eirikurn** [comment]
Wow! Amazing turnaround. Thank you thank you thank you!

**Comment by edmorley** [comment]
Thank **you** for reporting! 😄
