### ISSUE TITLE
Add Hot Module Replacement (HMR) for Node.js

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#59]
The story around HMR for React is pretty good, but practically non-existent for Node.js apps. Right now Neutrino skips any kind of separate build process for Node.js in development vs. production, just generating an identical build except with a different NODE_ENV. Let's see if we can get proper HMR support in the preset, and document how it can be integrated into Node.js apps.

**Comment by ericclemmons** [comment]
Inspiration for ya:

- https://github.com/ericclemmons/webpack-hot-server-example
- https://github.com/palmerhq/backpack/pull/39

**Comment by eliperelman** [comment]
@ericclemmons fantastic, thank you!

**Comment by eliperelman** [comment]
@ericclemmons I've got an initial implementation up with my latest commit to the v5 branch, in case you're interested what the Neutrino implementation looks like so far:

https://github.com/mozilla-neutrino/neutrino-dev/pull/86/commits/e3c7b60210f2f1466621e0bcb10b8b97e1a7d8c8#diff-d7b5dff9b5ea9063b998d40d77a9646d

I was surprised by how well it worked and easy it was to implement. :smile:

**Comment by eliperelman** [comment]
This will be resolved in #86.

**Comment by eliperelman** [comment]
Resolved with #86.

**Comment by ericclemmons** [comment]
Nice work @eliperelman!  I hope I've been able to help somehow.  HMR on the server has been awesome when working with large projects.

**Comment by eliperelman** [comment]
Your links were a tremendous help! I hope users find value in your contribution.
