### ISSUE TITLE
Links to docs on neutrino.js.org seem busted

### ISSUE THREAD

**Issue by wlach** [mozilla-neutrino/neutrino-dev#605]
On the main page there's a link to "react components" under "Packages", but it seems to be broken: 

<img width="831" alt="screen shot 2017-12-12 at 3 06 02 pm" src="https://user-images.githubusercontent.com/20569/33908434-011f1112-df4e-11e7-9196-8e8fbf4a711f.png">

https://neutrino.js.org/packages/react-components/packages/react-components/packages/react-components/packages/react-components/

Seems to be a similar story for other packages.

**Comment by wlach** [comment]
Navigating manually to https://neutrino.js.org/packages/react-components/ works fine tho.

**Comment by eliperelman** [comment]
Strange, I don't replicate in FF or Chrome:

<img width="428" alt="screen shot 2017-12-12 at 3 09 01 pm" src="https://user-images.githubusercontent.com/285899/33908560-7088cafc-df4e-11e7-9821-4585d32f809c.png">

<img width="304" alt="screen shot 2017-12-12 at 3 09 31 pm" src="https://user-images.githubusercontent.com/285899/33908570-79b61918-df4e-11e7-9b43-4ec1a17a03df.png">

@mozilla-neutrino/core-contributors can anyone else replicate?

**Comment by helfi92** [comment]
Works fine for me on FF and Chrome.

**Comment by wlach** [comment]
hmm I can't reproduce now either... ? so strange, will reopen if I see it again

**Comment by eliperelman** [comment]
@wlach wow that's weird! Thanks for the report anyway. Maybe it was a bad cache?
