### ISSUE TITLE
Add create-project examples to the quickstarts of all presets

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#606]
For example, the React docs:

<img width="878" alt="screen shot 2017-12-12 at 3 13 03 pm" src="https://user-images.githubusercontent.com/285899/33908729-f82960a2-df4e-11e7-8979-c23cf0446cde.png">

We should show usage with `create-project` in the docs first, then we could show how to manually set up showing the existing set up.

**Comment by helfi92** [comment]
Sounds good. I'll do that sometime today.

**Comment by helfi92** [comment]
Completed in https://github.com/mozilla-neutrino/neutrino-dev/pull/610.
