### ISSUE TITLE
Using create-project with yarn does not work

### ISSUE THREAD

**Issue by armenzg** [mozilla-neutrino/neutrino-dev#607]
I tried running this command `yarn create @neutrinojs/project ci-metrics`.

```
armenzg@armenzg-mbp repos$ yarn create @neutrinojs/project ci-metrics
yarn create v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/opencollective/-/opencollective-1.0.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/armenzg/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by eliperelman** [comment]
We added a `--debug` flag to the command now, could you try and it report its output?

```bash
yarn create @neutrinojs/project ci-metrics --debug
```

**Comment by armenzg** [comment]
Debug did not show anything new than the output above.

I removed yarn from the globally installed packages [1].
I removed node, yarn and heroku from my brew installations [3].
I reinstalled node LTS and yarn via brew (as it is the recommended way).

I still got the same issue [0]

[0]

> armenzg@armenzg-mbp ~$ yarn create @neutrinojs/project asd --debug
> yarn create v1.3.2
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/opencollective/-/opencollective-1.0.4.tgz: Request failed \"404 Not Found\"".
> info If you think this is a bug, please open a bug report with the information provided in "/Users/armenzg/.config/yarn/global/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

[1]

> armenzg@armenzg-mbp ~$ npm ls -g --depth=0
> /usr/local/lib
> ├── npm@5.5.1
> └── npm-check-updates@2.13.0

[2]

> armenzg@armenzg-mbp ~$ brew install yarn --without-node
> Updating Homebrew...
> ==> Auto-updated Homebrew!
> Updated 1 tap (caskroom/cask).
> No changes to formulae.
> 
> ==> Downloading https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz
> Already downloaded: /Users/armenzg/Library/Caches/Homebrew/yarn-1.3.2.tar.gz
> 🍺  /usr/local/Cellar/yarn/1.3.2: 14 files, 3.9MB, built in 1 second
> armenzg@armenzg-mbp ~$ which node
> /usr/local/bin/node
> armenzg@armenzg-mbp ~$ which yarn
> /Users/armenzg/.yarn/bin/yarn
> armenzg@armenzg-mbp ~$ which npm
> /usr/local/bin/npm
> armenzg@armenzg-mbp ~$ node --version
> v8.9.3
> armenzg@armenzg-mbp ~$ yarn --version
> 1.3.2
> armenzg@armenzg-mbp ~$ npm --version
> 5.5.1

[3]
> armenzg@armenzg-mbp repos$ sudo npm i -g npm
> Password:
> /usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
> /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> + npm@5.6.0
> added 27 packages, removed 11 packages and updated 38 packages in 8.983s
> armenzg@armenzg-mbp repos$ npm uninstall -g yarn
> removed 1 package in 0.071s
> armenzg@armenzg-mbp repos$ npm install -g yarn
> npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
> /usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
> /usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
> + yarn@1.3.2
> added 1 package in 1.431s
> armenzg@armenzg-mbp repos$ npm uninstall -g yarn
> removed 1 package in 0.075s
> armenzg@armenzg-mbp repos$ brew install yarn
> Updating Homebrew...
...

> armenzg@armenzg-mbp repos$ brew uninstall --force heroku
> Uninstalling heroku... (12,872 files, 71.2MB)
> armenzg@armenzg-mbp repos$ brew uninstall node
> Uninstalling /usr/local/Cellar/node/9.3.0_1... (5,125 files, 49.6MB)
> node 8.6.0, 8.5.0, 8.1.3, 8.1.4 4 are still installed.
> Remove all versions with `brew uninstall --force node`.
> armenzg@armenzg-mbp repos$ brew uninstall --force node
> Uninstalling node... (15,868 files, 186MB)
> armenzg@armenzg-mbp repos$ brew uninstall --force npm
> armenzg@armenzg-mbp repos$ brew uninstall yarn
> Error: No such keg: /usr/local/Cellar/yarn

**Comment by armenzg** [comment]
I removed everything again [1] and started from scratch with nvm [2].

[1]
https://github.com/nodejs/node-v0.x-archive/issues/4058
sudo rm -rf /usr/local/{bin/{node,npm},lib/node_modules/npm,lib/node,share/man/*/node.*}

[2]
> curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
> nvm install node
> armenzg@armenzg-mbp ~$ nvm run node --version
> Running node v9.3.0 (npm v5.5.1)
> v9.3.0
> brew install yarn --without-node
> armenzg@armenzg-mbp ~$ brew install yarn --without-node
> ==> Downloading https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz
> Already downloaded: /Users/armenzg/Library/Caches/Homebrew/yarn-1.3.2.tar.gz
> 🍺  /usr/local/Cellar/yarn/1.3.2: 14 files, 3.9MB, built in 1 second
> armenzg@armenzg-mbp ~$ yarn --version
> 1.3.2
> armenzg@armenzg-mbp ~$ cd repos/
> armenzg@armenzg-mbp repos$ yarn create @neutrinojs/project asd --debug
> yarn create v1.3.2
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/opencollective/-/opencollective-1.0.4.tgz: Request failed \"404 Not Found\"".
> info If you think this is a bug, please open a bug report with the information provided in "/Users/armenzg/.config/yarn/global/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
> armenzg@armenzg-mbp repos$ npm ls -g --depth=0
> /Users/armenzg/.nvm/versions/node/v9.3.0/lib
> └── npm@5.5.1

**Comment by edmorley** [comment]
I don't think this is a problem with Neutrino, since `opencollective` isn't used by either it or it's dependencies.

My guess is that:
* since [yarn create](https://yarnpkg.com/lang/en/docs/cli/create/) installs the specified starter kit globally, it's causing a refresh of your global yarn package directory
* some previous global install of another package has the broken dependency on opencollective
* the global package directory wasn't cleaned up above 

Could you try purging the directory specified when you run `yarn global dir`?

**Comment by armenzg** [comment]
Thank you Ed! That was it.

**Comment by edmorley** [comment]
Great! :-)

**Comment by weishijun14** [comment]
Hi!

```
wsj@wsj:~$ yarn create @neutrinojs/project sss
yarn create v1.9.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.9.4", while you're on "1.9.2".
info To upgrade, run the following command:
$ sudo apt-get update && sudo apt-get install yarn
success Installed "@neutrinojs/create-project@8.3.0" with binaries:
      - create-project
[#####################################################################] 332/332/bin/sh: 1: /home/wsj/.yarn/bin/@neutrinojs/create-project: not found
error Command failed.
Exit code: 127
Command: /home/wsj/.yarn/bin/@neutrinojs/create-project
Arguments: sss
Directory: /home/wsj
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```
I do  purging the directory specified when  run `yarn global dir`, but still error
