### ISSUE TITLE
Trace warnings in debug mode

### ISSUE THREAD

**Issue by helfi92** [mozilla-neutrino/neutrino-dev#619]
When running in debug mode, we should use the [`trace-warnings`](https://nodejs.org/api/cli.html#cli_trace_warnings) flag to print stack traces for process warnings.

**Comment by Shruti9520** [comment]
Hi,
Can I work on this issue?

**Comment by edmorley** [comment]
After #852 we don't have a Neutrino binary that's used as the only entrypoint any more, so presumably this would have to be done via something like `process.on('warning', e => console.warn(e.stack));` ?
https://nodejs.org/api/process.html#process_event_warning

That said, is this still worth it - given people can just `node --trace-warnings ...` or `NODE_OPTIONS='--trace-warnings' webpack ...` etc?

**Comment by eliperelman** [comment]
I'd say no, let's close.
