### ISSUE TITLE
Add engines check to all packages

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#625]
Right now the documentation lists out the requirements of using Neutrino or middleware:

> - Node.js v6.10+
> - Yarn or npm client
> - Neutrino v8

Now, in the root workspace package.json:

```json
"engines": {
  "node": ">=6.10.0",
  "yarn": "^1.2.1"
}
```

Good for development, not very helpful for our users. Let's update the docs to reflect our current support, and codify this in every monorepo package.json's `engines`:

Node.js v6 LTS, v8, v9
Yarn v1.2.1+, or npm v5.5 (I think? @helfi92?)

**Comment by helfi92** [comment]
I believe it's npm v5.4.0. I will open a pull-request for that.

**Comment by helfi92** [comment]
The [first LTS version](https://nodejs.org/en/download/releases/) of v6 (Boron) happens to be 6.9.0. To that end, I think it's safe to downgrade the minimum requirement of node to that version.
