### ISSUE TITLE
ES6 won't compile when using Jest preset with v8

### ISSUE THREAD

**Issue by okonet** [mozilla-neutrino/neutrino-dev#638]
I'm trying to upgrade to v8 from v7 and following the guide. But after I switched to new presets I'm getting lots of these errors:

```
 FAIL  src/content/app/components/ui/DataGrid/SortedDataGrid.test.jsx
  ● Test suite failed to run

    /Users/okonet/Projects/feedly/client/src/content/app/components/ui/DataGrid/SortedDataGrid.test.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
```

No matter what I try I can't get it working again. Looks like the preset doesn't pick the `compile` part from `react` preset.

**Comment by eliperelman** [comment]
Bisecting this:

```
❯ git bisect bad
f4bc5fb753cef5425a04db4336287c9a967a1812 is the first bad commit
commit f4bc5fb753cef5425a04db4336287c9a967a1812
Author: Hassan Ali <helfi92@gmail.com>
Date:   Tue Dec 5 10:33:16 2017 -0500

    Use extensions in outstanding package (#532)

:040000 040000 79bfadb4ea25262a955136aa3dfe5f5a9d082e10 346bfe63f7e6ca13b3fac6ac29c715e7840d0f82 M	packages
```

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/neutrino-dev/pull/532

**Comment by eliperelman** [comment]
This issue seems to be fixed when I change to the old JS names value:

```
BAD (Current): /.(js|jsx)$/
GOOD (Previous): \.(js|jsx)$
```

The current values are derived from:

https://github.com/mozilla-neutrino/neutrino-dev/blob/abdcbeb20098531a74a6d39198e878de29309e8d/packages/jest/src/index.js#L26

**Comment by eliperelman** [comment]
@helfi92 in order to resolve this, I think we need to just manually build out this value instead of using `regexFromExtensions`.

**Comment by helfi92** [comment]
Sounds good. I think this is happening because we are setting a regex as a property to an object. https://github.com/mozilla-neutrino/neutrino-dev/blob/abdcbeb20098531a74a6d39198e878de29309e8d/packages/jest/src/index.js#L61.

PR on the way 🛫

**Comment by helfi92** [comment]
@eliperelman https://github.com/mozilla-neutrino/neutrino-dev/pull/640.

**Comment by ftes** [comment]
This issue still occurs for me with `v8.1.2`:

`SyntaxError: Unexpected token import`
