### ISSUE TITLE
neutrino.custom.eslintrc in lint presets don't output correct eslintrc json

### ISSUE THREAD

**Issue by timothyquach** [mozilla-neutrino/neutrino-dev#64]
I've tried getting neutrino linting presets to output hints to vscode and found some bugs.
`neutrino.custom.eslintrc` throws an exception because a global is undefined and assumes `options.envs` is an array of objects.

**Comment by eliperelman** [comment]
According to the docs, the rc file doesn't take `envs` like CLIEngine, but `env`, which is an object of environments to enable.

http://eslint.org/docs/user-guide/configuring
