### ISSUE TITLE
Possible to extend create-project?

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#642]
Mostly what I want to do is include a few additional boilerplate files (`.stylelintrc.js`, `.env`, `.postcssrc.js`, `.browserslistrc`), though Ideally I'd like to make some minor modifications to `.neutrinorc.js` as well.

Is there a decent way to extend @neutrinojs/create-project? Or do you think I should just have a separate generator that I run _after_ I run that?

**Comment by eliperelman** [comment]
See #521.

**Comment by eliperelman** [comment]
Closing as duplicate.
