### ISSUE TITLE
Duplicated `require('source-map-support').install()`

### ISSUE THREAD

**Issue by chenxsan** [mozilla-neutrino/neutrino-dev#650]
I'm developing react component using https://neutrino.js.org/packages/react-components/. In one of my component, I'm including a css file:

```
import '../common.css'
```
When I run `yarn build`, I will have a `index.[hash].css` file under `build` folder. The content has two `require('source-map-support').install();`:

```
require('source-map-support').install();
require('source-map-support').install();
body{margin:0}
/*# sourceMappingURL=index.b80e79d93a286e27f30657d3bf988aa7.css.map*/
```

Some package info:

```
  "devDependencies": {
    "@neutrinojs/jest": "^8.0.14",
    "@neutrinojs/react-components": "^8.0.14",
    "@neutrinojs/standardjs": "^8.0.14",
    "babel-eslint": "^8.1.2",
    "neutrino": "^8.0.14",
    "standard": "^10.0.3"
  },
```

And the `.neutrinorc.js`:

```
module.exports = {
  use: [
    '@neutrinojs/standardjs',
    '@neutrinojs/react-components',
    '@neutrinojs/jest'
  ]
};
```

**Comment by eliperelman** [comment]
@chenxsan could you provide a small repo or gist to replicate with?

**Comment by eliperelman** [comment]
Also fyi, you shouldn't need to install `babel-eslint` or `standard`. Those come with the presets you have installed.

**Comment by chenxsan** [comment]
@eliperelman Hi, you can check it here https://github.com/chenxsan/duplicated-install

1. `yarn` to install
2. `yarn build` to build the component

Here's what I got:

<img width="813" alt="screen shot 2018-01-09 at 4 40 36 pm" src="https://user-images.githubusercontent.com/1091472/34711875-da5b3d3e-f55b-11e7-82e2-8103d06c5813.png">
