### ISSUE TITLE
[Regression Bug]: @neutrinojs/web - if options.port is changed, dev server still on port 5000

### ISSUE THREAD

**Issue by evliu** [mozilla-neutrino/neutrino-dev#652]
Tested in brand new projects and existing. if I set `--options.port 8080` as a CLI parameter or change `.neutrino.js` config, the web server is at port 8080 but CLI still says dev server running on port 5000. The page will load but this will show in the console:
```
Failed to load resource: net::ERR_CONNECTION_REFUSED      client?0485:164
[WDS] Disconnected!            @ client?0485:164
GET http://localhost:5000/sockjs-node/info?t=1515019640800 net::ERR_CONNECTION_REFUSED         sockjs.js?3600:1601 
```

any help would be appreciated. worked fine in neutrino v4

**Comment by evliu** [comment]
Note: also tried configuring `devServer` to all use that port and it didn't work; still seeing WDS try to connect to localhost:5000

**Comment by eliperelman** [comment]
I can confirm the issue.
