### ISSUE TITLE
Regex in doc not working

### ISSUE THREAD

**Issue by piu130** [mozilla-neutrino/neutrino-dev#66]
I tried to use the regex in the [doc](https://github.com/mozilla-neutrino/neutrino-dev/blob/master/docs/customization/simple.md#module-rules):

```json
"test": "/\\.less$/"
```

But it doesn't apply for `.less`-files. Because we use `new RegExp({regexp})` it checks for files named `\.less{endOfString}\` (RegExp: /\\/\\.less$\\//) instead of `.less`.

So it should be

```json
"test": "\\.less$"
```

- What version of Neutrino are you using? 4.2.0
- Are you trying to use any presets? If so, which ones, and what versions? neutrino-preset-react@4.2.0
- Are you using the Yarn client or the npm client? What version? npm@3.10.10
- What version of Node.js are you using? 6.9.5
- What operating system are you using? WSL@15042.0

**Comment by eliperelman** [comment]
Oooh, good catch! Updating the docs now.
