### ISSUE TITLE
merge.all concatenates eslint arrays 

### ISSUE THREAD

**Issue by plumpNation** [mozilla-neutrino/neutrino-dev#665]
What version of Neutrino are you using?
`"neutrino": "^8.0.16"`

Are you trying to use any presets? If so, which ones, and what versions?
`"@neutrinojs/standardjs": "^8.0.16"`

Are you using the Yarn client or the npm client? What version?
`yarn --version`
`1.3.2`

What version of Node.js are you using?
`9.3.0`

What operating system are you using?
`OSX 10.13.1 High Sierra`

What did you do?
I tried to override babel/object-curly-spacing value. The hardcoded one is ["error", "always"]. I wanted to override it to [2, "never"]. I use the 2 to make the issue clearer as it is easy to see if it replaces the string "error".

What did you expect to happen?
To be able to change the value.

What actually happened, contrary to your expectations?
the value was concatenated by `merge.all()`
(4) `["error", "always", 2, "never"]`

Related issue:

I am also unable so far to find a way to override that setting using an .eslintrc file, with the eslint.useEslintrc flag set to true.

**Comment by eliperelman** [comment]
@plumpNation could you provide the code or a sample repo to replicate with?

Regarding overrides, you won't be able to override from a `.eslintrc` file. It's possible to do from a `.eslintrc.js` file, but we strongly encourage you to use the `.neutrinorc.js` file to control all overrides, since that will make it apply cleanly to all the Neutrino commands.

**Comment by plumpNation** [comment]
```
const eslintOptions = {
    eslint: {
        rules: {
            'babel/object-curly-spacing': [2, 'never']
        }
    }
};

module.exports = {
    use: [
        ['@neutrinojs/standardjs', eslintOptions],
        '@neutrinojs/web'
    ]
};
```

Now in @neutrino/standardjs/index.js the merge.all creates a config object containing

`'babel/object-curly-spacing': [ 'error', 'always', 2, 'never' ]`
