### ISSUE TITLE
Allow configuring html-loader via web preset options

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#682]
The font, image, style and babel loaders support being passed options via the web preset to configure their behaviour:
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.0.18/packages/web/index.js#L132-L134

However the html-loader doesn't:
https://github.com/mozilla-neutrino/neutrino-dev/blob/v8.0.18/packages/web/index.js#L104

For context, the option I wish to adjust is [html-loader](https://github.com/webpack-contrib/html-loader)'s `attr` option, which defaults to `['img:src']`, but I'd like to change to `['img:src', 'link:href']` so it picks up favicons (`<link href="...">`).

If we did add such an option, we'd probably have to call it `htmlLoader` or similar, since `html` is already taken for the options passed to `html-webpack-plugin`.

My workaround in the meantime:
```js
neutrino.config.module
  .rule('html')
  .use('html')
  .tap(options => ({
    ...options,
    // Override html-loader's default of `img:src`,
    // so it also parses favicon images (`<link href="...">`).
    // TODO: Remove once we update to html-loader 1.0.0+:
    // https://github.com/webpack-contrib/html-loader/issues/17
    attrs: ['img:src', 'link:href'],
  }));
```

**Comment by edmorley** [comment]
Now that the default value for `attrs` has been updated in #943, Treeherder's has no need to be able to pass custom options to `html-loader` when used via the react preset.

As such, I'm happy to close this out, unless we feel it's a feature we really should have regardless?

**Comment by eliperelman** [comment]
We can close, I don't think it's too crazy to ask for an options tap here.
