### ISSUE TITLE
How to add babel-polyfill in Neutrino v8?

### ISSUE THREAD

**Issue by gormonn** [mozilla-neutrino/neutrino-dev#688]
How to add babel-polyfill in Neutrino v8?

**Comment by eliperelman** [comment]
Hello! You can use babel-polyfill as any other application-level dependency. Simply install it via npm or yarn, and import it, typically before any code that may depend on it, usually as the first import in your main file:

```js
// src/index.jsx

import 'babel-polyfill';
import { Component } from 'react';

// ...
```

**Comment by eliperelman** [comment]
As the above response should answer your question, I am going to close this issue. If for some reason my answer doesn't resolve this, please feel free to re-open. Thanks!
