### ISSUE TITLE
Custom presets not showing up in list

### ISSUE THREAD

**Issue by nwaywood** [mozilla-neutrino/neutrino-dev#689]
I have created two presets and as far as I can tell they satisfy all the [conditions listed](https://neutrino.js.org/presets/community-presets.html) but they are still not showing up in the list.

The presets I have made are:

- [neutrino-preset-flow](https://www.npmjs.com/package/neutrino-preset-flow) and
- [neutrino-preset-emotion](https://www.npmjs.com/package/neutrino-preset-emotion)

Is there an issue with the list not updating or is there something wrong with my presets?

Also note that it has been 5 days since I published those packages so I doubt its a batch processing issue.

Thanks in advance

**Comment by eliperelman** [comment]
Hmm, that is odd. When I look up the same query on npms.io, I see 63 results:

https://npms.io/search?q=keywords:neutrino-preset%20not:deprecated

It's interesting that the list on the docs is limited to 25. I'll look into it.

**Comment by eliperelman** [comment]
Looks like npms now has a `size` parameter, which defaults to 25:

https://api-docs.npms.io/. I'll revise to the max and see what happens.
