### ISSUE TITLE
Runtime error on neutrino.js.org displaying preset list 

### ISSUE THREAD

**Issue by nwaywood** [mozilla-neutrino/neutrino-dev#695]
Thanks for fixing https://github.com/mozilla-neutrino/neutrino-dev/issues/689

It looks like the community middleware list is correctly displaying are entries now. But the [community preset](https://neutrino.js.org/presets/community-presets.html) list display nothing with the following error in the console

![image](https://user-images.githubusercontent.com/3773641/35539316-2b7329b2-05a5-11e8-9d5b-ec4901382aba.png)

**Comment by eliperelman** [comment]
Sorry about that, everything should now be good!
