### ISSUE TITLE
Stylelint preset does not work with stylelint-config-standard

### ISSUE THREAD

**Issue by jamiedust** [mozilla-neutrino/neutrino-dev#698]
When using the stylelint preset (thanks for that by the way!) linting fails when using the latest stylelint-config-standard (a popular preset), because it includes an unrecognised rule.

`Error: Undefined rule font-family-no-missing-generic-family-keyword`

This is because the version of `stylelint-webpack-plugin` which is used by the preset is 0.7.0, which depends on stylelint v7, this needs to be increased to at least 0.9.0, in order to fix this issue. I may submit a PR over the next day or so if I get time.

Thanks.

What version of Neutrino are you using?

7.4.0

Are you trying to use any presets? If so, which ones, and what versions?

preset-stylelint 1.1.0

Are you using the Yarn client or the npm client? What version?

Tried with both, npm version 5.5.1

What version of Node.js are you using?

8.9.3

What operating system are you using?

Mac OSX

What did you do?
What did you expect to happen?
What actually happened, contrary to your expectations?

Described above

**Comment by timkelty** [comment]
@jamiedust I think you might be using the wrong package…

The core stylelint middlware was only introduced in Neutrino v8: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/CHANGELOG.md#v810

The NPM package is `@neutrinojs/stylelint`, not `neutrino-preset-stylelint`.

**Comment by timkelty** [comment]
See #699

**Comment by jamiedust** [comment]
Aah, my mistake apologies for wasting your time.

I had previously used neutrino-middleware-stylelint, so I thought this was the new package. It makes sense now.
