### ISSUE TITLE
Stylelint preset is not running

### ISSUE THREAD

**Issue by jamiedust** [mozilla-neutrino/neutrino-dev#699]
Thanks for a great project and bringing the stylelint preset into core.

What version of Neutrino are you using?

7.4.0

Are you trying to use any presets? If so, which ones, and what versions?

preset-stylelint 1.1.0

Are you using the Yarn client or the npm client? What version?

Yarn 1.3.2 - npm 5.5.1

What version of Node.js are you using?

8.9.3

What operating system are you using?

Mac OSX

What did you do?

Installed the stylelint preset, added it to `.neutrinorc.js` file e.g. `use: [ ['neutrino-preset-stylelint] ]`

What did you expect to happen?

Stylelint would run on neutrino build command.

What actually happened, contrary to your expectations?

Received error

```Building project/Users/jamie.woolgar/dev/my-project/node_modules/webpack-chain/src/Plugin.js:9
    this.init((Plugin, args = []) => new Plugin(...args));
                                     ^

TypeError: undefined is not a function``

**Comment by timkelty** [comment]
@jamiedust I think you might be using the wrong package…

The core stylelint middlware was only introduced in Neutrino v8: https://github.com/mozilla-neutrino/neutrino-dev/blob/master/CHANGELOG.md#v810

The NPM package is `@neutrinojs/stylelint`, not `neutrino-preset-stylelint`.

**Comment by jamiedust** [comment]
You are correct, apologies.
