### ISSUE TITLE
Typo error in 'Create new project' page link

### ISSUE THREAD

**Issue by Nhiokh** [mozilla-neutrino/neutrino-dev#706]
Just a little typo error on the Customization part of the ['Create new projet'](https://neutrino.js.org/installation/create-new-project.html#customization) page.

Customization link is missing a backslash at the end of its url. :)

**Comment by apoorvaagupta** [comment]
Hey, can I solve this issue?

**Comment by edmorley** [comment]
@apoorvaagupta - certainly! :-)

**Comment by edmorley** [comment]
I ended up fixing this since it's been a few weeks since the above, and I happened to spot several more really bad broken links that needed fixing asap :-)
