### ISSUE TITLE
@neutrinojs/react: watch, and compile

### ISSUE THREAD

**Issue by MrSaints** [mozilla-neutrino/neutrino-dev#707]
From my understanding, with `@neutrinojs/react`, you can either `start`, `build` or `test`.

`start` will spin up a development server, while `build` will actually perform the compilation, and copying of `static` files. I am looking for an in-between. That is, I need to watch for changes, and build. The output does not have to be minified. The use-case here is that there are cases where we want to use `index.html` directly, e.g. when developing a Chrome extension. 

I was wondering if this is currently possible (does not seem like it)? Or does it require some hacking?

**Comment by eliperelman** [comment]
@MrSaints I believe you can do that if you use `start`, but clear out the devServer configuration:

```js
module.exports = {
  use: [
    '@neutrinojs/react',
    (neutrino) => {
      if (neutrino.options.command === 'start') {
        neutrino.config.devServer.clear();
      }
    }
  ]
};
```

**Comment by MrSaints** [comment]
I can confirm that does in fact work 👍 

Cheers!
