### ISSUE TITLE
Neutrino lint and ESLint return different results

### ISSUE THREAD

**Issue by gir** [mozilla-neutrino/neutrino-dev#708]
Hello,

I'm trying to figure out what's going on here and have been stuck. It seems that when running `neutrino lint` vs `eslint` directly, results differ.

I have created a minimal repro [here](https://github.com/gir/neutrino-lint-test). I am unsure if the problem is with the specific usage of Webpack module resolve (perhaps I use it incorrectly?), a neutrino setup oversight, or a bug. I have quickly tried to trace it through some of the Neutrino source, but don't see anything that jumps out. I also had a look at #380 and #382 but may have missed something.

Essentially I have added `src` as a module directory to the Webpack config so that I can do something like `import foo from 'foo'` (note not `'./foo'`). Then I add the directory to `import/resolver` through ESLint settings so the airbnb-configured `import/no-unresolved` should not fail.

`yarn lint` which runs `neutrino lint` returns errors.
`yarn eslint src --ext .js,.jsx` returns no errors.

I would expect the two runs to return the same results.

Versions:
```
neutrino v8.1.1
node v9.5.0
yarn v1.3.2

@neutrinojs/airbnb v8.1.1
@neutrinojs/jest v8.1.1
@neutrinojs/react v8.1.1
```

**Comment by yasinuslu** [comment]
I was having the same problem, i debugged neutrino with:
```
nodemon --inspect-brk ./node_modules/neutrino/bin/neutrino.js lint
```
Eslint somehow gets an eslint config with some of our configs overridden when neutrino sets `useEslintrc: false`

![image](https://user-images.githubusercontent.com/1007479/37583765-b769ec24-2b63-11e8-8123-30c0bc57e2d8.png)

I added `useEslintrc: true` to my eslint config and it's working now.
