### ISSUE TITLE
Babel preset/plugin customization is undocumented?

### ISSUE THREAD

**Issue by dbkaplun** [mozilla-neutrino/neutrino-dev#71]
I would like to use Radium with neutrino-dev but it seems like neutrino does not come with babel plugins for class decorators or properties as in Radium's [default usage](https://github.com/FormidableLabs/radium#usage). Is there any way to customize neutrino's babel configuration?

**Comment by eliperelman** [comment]
Yes, you can certainly enhance the Babel configuration, and the documentation is here: https://neutrino.js.org/customization/advanced.html

In your override file, you can start a modification with:

```js
module.exports = neutrino => {
  neutrino.config.module
    .rule('compile')
      .loader('babel', ({ options }) => {
        options.presets...
        options.plugins...

        return { options };
      });
};
```

Add this file to your preset list and you should be good to go.

**Comment by eliperelman** [comment]
Closing, and informed of documentation for overriding Babel configuration. Please re-open if something is insufficient for you. Thanks!
