### ISSUE TITLE
react-components preset should compile down to es5 by default

### ISSUE THREAD

**Issue by wlach** [mozilla-neutrino/neutrino-dev#722]
If we don't do this, the resulting minified js won't be useable by tools like create-react-app (see e.g. mozilla/react-metrics-graphics#18).

Current suggested workaround (could probably be used as a basis of a solution here):

https://github.com/eliperelman/react-fout-stager/blob/67b13f839701438334863f42b8c859595eb3bf6b/.neutrinorc.js#L13

**Comment by edmorley** [comment]
So IMO libraries like this should provide both an ES6 version (accessible via the `module` property in `package.json`) and an ES5 output.

That said, this really is the territory of rollup (see the vast majority of other libraries that produce multiple variants) - I wonder if it would be a better fit compared to Neutrino/webpack in these cases?

**Comment by eliperelman** [comment]
The superiority may be temporary, and for that reason I don't see why we need to recommend another tool. Documenting the tradeoffs may be good, but we should let users determine whether the tradeoffs warrant the use of another tool over the benefits of shared configuration.

**Comment by edmorley** [comment]
Fair point.

The problem at the moment is that there's no one maintaining the preset and it currently generates broken (by best practice standards) output. I don't use this preset or have time to look at it, so I don't see it getting fixed any time soon.

**Comment by eliperelman** [comment]
It's not necessarily broken, just that it doesn't work *everywhere*. If you generate a component, and you use that component in a Neutrino-based React project, it will work. It just doesn't work as-is in a CRA project.

I do use this, though, so I will fix it.

**Comment by edmorley** [comment]
Putting !ES5 content in `main` is broken TBH. It's not expected that everyone runs babel against `node_modules` (though I imagine in the future more and more people will be putting ES6 in `module` so everyone will have to include `node_modules` in babel-loader regardless).

**Comment by edmorley** [comment]
This doesn't block a Neutrino v9 alpha - however since it's a breaking change, someone would need to start working on this soon or else it's not going to make Neutrino 9 final, and would then have to wait until Neutrino 10.
