### ISSUE TITLE
how do I link a cdn stylesheet?

### ISSUE THREAD

**Issue by cultofmetatron** [mozilla-neutrino/neutrino-dev#728]
tryign to link to the stylesheets in https://material-ui-next.com/getting-started/installation/

here's my neutrino.js file

```
const template = require('@neutrinojs/html-template');

module.exports = {
  use: [
    '@neutrinojs/standardjs',
    
    [
      '@neutrinojs/react',
      {
        html: {
          title: 'slate-basic',
          
        }
      }
    ],
    ['@neutrinojs/html-template', {
      title: 'my React Application',
      link: [
        {
          rel: 'stylesheet',
          href: "https://fonts.googleapis.com/icon?family=Material+Icons"
        }
      ]
    }],
    '@neutrinojs/jest',
  ]
};

```

Doesn't work and there's nothing I've found in the docs on how to link to a cdn. Everythign I've found revolves around linking to a module. How do I add the style link to my head?

**Comment by eliperelman** [comment]
The `html` options for the `react` preset are driven via [html-webpack-template](https://github.com/jaketrent/html-webpack-template), which accepts a `links` array. You should be able to specify it like:

```js
module.exports = {
  use: [
    '@neutrinojs/standardjs',
    ['@neutrinojs/react', {
      html: {
        title: 'slate-basic',
        links: [
          {
            href: 'https://fonts.googleapis.com/icon?family=Material+Icons',
            rel: 'stylesheet'
          }
        ]
      }
    }],
    '@neutrinojs/jest',
  ]
};
```

Give that a shot and let me know!

**Comment by cultofmetatron** [comment]
haha YES it worked. omg my blind guess was off by a single character 📦 
Thanks!

**Comment by eliperelman** [comment]
Great! Good luck! 👏

**Comment by edmorley** [comment]
(Answered in #1134 :-))
