### ISSUE TITLE
Consider switching from extract-text-webpack-plugin to mini-css-extract-plugin

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#735]
There is a new webpack 4 only plugin for extracting CSS:
https://github.com/webpack-contrib/mini-css-extract-plugin

Once we've updated to webpack 4, it looks like it might be worth switching to it.

**Comment by eliperelman** [comment]
I think it was in beta, but yeah, if it's usable when we switch, I agree.

**Comment by edmorley** [comment]
Fixed by #809.
