### ISSUE TITLE
--watch isn't being handled by the mocha preset

### ISSUE THREAD

**Issue by armenzg** [mozilla-neutrino/neutrino-dev#736]
I'm currently using "./node_modules/mocha/bin/mocha ./test/**/*.test.js --watch" instead of "neutrino test ./test/**/*.test.js --watch".

Preset referred:
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/mocha/src/mocha.js

**Comment by edmorley** [comment]
Hi!

The `--watch` option is recognised by `neutrino test`, which passes it down to whatever registered the `test` command. For the karma preset this is then passed onto the test runner like so:
https://github.com/mozilla-neutrino/neutrino-dev/blob/8b03d8bd21b707f711ea6931f30c8016513e34db/packages/karma/index.js#L55-L60

Would you be up for making a similar change to the mocha preset? :-)
https://github.com/mozilla-neutrino/neutrino-dev/blob/8b03d8bd21b707f711ea6931f30c8016513e34db/packages/mocha/src/index.js#L7

**Comment by armenzg** [comment]
I've managed to see this move forward, however, mocha runs once and then it runs once more (upon file changes) with 0 passing tests [1]

Further file changes do not change the output. The script seems to always be watching.

[1]
> 
>   getChromePopular
>     ✓ should return an array (10111ms)
> 
> 
>   11 passing (17s)
> 
>   0 passing (0ms)

The mocha code being reached is this:
https://github.com/mochajs/mocha/blob/50aec7a249c7b2a28e2fdc18058829f48e6ee6d6/bin/_mocha#L523-L577

**Comment by armenzg** [comment]
Here's the neutrino-dev changes:
https://github.com/mozilla-neutrino/neutrino-dev/compare/master...armenzg:watch

The project I'm trying to make watching work for is:
https://github.com/mozilla/firefox-health-backend

The "watch:test" script requires changing "mocha" for "neutrino test"
https://github.com/mozilla/firefox-health-backend/blob/master/package.json#L8

**Comment by markoshust** [comment]
i believe this issue should be reopened, `--watch` isn't working with mocha for me. the tests just run once and stop as if `--watch` isn't even being seen.

**Comment by markoshust** [comment]
I didn't know there was a new version of Neutrino coming out.... sounds great! :)
