### ISSUE TITLE
Setting app's mount id to be something else than "root"

### ISSUE THREAD

**Issue by atoiv** [mozilla-neutrino/neutrino-dev#74]
Would it be possible to allow setting (react) app's mount id to be something else than "root"?

It seems `appMountId` is currently set as part of the `html-webpack-plugin` initialization in `neutrino-preset-web`, but it is hard coded to "root".

Now, I've created a [custom config](https://neutrino.js.org/customization/advanced.html) for altering the value, which seems to do the trick, but feels somewhat error prone, as it relies on `neutrino-preset-web` using a specific html template:

```javascript
// custom-config.js
'use strict';

const appMountId = 'custom-project-id';

module.exports = neutrino => {
  neutrino.config.plugin('html').args[0].appMountId = appMountId;
}
```

Would it be possible to set the value in some predefined way, possibly as:

1) env variable,
2) preset option,
3) general neutrino conf option,
4) some other way.

Hard coded `id` for a project is probably valid for modern SPA's, but there's a plenty of legacy and other reasons for needing it to be able to be changed per project, such as:

1) need for mounting multiple different projects on the same page,
2) not being able to use the id "root" on target page.

**Comment by eliperelman** [comment]
Changing the options that go to html-webpack-plugin is documented here:

https://neutrino.js.org/presets/neutrino-preset-web/#html-files

Essentially, at the moment this can only be overridden in package.json via `config.html`, and can't be overridden via an override file due to #23. To change the app mount ID:

```json
{
  "config": {
    "html": {
      "appMountId": "custom-project-id"
    }
  }
}
```

We can't fix #23 until we are ready to go to v5, since this is a breaking change.

**Comment by atoiv** [comment]
Sorry, found [documentation](https://neutrino.js.org/presets/neutrino-preset-web/#html-files) for this after creating the issue.

**Comment by eliperelman** [comment]
@atoiv no worries! Hope you find it helpful, and that we can fix these soon.

**Comment by atoiv** [comment]
@eliperelman Definitely! This project is awesome. Thanks for the great work!

And thanks for the fast reply.
