### ISSUE TITLE
Where to put created presets?

### ISSUE THREAD

**Issue by SpencerCDixon** [mozilla-neutrino/neutrino-dev#75]
Love this project!  [I created a simple neutrino preset for applying Prettier code formatting.](https://github.com/SpencerCDixon/neutrino-preset-prettier)  I was wondering if there was a section in the docs or readme you were going to include all 3rd party neutrino presets for people to find?

**Comment by tj** [comment]
Hmm maybe wiki + "neutrino-preset" GH topic would be good, looks like the wiki isn't enabled or something though

**Comment by SpencerCDixon** [comment]
Wiki sounds good to me! Whatever core contributors think is appropriate. Having all presets in one place and organized by type (I.e testing, formatting, etc.) will definitely help with adoption and less people rebuilding the same presets.

**Comment by eliperelman** [comment]
Yeah, I've been thinking about this as well, although I'm not sure the right direction. I like the wiki idea so anyone can drive-by their preset, the con being that there's 2 different places where things are documented. I could also add some sort of XHR call to npm and list out packages with the `neutrino-preset` keyword, and put it on the docs too, the pro being that new presets can be picked up automatically.

**Comment by tj** [comment]
I guess both assume that people will either add a keyword, or add it to the wiki. People seem pretty good with adding to a wiki though: https://github.com/koajs/koa/wiki, kinda nice to categorize as well.

**Comment by SpencerCDixon** [comment]
Why not both?  Seems like doing the XHR call on the docs to grab all with the proper prefix provides big bang for your buck.  Then maybe adding a note in the 'Creating Presets' section to either make sure to name presets with proper prefix and/or add to the proper category in the wiki.

**Comment by eliperelman** [comment]
Doing both is an option, it just takes work to implement. I have something that works, but I'd prefer not to land it as complete garbage. :laughing:

In the meantime, I'll at least get a wiki page going. I'll take care of that tomorrow.

**Comment by eliperelman** [comment]
I whipped up a gitbook plugin for embedding an npm search into a gitbook:

https://github.com/eliperelman/gitbook-plugin-npmsearchlist

I'll add this page to the docs shortly, then open up the wiki.

**Comment by eliperelman** [comment]
Live! https://neutrino.js.org/presets/community-presets.html

**Comment by eliperelman** [comment]
Wiki preset page at https://github.com/mozilla-neutrino/neutrino-dev/wiki/Community-Presets

**Comment by jefffriesen** [comment]
I'm not sure this npmsearchlist is working correctly. I published two presets yesterday and they don't show up in the [community presets](https://neutrino.js.org/presets/community-presets.html) section. 

https://www.npmjs.com/package/neutrino-preset-class-properties
https://www.npmjs.com/package/neutrino-preset-decorators

A preset by someone else was published 6 days ago: 
https://www.npmjs.com/package/jke-neutrino-preset-react-mobx 
and it also doesn't show up in that list.

All have `neutrino-preset` in the npm name and keywords.

**Comment by eliperelman** [comment]
Very strange, when using the API directly, I only get those 11 results:

https://api.npms.io/v2/search?q=keywords:neutrino-preset+not:deprecated&size=100

But clearly there are more. Not sure what is going on yet.

**Comment by eliperelman** [comment]
Looks like the presets are showing up now. Not sure what is up with the npms.io API, but maybe it is cached for some duration.

**Comment by jefffriesen** [comment]
Yep, I see the the ones I mentioned and more.
