### ISSUE TITLE
Options for Loader Merge Middleware

### ISSUE THREAD

**Issue by Graf009** [mozilla-neutrino/neutrino-dev#750]
Hello. When working with the loader-merge, the problem appears when working with the babel config, you can make an option where you can redefine the merge function, for example,  the babel-merge?
I can do PR.

**Comment by edmorley** [comment]
@Graf009, I don't suppose you saw the above? :-)

**Comment by Graf009** [comment]
@edmorley Hello, I'm on vacation with bad Internet, I'll write on arrival

**Comment by edmorley** [comment]
@Graf009 Enjoy your vacation - it can wait! :-)

**Comment by edmorley** [comment]
Closing for now - happy to reopen once some further details given :-)
