### ISSUE TITLE
lint-staged breaks partial staging of changes

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#756]
A common workflow when I'm developing is to make a handful of changes, then afterwards stage a subset of those changes, make a new commit, stage some more, commit some more etc.

Unfortunately the use of lint-staged means that if only a few of the changes in a file were staged, then after committing all other changes end up being staged (due to the `git add`), breaking my workflow.

In addition, running the commit hooks takes 5-10 seconds which wears thin pretty fast.

Does anyone have any ideas, other than just disabling lint-staged?

**Comment by edmorley** [comment]
It looks like there isn't a decent solution: okonet/lint-staged#366

**Comment by eliperelman** [comment]
I've dealt with this exact issue in taskcluster-tools:

https://github.com/taskcluster/taskcluster-tools/pull/414

In the end, I still think it's useful for running a lint precommit, but it shouldn't do a fix, and it shouldn't also do `git add`. What are your thoughts? Are we running `git commit` frequently enough where the tradeoff isn't worth the branch protection?

Worst case scenario, you can skip the check manually if you like with `git commit --no-verify`.

**Comment by edmorley** [comment]
Linting without the fix/git add sounds fine. That would at least prevent having my nicely staged commits ruined for the third time this evening (since my success rate for remembering to disable the hooks each time has been low) hehe.

I'll open a PR.
