### ISSUE TITLE
gh-pages deploy failed

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#761]
I just tried to update the docs by running `yarn docs:deploy`.

This resulted in the following new commit:
https://github.com/mozilla-neutrino/neutrino-dev/commit/283141654a49255243718b0cfe5a1fedd877aae1

...which has the `.md` source files present, and not just the `.html` built output.

This then results in a build error email from GitHub:
```
The page build failed for the `gh-pages` branch with the following error:

The tag `npmsearchlist` on line 25 in `middleware/community-middleware.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
```

I've tried twice and the same thing happens. 

Perhaps it's a gitbook bug with source file cleanup that only shows on Windows?
@eliperelman could you try running `yarn docs:deploy` and seeing if it works for you?

**Comment by eliperelman** [comment]
It succeeded for me :(

**Comment by edmorley** [comment]
I guess next time I'll just have to run the steps individually and delete the source files manually.
Perhaps after we update to the new gitbook (or whatever direction we go), if it's still buggy I can dig in more.

**Comment by edmorley** [comment]
Thank you for updating the docs though! :-)
