### ISSUE TITLE
@neutrinojs/eslint doesn't play well with Vue out of the box

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#763]
With a config like this:

```
    neutrino.use('@neutrinojs/vue');
    neutrino.use('@neutrinojs/eslint', {
      eslint: {
        baseConfig: {
          extends: [
            'plugin:vue/recommended',
          ],
        }
      }
    });
```

You will get errors like this:

```
error: Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error (vue/no-multi-spaces) at src/vue/portal.js:1:1:
> 1 | import Vue from 'vue';
    | ^
  2 | import App from './App.vue';
  3 |
  4 | new Vue({
```

If you follow that link and follow the instruction, you can get it to work by moving the `parser` option:

```
    neutrino.use('@neutrinojs/eslint', {
      eslint: {
        parserOptions: {
          parser: 'babel-eslint',
        },
        baseConfig: {
          extends: [
            'plugin:vue/recommended',
          ],
        }
      }
    });
```

Not sure if this is something we should do for the user behind the scenes in `@neutrinojs/eslint`, but at the very least it should be in the docs.

**Comment by eliperelman** [comment]
https://github.com/mozilla-neutrino/neutrino-dev/blob/323abe846a2ecc647627d9b6459a62b41385249e/packages/vue/index.js#L36-L38

**Comment by timkelty** [comment]
@eliperelman ah-hah - that only works if `@neutrinojs/eslint` comes _first_.

**Comment by eliperelman** [comment]
Yep, since it's extending from the eslint middleware. We used to have something in the docs about linting middleware should come before build middleware...

**Comment by eliperelman** [comment]
So one thing that sucks right now is any logging done from middleware interacts with the spinners. Maybe we should add something like `neutrino.log`, which pauses the spinners, logs the message, and starts them back up? This would require giving Neutrino knowledge of a spinner instance.

**Comment by edmorley** [comment]
Ah true. Though perhaps in this case throwing might be more appropriate than a log message?

**Comment by edmorley** [comment]
As far as I understand, this issue was due to the vue preset being before the lint preset in `.neutrinorc.js`, and reordering fixed it. I've opened #800 for adding a warning if the preset order is incorrect, so I think we can close this issue out :-)

**Comment by edmorley** [comment]
In Neutrino 9, the inverted ordering here will result in an error message explaining that lint presets need to come first (#939), hopefully preventing others from hitting this.
