### ISSUE TITLE
Add issue template plus .github folder

### ISSUE THREAD

**Issue by spadesr** [mozilla-neutrino/neutrino-dev#772]
# Why?
To stimulate issue makers to add the right information immediately when filing an issue. This avoids unnecessary back-and-forths where maintainers need to ask for more details (ie version numbers). 
It's very helpful to have links to documents describing how to contribute. Unfortunately, not everybody reads through these documents before submitting an issue.

# How?
I propose to add an issue template (using existing questions) and move all Github related docs to a `.github` folder. Also, while doing this, I propose to add a `SUPPORT.md` file. That's currently missing. It would allow issue contributors to quickly go to the place to get support via the _Helpful resources_ tab. Lastly, moving everything to a `.github` (including `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`) folder would clean up the root dir a bit, after the aforementioned changes.

### The changes in short
- Add `ISSUE_TEMPLATE.md`.
- Add `SUPPORT.md`.
- Move `ISSUE_TEMPLATE.md`, `SUPPORT.md`, `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` to `.github` folder.

# Example
Before:
![Before change](https://cdn.pbrd.co/images/HdQyzkp.png)

After:
![After change](https://cdn.pbrd.co/images/HdQyMij.png)

Since these are small changes, I created a fork to show what I mean: https://github.com/spadesr/neutrino-dev/tree/github-documentation-and-templates. I'd be happy to make adjustments and submit a PR if you like the suggestion.

This is also one of my first enhancement suggestions to a project. Any feedback on how I'm suggesting this is appreciated :-).

Thoughts?

**Comment by eliperelman** [comment]
I really like this idea! Feel free to open a PR to move forward with this.

**Comment by edmorley** [comment]
Fixed by #774
