### ISSUE TITLE
.neutrinorc.js file clobbers --use option

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#773]
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/neutrino/bin/neutrino.js#L88-L89

Was attempting this (with a different `.neutrinorc.js` in cwd: `neutrino build --use .neutrinorc-vue.js`

Config from `.neutrinorc.js` is used when it should be ignored (because of `--use`).

**Comment by eliperelman** [comment]
Confirmed.
