### ISSUE TITLE
Consider changing "official/example" middleware format from array to fn

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#779]
`yarn create @neutrinojs/project` gives you something like this:

```
module.exports = {
  use: [
    '@neutrinojs/airbnb',
    [
      '@neutrinojs/react',
      {
        html: {
          title: 'foo'
        }
      }
    ],
    '@neutrinojs/jest'
  ]
};
```

Personally I always avoid the array middleware format, as I find it hard to read. I've seen quite a few people mess it up as well.

I always change it to this:

```
module.exports = {
  use: [
    '@neutrinojs/airbnb',
    neutrino => neutrino.use('@neutrinojs/react', {
      html: {
        title: 'foo'
      }
    }),
    '@neutrinojs/jest'
  ]
};
```

Anyone else?

**Comment by timkelty** [comment]
k, we'll just leave it then 👍

**Comment by eliperelman** [comment]
Haha ok. One pro for using the array format is its familiarity to Babel users, who also share the string and array pair formats.

**Comment by timkelty** [comment]
True. Think its just a silly preference I have, just wanted to make sure it wasn't universal.
