### ISSUE TITLE
@neutrinojs/library - compile to standard ES5

### ISSUE THREAD

**Issue by flash1293** [mozilla-neutrino/neutrino-dev#781]
IMHO the library preset should configure babel to compile to standard ES5 to be consumable by uglify, incuding async/await and other language features.

**Comment by eliperelman** [comment]
I think this is reasonable, and I am thinking the same thing about react-components as well so they play well with CRA by default. The tradeoff here comes with the size expense.

@mozilla-neutrino/core-contributors thoughts?

**Comment by edmorley** [comment]
Or ideally compile to both - one for the project's `main` and the other for `module`.

**Comment by eliperelman** [comment]
See also #722.

**Comment by edmorley** [comment]
This doesn't block a Neutrino v9 alpha - however since it's a breaking change, someone would need to start working on this soon or else it's not going to make Neutrino 9 final, and would then have to wait until Neutrino 10.
