### ISSUE TITLE
Bug: app using react preset does not run in Firefox

### ISSUE THREAD

**Issue by madox2** [mozilla-neutrino/neutrino-dev#785]
I am getting error in Firefox when using react preset. Application is succesfully started at `localhost:5000`. In browser's JS console I can see:

```
TypeError: Set is not a constructor
```

when I look at the Set built-in in the console: `typeof Set` it is equal to `undefined`.

However it works fine in Google Chrome.

my `.neutrinorc.js` is:

```js
module.exports = {
  use: [ '@neutrinojs/react' ],
}

```

neutrino@8.2.2
node@9.5.0
using yarn
Firefox 59.0.2
Ubuntu 16.04

**Comment by eliperelman** [comment]
Hmm, that's very odd. I am using Set in a React codebase and I don't experience this. What's more, Set has been in Firefox since FF13, so it should definitely be there. Do you have a simple test repo I can reproduce against? Are you sure that you haven't overridden Set, or used a polyfill which does so?

**Comment by madox2** [comment]
I generated clean project using `yarn create @neutrinojs/project myProject` (choosing react, airbnb and jest) and then I ran `yarn start`. That is all I did. It is quite strange while `Set` exists in other Firefox's window/tabs. It is missing only in the window with the neutrino application. It looks that something is overriding this built-in.

**Comment by eliperelman** [comment]
Hmm, I still am not able to replicate. I fired up my Ubuntu 16.04 machine, used React, Jest, and Airbnb, started the project with latest yarn, Node.js 8.6, FF 59, and it launched fine with no Set errors.

Do you have any extensions installed that may be messing with it? Could you try opening the page in a private window?

**Comment by madox2** [comment]
My mistake, I had an old service worker registered on `localhost:5000` which did some weird things.
Sorry for confusing issue and thanks the support!
