### ISSUE TITLE
font-loader not working in production?

### ISSUE THREAD

**Issue by markerikson** [mozilla-neutrino/neutrino-dev#786]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using? 
8.1.2

- Are you trying to use any presets? If so, which ones, and what versions? 
web and React, also 8.1.2

- Are you using the Yarn client or the npm client? What version? 
Yarn, 1.3

- What version of Node.js are you using?
 9.2.0

- What operating system are you using? 
Windows 10

- What did you do?
I'm building a slideset using the Spectacle toolkit.  Its default styles use the Montserrat typeface, and I've copied the files from the `typeface-montserrat` package into my project to simplify setup.  I also have a couple other fonts I'm trying to use.  The fonts load fine in development.  However, when I do a prod build, they're processed and written out to disk by `font-loader`, but not loaded into the app.  I can't find any evidence of the font-face declarations in the built CSS, anywhere.

- What did you expect to happen?

I expected the font declarations to be in the CSS, and the browser to actually load the fonts.

I've tried shuffling around where I'm importing the CSS file with the font declarations, and I'm seeing the same behavior even if I move the font declarations to a different CSS file.  All my other CSS shows up in the output CSS files, but no font declarations.

**Comment by eliperelman** [comment]
Could you provide a test project to reproduce this one on?

**Comment by markerikson** [comment]
@eliperelman : done - see https://github.com/markerikson/neutrino-fontloader-issue .

The slide text is correctly rendered using the Montserrat font in development, but not in production, and I see no evidence that the page is trying to load the font files in prod.

**Comment by markerikson** [comment]
Yep, that appears to be it.  Got it working now.  Thanks!
