### ISSUE TITLE
Enable the new eslint-plugin-babel 'babel/quotes' rule

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#788]
`eslint-plugin-babel` v5 (which we updated to in #780) added a new `babel/quotes` rule, that we presumably will want to enable.

> `babel/quotes`: doesn't complain about JSX fragment shorthand syntax (`<>foo</>;`)

https://github.com/babel/eslint-plugin-babel#rules

**Comment by patiboh** [comment]
Hi, I'll be happy to do this. This should be enabled in `.neutrinorc.js`, am I correct?

**Comment by edmorley** [comment]
Hi! 

The rule would need to be added here:
https://github.com/mozilla-neutrino/neutrino-dev/blob/master/packages/airbnb/index.js

**Comment by patiboh** [comment]
Thanks, I’m relatively new at this :)
I’ve read the project’s development process, I’ve done the modification on my branch and ran `yarn validate:eslintrc` as well as `yarn test`. Is that sufficient testing for submitting my PR?

**Comment by eliperelman** [comment]
@patiboh yes, feel free to submit!

**Comment by edmorley** [comment]
Fixed by #874.
