### ISSUE TITLE
How to disable eslint output in browser console

### ISSUE THREAD

**Issue by madox2** [mozilla-neutrino/neutrino-dev#797]
This is more question like issue. When I run project in dev mode and I have linting error, it is also printed to the browser's console as error. When I want to quickly debug app there is too much unnecessary output in the console. Furthermore it also prevents HMR to reload.

Is it possible to disable this behavior?

**Comment by edmorley** [comment]
Hi! From googling now it seems that this is currently not possible - and would require webpack-dev-tools (or more likely its replacement, [webpack-serve](https://github.com/webpack-contrib/webpack-serve)) to provide an option to only display build errors in the (shell) console and not the browser console. See:
webpack/webpack#5441
webpack/webpack-dev-server#977

**Comment by madox2** [comment]
I've found out that it is possible to turn off browser's logs by setting:

```
devServer: {
  clientLogLevel: 'none',
}
```

However HMR is still not working if there are linting errors.

**Comment by eliperelman** [comment]
@madox2 nice find!

Regarding the re-build of linting failures, @edmorley is correct in that this is something from webpack. Fortunately, there is a workaround through the eslint middleware, by setting `emitWarning` to `true` during development. For example, if you are using the airbnb middleware:

```js
module.exports = {
  use: [
    ['@neutrinojs/airbnb', {
      eslint: {
        emitWarning: process.env.NODE_ENV === 'development',
      },
    }],
  ],
};
```

See the Spectrum thread as well: https://spectrum.chat/thread/3fc28afb-95b6-47a7-b9d3-af14af0256b6

**Comment by madox2** [comment]
@eliperelman works well, thank you!
