### ISSUE TITLE
Make lint preset throw if included after other presets

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#800]
As seen in #763 and elsewhere, if the linter presets are included after the other presets, then they don't work as expected.

To help make this case more obvious to users, it seems to make sense for the lint presets to throw if not declared first. eg in eslint preset: 
```js
if neutrino.config.module.rules.has('compile') {
  throw new Error('Linter presets must be declared before any other presets.');
}

**Comment by eliperelman** [comment]
We would also need to make sure that another instance hasn't already been set:

```js
if (
  neutrino.config.module.rules.has('compile') &&
  !neutrino.config.module.rules.has('lint')
) {
```

**Comment by edmorley** [comment]
You mean in case people do something like this?
```js
  use: [
    '@neutrinojs/airbnb',
    '@neutrinojs/react',
    '@neutrinojs/standardjs',
]
```

If so, I don't think that is a case we should worry about supporting. In the unlikely event they are using multiple '@neutrinojs/*` lint presets, they should just list them all at the start.
