### ISSUE TITLE
Remove Hot Module Replacement

### ISSUE THREAD

**Issue by fredguest** [mozilla-neutrino/neutrino-dev#81]
It's unclear to me from the customization section of the docs how to remove Hot Module Replacement from`neutrino-preset-web` or React Hot Loader from `neutrino-preset-react`. @eliperelman could you provide an example?

**Comment by eliperelman** [comment]
To shut off HMR, I suppose you could do the following:

```js
config.entry.delete('webpack/hot/dev-server');
config.plugins.delete('hot');
config.devServer.hot(false);
```

It's not documented anywhere, but I suppose that might be something useful to add to the docs.

**Comment by fredguest** [comment]
I see, thanks for the help! So there's no way to accomplish this via `package.json` configs correct?

**Comment by eliperelman** [comment]
Correct, removing based on directives would make things much more difficult. The only setting you can change from JSON would be setting the dev server hot to false:

```js
{
  "config": {
    "neutrino": {
      "devServer": {
        "hot": false
      }
    }
  }
}
```

**Comment by fredguest** [comment]
Ok cool, the JavaScript solution should be fine then, thanks again!
