### ISSUE TITLE
Remove all spectrum badges from READMEs

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#828]
With our docs mostly moved to hosted GitHub, there is now a permanent link to Spectrum support at the top. We can remove the links from needing to be on all READMEs now.

**Comment by eliperelman** [comment]
@ericp3reira absolutely!

**Comment by ericp3reira** [comment]
@eliperelman Thanks for the opportunity! Here is the [PR](https://github.com/mozilla-neutrino/neutrino-dev/pull/840). :smiley:

**Comment by eliperelman** [comment]
Fixed by #840.
