### ISSUE TITLE
Unable to run 'yarn run lint --fix` 

### ISSUE THREAD

**Issue by mrwillis** [mozilla-neutrino/neutrino-dev#832]
### Bug or issue?

Please try to answer the following questions:

- What version of Neutrino are you using? 8.2.3
- Are you trying to use any presets? If so, which ones, and what versions?     ```"@neutrinojs/airbnb": "^8.2.3",
    "@neutrinojs/react": "^8.2.3",```
- Are you using the Yarn client or the npm client? What version? yarn @ 1.6.0 
- What version of Node.js are you using? v8.11.1
- What operating system are you using? Ubuntu 16
- What did you do? Ran `yarn run lint --fix`
- What did you expect to happen? For neutrino to try to lint and fix my files
- What actually happened, contrary to your expectations? 

```
julian@wilson:~/cika-client$ yarn run lint
yarn run v1.6.0
$ neutrino lint
⠋ Running lint/home/julian/cika-client/node_modules/neutrino/bin/execute.js:23
        throw new Error(`A command with the name "${commandName}" was not registered`);
        ^

Error: A command with the name "lint" was not registered
    at Object.commandHandler [as lint-cli] (/home/julian/cika-client/node_modules/neutrino/bin/execute.js:23:15)
    at ChainAction.Future.chain.chain.chain [as mapper] (/home/julian/cika-client/node_modules/neutrino/src/api.js:281:48)
    at ChainAction$resolved [as resolved] (/home/julian/cika-client/node_modules/fluture/index.js:807:27)
    at resolved (/home/julian/cika-client/node_modules/fluture/index.js:220:19)
    at Immediate.EncaseP2$res [as _onImmediate] (/home/julian/cika-client/node_modules/fluture/index.js:1849:7)
    at runCallback (timers.js:796:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is straight out of the box with the specified presets. `yarn run build` and `yarn run start` work fine!

### Feature request or enhancement?

Please describe your request in detail. Use the following questions as guidance: 

- What is the goal of the change?
- What are the pros and cons of the change?
- Could this dramatically improve the experience of our users?

**Comment by edmorley** [comment]
Hi! Could you paste the contents of your `.neutrinorc.js`? (One possibility is that `@neutrinojs/airbnb` is missing from there)

**Comment by constgen** [comment]
I believe when you use yarn you should pass flags as `yarn lint -- --fix` and without 'run'

**Comment by edmorley** [comment]
@constgen `yarn run lint` and `yarn lint` are equivalent, and the `--` is not needed for yarn 1.0+ (Neutrino requires 1.2.1+) - and in fact generates a warning:
```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded.
In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

This is likely a case of the airbnb preset not being loaded for whatever reason.

@mrwillis could you paste the contents of your `.neutrinorc.js`? :-)

**Comment by mrwillis** [comment]
Hi guys,

Sorry was a bit busy with stuff. My `.neutrinorc.js` looked something like this

```js
  env: {
    NODE_ENV: {
      development: {
        use: [
          (neutrino) => ...use airbnb plugin...
        ]
      }
    }
  }
```

I'm guessing this was the issue as it was only enabled during dev. Maybe add a warning to the docs? I've dumped the airbnb preset for now unfortunately as it was tough to integrate with IDEs

**Comment by eliperelman** [comment]
Yes, that would have been the problem as the lint command tries to run in production, not development, which would have found the command to be missing.

I'd be interested in hearing which IDE you had difficulty integrating the Airbnb preset with and had troubles.

**Comment by edmorley** [comment]
@eliperelman so it appears the confusing UX here is that the lint command is run with `NODE_ENV: 'production'`, since any custom command (that's not `start` / `build` / `test`) uses the `execute` handler, which defaults it to `'production'`.

So a few questions:
1) What should the default `NODE_ENV` be for custom commands? (Maybe the API should make people set it explicitly to avoid issues like this?)
2) Should the eslint preset's lint command override whatever default is chosen for (1)? 
3) Should the lint command become it's own official command?

Regardless of any code changes, we should probably also:
* Document default NODE_ENV on https://neutrino.js.org/cli/#custom-commands
* Adjust the error message seen above from `Error: A command with the name "lint" was not registered` to something that suggest users check for missing presets
