### ISSUE TITLE
Vue preset's babel-preset-vue dependency is unused

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#836]
The vue preset has a dependency on [babel-preset-vue](https://github.com/vuejs/babel-preset-vue):
https://github.com/mozilla-neutrino/neutrino-dev/blob/6dee32757ee93ec1541124acd59b3c990f5ea853/packages/vue/package.json#L26

However as far as I can tell it's not actually being used:
https://github.com/mozilla-neutrino/neutrino-dev/blob/6dee32757ee93ec1541124acd59b3c990f5ea853/packages/vue/index.js#L11-L27

Should it be removed, or are we meant to be using it?

@helfi92, any ideas?

**Comment by edmorley** [comment]
@helfi92 as the creator of this preset, do you have any ideas? :-)

**Comment by helfi92** [comment]
I believe it can be deleted. PR on the way.
