### ISSUE TITLE
`options.env` does not set `process.env` values

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#839]
Bug / `neutrino@8.1.2`

`options.env` is supposed to set environment variables (process.env), but it does not.

It correctly merges default cli options with passed options, but since the `process.env` vals are only set in the constructor ([via `getOptions`](https://github.com/mozilla-neutrino/neutrino-dev/blob/cc412d0c18dbaa66bceb011ed2f4185b2dbad8d2/packages/neutrino/src/api.js#L22)), they only ever get set once with the default cli options.

**Comment by eliperelman** [comment]
@ericp3reira sure thing! Ping me if you need any guidance. You'll need to look at the `mergeOptions` method in the API, linked from the description.
