### ISSUE TITLE
Check uses of [hash] vs [chunkhash] vs [contenthash]

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#844]
Apparently in many cases `[contenthash]` is preferred for production filenames, since it's less likely to change due to eg the CSS that was extracted. A quick ripgrep of the repo shows we're mostly using `[contenthash]`, but there are instances left of both `[hash]` and `[chunkhash]` that may or may not be correct.

The webpack docs are due to be updated to be clearer in webpack/webpack.js.org#2096 - once that's fixed we should re-evaluate what we're using where. (And ideally before Neutrino v9 final release, so we don't cause hash churn once out of beta.)

**Comment by eliperelman** [comment]
Agreed, it has to be done before v9 since any change in a hash is a breaking change.

**Comment by edmorley** [comment]
So the Neutrino web preset `config.output.filename` and `config.output.chunkFilename` values for production include the legacy `[chunkhash]` which means that the hashes currently change in cases when they shouldn't (eg CSS only changes cause the JS bundle hash to change too).

I have a local branch that fixes this.
