### ISSUE TITLE
Document that adding webpack to package.json is not recommended

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#849]
In #830 a Neutrino v8 project had a direct dependency on `webpack` v4, which caused confusing errors, since the `neutrino build` ended up using a combination of webpack 3 from `node_modules/neutrino/node_modules/webpack/` and webpack 4 from `node_modules/webpack/`.

Now this top-level webpack dependency was being used in `.neutrinorc.js`, so I don't think this issue would have been helped by adjusting the modules resolution order (ie #822).

Instead we should document that:
* in general, only neutrino packages should be added to a project's `package.json` (unless directly required in `.neutrinorc.js`)
* in cases where it is required, care must be taken to keep these in sync with the versions used in Neutrino

CC @mrwillis.

**Comment by eliperelman** [comment]
May be negated by #852.
