### ISSUE TITLE
How to test presets?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [mozilla-neutrino/neutrino-dev#854]
Hi,
I'm trying to create a new preset and cannot find good example of how to test one. Is there a good example of integration tests with neutrino to check that created config is good?

**Comment by eliperelman** [comment]
See https://github.com/mozilla-neutrino/neutrino-dev/issues/285#issuecomment-311201082. Each middleware in this project creates an instance of the Neutrino API, and attempts to require the middleware, have Neutrino `use` it, and then output a valid webpack configuration. Anything more than that would require doing something like create-project does, with integration tests:

https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/create-project/test

**Comment by Maxim-Filimonov** [comment]
Hm... sounds like a missing testing guide, PR ?

**Comment by eliperelman** [comment]
We are always happy to accept any PR. 😄
