### ISSUE TITLE
CSS + SASS

### ISSUE THREAD

**Issue by ovidius72** [mozilla-neutrino/neutrino-dev#871]
I would like to use sass with sass-loader but I also need to import a css file.
The index.js file has the following imports

import './path/to/file.css'
import './path/to/file.sass'

It's a react application so in the neutrino/react configuration I have:
```
style: {
    moduleTest: /\.module\.sass$/,
    test: /\.sass$/,
    loaders: [{
      loader: 'sass-loader'
      userId: 'sass'
    }]
```

After this I'm able to import .sass files but not css ones.
How can I have the sass-loader and still be able to import css files.
Thx

**Comment by eliperelman** [comment]
You should be able to follow a similar pattern as the one for LESS:

https://spectrum.chat/?t=a60e9355-9e30-4ba5-af0b-36ed8a40eda3

**Comment by ovidius72** [comment]
@eliperelman Thanks for you help.
The solution was to add also css to the sass-loader, like so:
```
 style: {
          loaders: [
            { loader: 'sass-loader', userId: 'sass' },
          ],
          test: /\.(css|sass)$/,
          moduleTest: /\.module.(css|sass)$/
        },
```

**Comment by constgen** [comment]
Have implemented Sass and Less middlewares recently that excellently integrate with core `style-loader` 
- https://github.com/constgen/neutrino-middleware-sass-loader
- https://github.com/constgen/neutrino-middleware-less-loader
