### ISSUE TITLE
Add an option to image-loader to bypass url-loader

### ISSUE THREAD

**Issue by timkelty** [mozilla-neutrino/neutrino-dev#901]
Using url-loader may not always be ideal, as file-loader would leverage browser caching.

You can get around this by passing `limit: 1` in the options, but it might be nice to have an option to explicitly use file-loader over url-loader.

**Comment by timkelty** [comment]
I take it back, `limit:1` is pretty damn easy, and explicit.

**Comment by edmorley** [comment]
`limit: 0` should work too:
https://github.com/webpack-contrib/url-loader/blob/v1.0.1/src/options.json#L5
https://github.com/webpack-contrib/url-loader/blob/v1.0.1/src/index.js#L32
