### ISSUE TITLE
Compile issue with node_modules in parent folder (e.g. Lerna bootstrap --hoist or yarn workspaces)

### ISSUE THREAD

**Issue by MatejMazur** [mozilla-neutrino/neutrino-dev#921]
### Bug

Please try to answer the following questions:

- What version of Neutrino are you using?
8.2.3
- Are you trying to use any presets? If so, which ones, and what versions?
`@neutrinojs/react-components` (8.2.3)
- Are you using the Yarn client or the npm client? What version?
Yarn 1.7.0.
- What version of Node.js are you using?
8.9.1
- What operating system are you using?
Windows 10
- What did you do?
I created monorepo with Lerna (Yarn workspaces enabled). One of packages is focused on react components so I added into the coresponding `package.json` devDependencies: `neutrino`, `@neutrinojs/react-components`, `react` and `react-dom`. 
Then I installed dependencies with the command `lerna bootstrap` (I tried even `yarn install`).
Then I added npm script: `"build": "neutrino build --use @neutrinojs/react-components"` into the coresponging `package.json`. 
Then I created file: `src/components/index.js` with the following code:
```js
import React from 'react';
export default () => <div>Hello World!</div>;
```
Then I called `lerna run build` at the root folder (I tried even local `yarn build`).
- What did you expect to happen?
I expected compiled code with just a component (it should have a size around 1kB).
- What actually happened, contrary to your expectations?
The compiled code contains React code (the size is around 8.35 kB).

The same problem is with `lerna bootstrap --hoist`. But when you use ordinary `lerna bootstrap` without `--hoist` and Yarn workspaces then it works as expected. So I think that the problem must be with something like `node_modules` folder.

Sry for my English.

_Update:_
I think that this is related: https://github.com/liady/webpack-node-externals/issues/39

**Comment by MatejMazur** [comment]
Ok, so after some digging I found this [comment](https://github.com/liady/webpack-node-externals/issues/39#issuecomment-356647854) which solves it.

**Comment by eliperelman** [comment]
Ah good catch! Yeah, my guess is it's a mismatch between `neutrino.options.root` which is `process.cwd()` and finding the `src` directory from there since it's more nested.

**Comment by MatejMazur** [comment]
Thanks for your response!

It would be good if I could somehow to set this for the whole monorepo. But I can't find a solution where I can set this for multiple packages. The `.neutrinorc.js` must be in the root of the package? There isn't any flag like `--config`?

**Comment by eliperelman** [comment]
You could `--use path/to/neutrinorc`.
