### ISSUE TITLE
Support for multiple dev servers

### ISSUE THREAD

**Issue by MatejMazur** [mozilla-neutrino/neutrino-dev#947]
Webpack devServer doesn't work for multiple apps.

Here is monorepo with the reproducible issue: https://github.com/MatejMazur/lerna-yarn-example
1) Install deps, and start dev:
```js
$ yarn install
$ yarn start
```
2) Open two browser tabs:
http://localhost:5000
http://localhost:5001

3) Change some code/text in `examples/my-app-2/src/components/App.js`.
(It should reload the localhost:5001 but it does nothing.)

4) Change some code/text in `examples/my-app/src/components/App.js`
(It reloads localhost:5000 but it reloads even localhost:5001.)

Please try to answer the following questions:

- What version of Neutrino are you using?
8.2.3
- Are you trying to use any presets? If so, which ones, and what versions?
`@neutrinojs/react` (8.2.3)
- Are you using the Yarn client or the npm client? What version?
Yarn 1.7.0.
- What version of Node.js are you using?
8.9.1
- What operating system are you using?
Windows 10
- What did you do?
I did `neutrino start` for multiple projects.
- What did you expect to happen?
It should reload the proper localhost:PORT
- What actually happened, contrary to your expectations?
It reloads only one localhost for one app with weird reloading of the other one.

**Comment by edmorley** [comment]
Hi! To override the port, it needs to be changed via `options.port` rather than manually changing via `devtool`, since otherwise it doesn't adjust the other things that are derived from `getPort()` such as `host` etc:
https://github.com/mozilla-neutrino/neutrino-dev/blob/release/v8/packages/dev-server/index.js#L6
