### ISSUE TITLE
Does Neutrino support both node application and web (with React) together?

### ISSUE THREAD

**Issue by hershmire** [mozilla-neutrino/neutrino-dev#979]
### Question

- What version of Neutrino are you using?
v8.3.0
- Are you trying to use any presets? If so, which ones, and what versions?
Node and React (v8.3.0)
- Are you using the Yarn client or the npm client? What version?
Yarn v1.7.0
- What version of Node.js are you using?
v8.11.3
- What operating system are you using?
MacOS
- What did you do?
Trying to setup a *multi-page* Node application that supports server-side-rendered React where Webpack is used on both the server and client-side. I've added both @neutrinojs/node and @neutrinojs/react and started wiring up multiple mains but when running `neutrino build` it will only build the client-side assets. Unsure if my use-case is possible with Neutrino as I haven't found anything in the docs. From what I can see, it appears it's intended use is to use one or the other but not both.

**Comment by eliperelman** [comment]
The Node.js and React presets are mutually exclusive. Using the React preset after using the Node.js one will override many of the Node.js preset options. Most likely you will want to augment the Node.js preset with settings specific to doing server-rendering of React pages, but currently there is no preset provided by Neutrino that does this for you.

**Comment by eliperelman** [comment]
I am closing this question as answered, if you feel I have not answered it appropriately, please feel free to re-open. Thank you!
