### ISSUE TITLE
Make @neutrinojs/node target the currently running node version

### ISSUE THREAD

**Issue by edmorley** [mozilla-neutrino/neutrino-dev#985]
At the moment `@neutrinojs/node` sets a `@babel/preset-env` target of:
```js
targets: {
  node: '8.3'
},
```

However `@babel/preset-env` also supports passing `'current'` as the version, which makes Babel target the same version of Node as is being used to run Babel:
https://babeljs.io/docs/en/next/babel-preset-env.html#targetsnode

This seem preferable for the `@neutrinojs/node` preset, since it's very likely that the version of Node being used to create the build, is the same version that will run it (the same cannot be said for the library preset when target=node) - and would mean that someone running a newer version of Node has as few Babel transforms being used as possible.

@eliperelman, thoughts? :-)

**Comment by eliperelman** [comment]
My thoughts for this preset have been to pin it to an LTS version of Node.js. I frequently change Node.js versions, so I'm not sure about my assumptions on this one.

**Comment by edmorley** [comment]
What use-case did you have in mind, that would be broken by using `'current'`? Having multiple node versions on the same machine is fine. I doubt people are building with one and then running with another (and if they are, they are in the 5% case, where Neutrino should be catering for the 80% case I think).
