### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by eliperelman** [mozilla-neutrino/neutrino-dev#99]
There are some good resources about efficient caching in this document from Webpack:

https://webpack.js.org/guides/caching/

We should look into the best settings to use for each preset and make changes where necessary.

**Comment by eliperelman** [comment]
It may also involve needing to use this plugin:

https://github.com/erm0l0v/webpack-md5-hash

**Comment by edmorley** [comment]
It looks like there are a few decisions to make:
1. Whether to use https://github.com/alexindigo/webpack-chunk-hash or https://github.com/erm0l0v/webpack-md5-hash for file content based hashing (it looks like the former is faster and a more maintained fork)
2. Whether to inline the manifest in the html too

**Comment by eliperelman** [comment]
Resolved in #223.
